lacework/go-sdk

api/client.go

We have been seeing a number of client timeouts on the Go API client,
this PR is increasing the default timeout from `10s` to `60s`.
Example error:
```
ERROR unable to send the request: Get "https://tech-ally.lacework.net/api/v1/external/integrations": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

chore(timeout): increase api timeout to 60s

---

cli/install.ps1
cli/install.sh

During some editing of the `install.sh` script I missed one variable name,
this PR is fixing that typo and using the correct variable name.
To run a local test, checkout this branch and run:
```
$ cat ./cli/install.sh | sudo bash
--> install: Installing the Lacework cli tool
--> install: Downloading via curl: https://github.com/lacework/go-sdk/releases/latest/download/lacework-cli-darwin-amd64.zip
--> install: Downloading via curl: https://github.com/lacework/go-sdk/releases/latest/download/lacework-cli-darwin-amd64.zip.sha256sum
/var/tmp/lacework.Jo1H/lacework-cli-latest.zip -> lacework-cli-darwin-amd64.zip
/var/tmp/lacework.Jo1H/lacework-cli-latest.zip.sha256sum -> lacework-cli-darwin-amd64.zip.sha256sum
--> install: Verifying the shasum digest matches the downloaded archive …
```

fix(cli): use correct variable inside install.sh

---

README.md
api/_examples/token-generation/main.go
cli/README.md
cli/install.ps1
cli/install.sh

This PR is updating documentation and the `install.ps1` script to add Windows
support for the Lacework CLI. 
To install the Lacework CLI, open a Powershell session as Administrator and run:
```
C:\> Set-ExecutionPolicy Bypass -Scope Process -Force
C:\> iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/lacework/go-sdk/master/cli/install.ps1'))
```

Update docs and `install.ps1` to add Windows supports

---

cli/install.ps1

Fix a small bug inside the `install.ps1`, after this PR is merged the PowerShell
install script should work:
```powershell
C:\> Set-ExecutionPolicy Bypass -Scope Process -Force
C:\> iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/lacework/go-sdk/master/cli/install.ps1'))
```
Spin up a Windows VM, or if you are running on Windows already, follow these steps
to test this change locally:
* Clone this repo and checkout this branch
* Open a PowerShell terminal as an Administrator
* Run the following commands:
```powershell
C:\> Set-ExecutionPolicy Bypass -Scope Process -Force
C:\> ./cli/install.ps1
```

fix(install.ps1) copy lacework.exe to ProgramData

---

cli/cmd/vulnerability.go

The command `lacework vul scan run` has now a `--poll` flag that will
lock the command and track the progress of the scan until completion.
```
$ lacework vulnerability scan run index.docker.io techallylw/lacework-cli-ubuntu18 latest --poll
A new vulnerability scan has been requested. (request_id: 7ac5dac2-7381-432f-8e64-d24105faf44a)
CONTAINER IMAGE DETAILS                                 |        VULNERABILITIES
------------------------------------------------------------------------------------------+---------------------------------
ID          sha256:8691d91057442af854be19c2d75c976e7cfca7c5aca8a6ef4498d9bd4d56a644   |   SEVERITY   COUNT   FIXABLE
Digest      sha256:9781fc23fc36970652acdfba82432637c059ea9f66bed9c5500a9d9cd6106f37   | -----------+-------+----------
Registry …
```

feat(cli): 'vul scan run' command can poll for status

---

cli/cmd/api.go
cli/cmd/cli_state.go
cli/cmd/integration.go
cli/cmd/outputs.go
cli/cmd/root.go
cli/cmd/vulnerability.go

We are adding a new Global Flag called `--json` that users can use to
switch the CLI output format to display JSON instead of the default,
human-readable format.
To make this setting persistent on the current terminal, a user can
export the environment variable `LW_JSON=1`.
An example of the JSON output when requesting an on-deman
vulnerability scan:
```
$ lacework vulnerability scan run index.docker.io techallylw/lacework-cli-ubuntu18 latest --json
{
"requestId": "241d943d-1b8f-42cc-be34-c1a1d9ae5297",
"status": "Scanning"
}
```

feat(cli): implement JSON format for all commands

---

api/integrations.go
api/integrations_test.go
api/vulnerabilities.go

Our API Server returns responses that can change 100%, this behavior is
making us omit a number of fields if they are empty so that we don't
present them to the end user.
There is a current bug that this change is fixing where if you try to
create a new Lacework Integration with the Go client, the request
generated will send the following body and the API Server will through a
500 Internal Server Error (in the k8s logs, Schema validation failure)
```json
{
"NAME": "Azure Activity Log",
"TYPE": "AZURE_AL_SEQ",
"ENABLED": 1,
"STATE": {
"ok": false,
"lastUpdatedTime": "",
"lastSuccessfulTime": ""
},
"DATA": {
"CREDENTIALS": {},
"TENANT_ID": "ID",
"QUEUE_URL": "URL"
}
}
```
We are avoiding adding the `STATE` field if it is empty so that we send
this request body instead:
```json
{
"NAME": …
```

fix(api): omitempty integration responses fields

---

api/api.go
api/events.go
api/events_test.go
cli/cmd/event.go

This change is adding a new `Events.Details(ID)` function that returns details
about the specified `event_id` plus adding a new `show` sub-command to the
`event` command inside the Lacework CLI. Such sub-command will show details
of a specific event.
Example: Human readable output
```
$ lacework event show 5
EVENT ID |               TYPE               |     ACTOR     |      MODEL       |      START TIME      |       END TIME
-----------+----------------------------------+---------------+------------------+----------------------+-----------------------
5 | CloudStorageIAMPermissionChanged | GcpAuditTrail | GcpAuditTrailCep | 2020-04-17T19:00:00Z | 2020-04-17T20:00:00Z
```
Example: Machine/JSON format
```
$ lacework event show 5 --json
{
"end_time": "2020-04-17T20:00:00Z",
"entity_map": { …
```

API Events Details imp + New `event show` CMD

---

cli/README.md
cli/cmd/api.go
cli/cmd/cli_state.go
cli/cmd/configure.go
cli/cmd/event.go
cli/cmd/integration.go
cli/cmd/root.go
cli/cmd/vulnerability.go

Introducing a new flag called `--noninteractive` that will disable interactive
progress bars (i.e. 'spinners'). This parameter can be configured via environment
variables using `LW_NONINTERACTIVE=1`.
Additionally, updated the `README.md` to display a list of all environment variables
available:
| Environment Variable | Description |
|----------------------|-------------|
|`LW_NOCOLOR=1`|turn off colors|
|`LW_DEBUG=1`|turn on debug logging|
|`LW_JSON=1`|switch commands output from human-readable to JSON format|
|`LW_NONINTERACTIVE=1`|disable interactive progress bars (i.e. spinners)|
|`LW_PROFILE="<name>"`|switch between profiles configured at `~/.lacework.toml`|
|`LW_ACCOUNT="<account>"`|account subdomain of URL (i.e. `<ACCOUNT>.lacework.net`)|
|`LW_API_KEY="<key>"`|access key id| …

feat(cli): noninteractive mode flag

---

api/integrations.go

This change is fixing a bug introduced with https://github.com/lacework/go-sdk/pull/67 where the `State` of the 
integration struct is now a pointer, and therefore we need to access it safely.

fix(cli): access integration state securely

---

api/api.go
api/auth.go
api/client.go
api/events.go
api/http.go
api/logging.go
lwlogger/logger.go
lwlogger/logger_test.go

To help the Go api client to log information messages that do not
overload the output we display, we are suppressing headers and body of
requests on `INFO` log level. If users wants to see those details, they
will have to set `DEBUG` to sniff inside the request and response
headers and bodies.

refactor(api): request and response log messages

---

api/vulnerabilities.go
cli/cmd/vulnerability.go

The Go api client shouldn't have anything related to the Lacework CLI,
the Go api should be an identical copy of the Lacework API as much as
possible. This change is moving the formatting of Tables from the api to
the cli go package.

style: avoid mixing duties between api/ and cli/

---

README.md
cli/cmd/api.go
cli/cmd/cli_state.go
cli/cmd/cli_update_cmd.go
cli/cmd/cli_update_cmd_windows.go
cli/cmd/event.go
cli/cmd/outputs.go
cli/cmd/version.go
cli/cmd/vulnerability.go
lwlogger/_examples/main.go
lwupdater/_examples/main.go
lwupdater/updater.go
lwupdater/updater_test.go

```
I would like to be kept up-to-date with the latest available versions,
So I can be aware of newer available versions and I can easily update.
```
How do we ensure that our users will update constantly? Software updates are
important because they often include critical patches to security holes, new
features, stability enhancements, and remove outdated features. All of these
updates are aimed at making the user experience better.
Introducing a new Go library called `lwupdater` that will check for available
updates of Lacework projects.
This new library aims to help our users to be kept up-to-date with the latest
version of our products, when users check for the current version installed on
their workstations, we are going to check if there are new versions …

feat: Lacework updater, keep users up-to-date

---

cli/cmd/vulnerability.go

This change is adding a new flag to the vulnerability command called
`--details`, this flag will extend the report shown to the end-user.
The new information presented with this flag is the list of CVE's with
its severity, version and, if any, fix version, plus the layer that the
vulnerability was introduced by.
Example:
```
$ lacework vulnerability report sha256:123ab...xyz --details
```
This flag is available to all sub-commands inside the `vulnerability`
cmd. (`lacework vul scan run`, `lacework vul scan show`, and 
`lacework vul report`, as shown above 👆🏽)
Closes https://github.com/lacework/go-sdk/issues/82

feat(cli): add --details flag to vulnerability cmd

---

cli/cmd/vulnerability.go

By default, on-demand vulnerability scans are requested by providing the
tag or digest of an image, therefore this change is modifying the
`vulnerability` command to be focused in digest as much as possible.
Though, we will provide a way to retrieve reports from image IDs.
To run an on-demand scan, a user will need the following information:
```
<registry>    container registry where the container image has been published
<repository>  repository name that contains the container image
<tag|digest>  either a tag or an image digest to scan (digest format: sha256:1ee...1d3b)
```
Note that we can't trigger scans with an image ID.
To review vulnerability reports from container image scans that run previously either
by the periodic scan mechanism that Lacework runs every hour, or a requested …

refactor(cli): consistency between image ID & Digest

---

api/integrations.go
cli/cmd/integration.go

The Go api client shouldn't have anything related to the Lacework CLI,
the Go api should be an identical copy of the Lacework API as much as
possible. This change is moving the formatting of Tables from the api to
the cli go package.

style: avoid mixing duties between api and cli

---

Dockerfile
Makefile
cli/images/amazonlinux-2/Dockerfile
cli/images/centos-8/Dockerfile
cli/images/debian-10/Dockerfile
cli/images/ubi-8/Dockerfile
cli/images/ubuntu-1804/Dockerfile
cli/images/windows-nanoserver/Dockerfile
scripts/release_containers.sh

Adding a number of docker containers with the Lacework CLI packaged
inside them, the list of containers we are adding:
- scratch (https://hub.docker.com/_/scratch)
- ubi-8
- debian-10
- centos-8
- ubuntu-1804
- amazonlinux-2
- windows-nanoserver
During release, we will be able to run the `make release-containers`
directive to build and push all these new docker containers.
By default, the docker container built from SCRATCH will be our main
image for our CI/CD pipeline story, any user or machine will be able to
run `docker run techallylw/lacework-cli` and have a 7MB container
running the latest Lacework CLI:
```
$ docker run techallylw/lacework-cli
The Lacework Command Line Interface is a tool that helps you manage the
Lacework cloud security platform. Use it to manage compliance reports, …
```

feat: Add lacework-cli containers

---

api/integrations_aws.go
api/integrations_azure.go
api/integrations_cont_reg.go
api/integrations_gcp.go
cli/cmd/event.go
cli/cmd/integration.go
go.mod
go.sum
scripts/release_containers.sh
vendor/github.com/mitchellh/mapstructure/.travis.yml
vendor/github.com/mitchellh/mapstructure/CHANGELOG.md
vendor/github.com/mitchellh/mapstructure/mapstructure.go
vendor/modules.txt

Adding a new sub-command `lacework integration show <int_guid>` to show
details about a specific external integration, example:
```
$ lacework int show TECHALLY_1234567890ABCDEF1234567890ABCDEF1234567890ABCDE
INTEGRATION GUID                     |    NAME    |  TYPE   | STATUS  | STATE
-----------------------------------------------------------+------------+---------+---------+--------
TECHALLY_1234567890ABCDEF1234567890ABCDEF1234567890ABCDE | GCP config | GCP_CFG | Enabled | Ok
INTEGRATION DETAILS
----------------------------------------------------------------------------------------------------------
LEVEL                | PROJECT
ORG/PROJECT ID       | techally-hipstershop
CLIENT ID            | 123456789001234567890
CLIENT EMAIL         | …
```

feat(cli): new 'integration show' cmd 

---

api/events.go
api/events_test.go
scripts/release_containers.sh

The `cpu_percentage` field inside the `entity_map` is a `float32`
not `int32`, this commit is fixing the following error:
```
ERROR unable to get event details: json: cannot unmarshal number 0.02 into Go struct field eventProcessEntity.data.entity_map.process.cpu_percentage of type int32
```
Closes #78
Additionally, I included a super quick fix to the build/release of our CLI containers. 

fix(api): parsing event details 'cpu_percentage' 

---

api/auth.go
api/client.go
api/events.go
api/integrations_aws.go
api/integrations_aws_test.go
api/integrations_gcp.go
api/integrations_gcp_test.go
cli/cmd/integration.go
cli/cmd/integration_aws.go
cli/cmd/integration_gcp.go
lwupdater/updater.go

This PR is just helping with the consistency of the ID field in Go
structs, the best practices says to call them `ID` and not `Id`.

chore: consistency with ID fields in Go structs

---

cli/cmd/event.go
cli/cmd/integration.go

To help users access both commands, `integration` and `event`, we are
adding aliases in plural since the natural thing to type when trying to
access all integrations or events is to write the command in plural.
Having aliases will allow users to run:
```
$ lacework events list
$ lacework integrations list
```

feat(cli): add aliases to integration and event cmds

---

cli/README.md
cli/cmd/configure.go

This change is adding an extra flag called `--json_file`, short that `-j`
that will allow users to load a generated API key JSON file from the WebUI.
Example: On this example, we create a set of API keys by logging in into
the Lacework WebUI, then download the keys and pass them to the Lacework
CLI to preconfigure it.
```
$ lacework configure --json_file /path/to/EXAMPLE_D3EFA214SD12DFSGRD3EFA214SD12DFSGR.json
```
The result of the above command is to only provide the "Account"
information, the API access key, and access secret will be preloaded.
**Jira Ticket: ALLY-104**

feat(cli): preconfigure using key file from the WebUI

---

cli/cmd/root.go

This small change will allow users to run `lacework help` without
failing with an error message. Just a nice UX addition! 😄 

style(cli): show help without errors

---

api/events.go

This PR is fixing the case where events with type `NewExternalServerDNSConn`
are sending the `bytes` field with a scientific notation format.
The error we are seeing is the following:
```
$ lacework event show 37
ERROR unable to get event details: json: cannot unmarshal number 6.873831E7 into Go struct field eventDnsNameEntity.data.entity_map.DnsName.total_out_bytes of type int32
```
Switching these fields to be `float32` seems to fix the parsing problem.

fix(api): use correct types on events response

---

api/events.go
cli/cmd/event.go
cli/cmd/outputs.go
internal/array/join.go

This change is making the `lacework event show ID` command more verbose
for our Human Readable Format. It will now display all entities.
Example:
```
$ lacework event show 78
+----------+---------------+------------+---------------+----------------------+----------------------+
| EVENT ID |     TYPE      |   ACTOR    |     MODEL     |      START TIME      |       END TIME       |
+----------+---------------+------------+---------------+----------------------+----------------------+
|       78 | NewViolations | Compliance | AwsCompliance | 2020-05-11T13:00:00Z | 2020-05-11T14:00:00Z |
+----------+---------------+------------+---------------+----------------------+----------------------+
+--------------+-----------------------------------------+----------------------------------------+
| …
```

feat: incident analysis, visualize event details

---

api/api.go
api/client.go
api/compliance.go
api/compliance_aws.go
api/compliance_azure.go
api/compliance_gcp.go
cli/cmd/compliance.go
cli/cmd/compliance_aws.go
cli/cmd/compliance_azure.go
cli/cmd/compliance_gcp.go
cli/cmd/configure.go
cli/cmd/integration.go
integration/compliance_test.go
integration/framework_test.go
integration/help_test.go
integration/integration_test.go

This change is adding the ability to manage compliance reports from the
Lacework CLI. As a prerequisite to start sending data about your
environment to Lacework for compliance reporting analysis, a user has to
configure one or more cloud integration using the following command:
```
```
Or, do it via the WebUI by logging in to Lacework at:
https://ACCOUNT.lacework.net
Then navigate to Settings > Integrations > Cloud Accounts.
Use the following command to list all available integrations in your
account:
```
$ lacework integrations list
```
To get the latest AWS compliance assessment report, use the new command
```
$ lacework compliance aws get-report <account_id>
```
These reports run on a regular schedule, typically once a day.
The available report formats are …

feat: manage compliance reports for GCP, Azure, and AWS

---

README.md
cli/README.md
cli/cmd/cli_unix.go

Since the Lacework CLI is being installed at `/usr/local/bin`, there is
no need for users to run the install script via `sudo`.

docs(cli): remove the need to install using sudo

---

cli/cmd/configure.go
cli/cmd/prompt.go
cli/cmd/prompt_test.go
integration/configure_test.go

When users configure the CLI and insert their API secret key, such
secret will now be formatted to avoid showing it on the screen.
Example:
```
$ lacework configure
▸ Account: tech-ally
▸ Access Key ID: TECHALLY_3ACE24322ABBD3AC4435608BACEC4D638BEC6500DC12345
▸ Secret Access Key: (*****************************f19e)
You are all set!
```
Closes https://github.com/lacework/go-sdk/issues/114

feat(cli): avoid displaying API key secret

---

Makefile
scripts/release.sh
scripts/release_containers.sh

This change is updating the release process as well as adding documentation
about how to do releases via a Wiki: https://github.com/lacework/go-sdk/wiki

Update Release Process

---

scripts/release.sh

I missed these things during the last release, I have verified full functionality since
I just released https://github.com/lacework/go-sdk/releases/tag/v0.1.13

fix(release): update release link and version message

---

cli/cmd/event.go

This fixes a misspelling of event header when showing details of an event. The word `Principal` was misspelled as `Pincipal`
Closes Issue [#118](https://github.com/lacework/go-sdk/issues/118) 
Signed-off-by: Scott Ford <scott.ford@lacework.net>

fix(spelling) Fixes event header misspelling

---

cli/cmd/configure.go
integration/configure_test.go

When users pass the `--profile` flag, the CLI will automatically
populate the account name with the provided profile:
```
$ lacework configure --profile new-account
▸ Account: new-account
```
Closes https://github.com/lacework/go-sdk/issues/98

feat: auto-populate account with --profile flag

---

api/vulnerabilities.go
cli/cmd/vulnerability.go

Make the Go API and the CLI to understand new payloads from the vuln
reports API endpoints that displays reports with 0 vulnerabilities,
we are now displaying a message to the user that explains that the
report has no vulnerabilities
The output shown to the end-user is for reports with 0 vulnerabilities:
```
$ lacework vul report sha256:32c5a42735581453d1e9ea664604fa81f4b635459dc88799ee1f8c373dca4819
Great news! This container image has no vulnerabilities.
```
And for the JSON format:
```
$ lacework vul report sha256:32c5a42735581453d1e9ea664604fa81f4b635459dc88799ee1f8c373dca4819 --json
{
"critical_vulnerabilities": 0,
"fixable_vulnerabilities": 0,
"high_vulnerabilities": 0,
"info_vulnerabilities": 0,
"low_vulnerabilities": 0,
"medium_vulnerabilities": 0,
"scan_status": "Success", …
```

feat: understand vuln reports with 0 vulnerabilities

---

.circleci/config.yml
cli/cmd/vulnerability.go
integration/event_test.go
integration/integration_test.go

Lacework runs vulnerability scans only against the following list of
supported distributions:
* https://support.lacework.com/hc/en-us/articles/360035472393-Container-Vulnerability-Assessment-Overview
Any other container image that is not listed there is unsupported and we
will be displaying an error message similar to:
```
$ lacework vul report sha256:04e8df550c7b52cd8ec64143a1c853cd76b234b29ad9e37149ffe04786acd142
Usage:
lacework vulnerability report <sha256:hash> [flags]
Flags:
--details    increase details about the vulnerability report
--digest     tread the provided sha256 hash as image digest (DEPRECATED) (default true)
-h, --help       help for report
--image_id   tread the provided sha256 hash as image id
Global Flags:
-a, --account string      account subdomain of URL (i.e. …
```

fix: vulnerability scans of unsupported images

---

scripts/release.sh

ci: upload artifacts to release

---

cli/cmd/vulnerability.go

Adding the ability to display only fixable vulnerabilities by providing
the new flag `--fixable`.
Example: From a total of 15 vulnerabilities, display only the 5 that are
fixable.
```
lacework vul report sha256:62dce44a0d2df7e3e3146817cc35681579c15a4ccd2c5d1f0bddb619fdd6dab8 --fixable
CONTAINER IMAGE DETAILS                                 |        VULNERABILITIES
------------------------------------------------------------------------------------------+---------------------------------
ID          sha256:1f40f2c68a11e338b7eda2264e71546ab1b5d6bc4c458bbd3785fd5efb3fc632   |   SEVERITY   COUNT   FIXABLE
Digest      sha256:62dce44a0d2df7e3e3146817cc35681579c15a4ccd2c5d1f0bddb619fdd6dab8   | -----------+-------+----------
Registry    index.docker.io …
```

feat(cli): add --fixable flag to vulnerability cmd

---

cli/cmd/event.go
integration/event_test.go

We are adding two flags to the `events list` command to provide a custom
time range:
```
$ lacework event list --end "2020-06-19T00:00:00Z" --start "2020-06-13T00:00:00Z"
```
If either a start or an end time is provided, both flags are required.

feat(cli): add time range flags to events list cmd

---

cli/cmd/vulnerability.go

As an Engineer fixing container vulnerabilities,
I would like to have a report that lists all the packages that contain vulnerabilities,
so that I can easily understand the total number of CVEs (vulnerabilities) of individual packages and
detect which packages introduce the most number of vulnerabilities.
The output of this new `--packages` flag looks like this:
```
lacework vulnerability report sha256:167ec3ad6d0368acc9d64b1d857c0208ac641da83209498d1f3da9f38c9ae9ec --packages
CONTAINER IMAGE DETAILS                                 |        VULNERABILITIES
------------------------------------------------------------------------------------------+---------------------------------
ID          sha256:32d9a0f8b7169d837120339f930117eeccbd7fb65f65415cf0a1a4970ff38ee9   |   SEVERITY   COUNT …
```

feat(cli): add --packages flag to vulnerability cmd

---

cli/cmd/configure.go

The first config we had in the Lacework CLI was a single account:
```toml
account = "dev"
api_key = "DEV_1234"
api_secret = "_abcd"
```
The new configuration file allows users to have multiple profiles, from
this commit, that is the only configuration file we support:
```toml
[default]
account = "prod"
api_key = "PROD_1234"
api_secret = "_abcd"
[dev]
account = "dev"
api_key = "DEV_1234"
api_secret = "_abcd"
```

chore(cli): remove deprecated old config loading

---

cli/cmd/configure.go
cli/cmd/root.go
integration/compliance_test.go
integration/configure_test.go
integration/help_test.go

>As a Lacework CLI user that uses the tool in CI/CD Pipelines,
>I want to have a non-interactive way to configure the Lacework CLI,
>So I don't have to manually create the config file `~/.lacework.toml` inside my pipeline.
When a user runs:
```
$ lacework configure -a foo -k bar -s bubu --noninteractive
```
The result is the creation of the `~/.lacework.toml` without asking the user
to validate the inputs. (non-interactive mode)
The command loads these settings from all sources, as usual, environment
variables, parameters (including `--json_file`), and the actual config file.
Closes https://github.com/lacework/go-sdk/issues/112

feat(cli): configure in non-interactive mode

---

api/api.go
api/events.go
api/events_test.go
api/vulnerabilities.go
api/vulnerabilities_test.go
cli/cmd/event.go

This new feature is adding two new functions `ListEvalutions()` and
`ListEvaluationsDateRange()` to the `Vulnerabilities` service inside the
Go API client, these endpoints wrap the new API endpoint:
`/external/vulnerabilities/container/GetEvaluationsForDateRange`
The functions will allow users to lists all evaluations in an account.
An example:
```go
package main
import (
"fmt"
"log"
"github.com/lacework/go-sdk/api"
)
func main() {
lacework, err := api.NewClient("account")
log.Fatal(err)
}
// List evaluations from the last 7 days
fmt.Println(lacework.Vulnerabilities.ListEvaluations())
}
```
Contributes to https://github.com/lacework/go-sdk/issues/156

feat(api): new Vulnerabilities.ListEvaluations() func

---

api/_examples/slack-channel-alert/main.go
api/integrations.go
api/integrations_slack_channel.go
api/integrations_slack_channel_test.go

With this change, users can now do CRUD operations of Slack Channel
Alerts, here is a quick basic usage:
Initialize a new SlackChanIntegration  struct, then use the new
instance to do CRUD operations.
```go
return err
}
slackChannel := api.NewSlackChannelIntegration("foo",
api.SlackChannelData{
SlackUrl: "https://hooks.slack.com/services/ABCD/12345/abcd1234",
MinAlertSeverity: 3,
},
)
client.Integrations.CreateSlackChannel(slackChannel)
```
**JIRA:** ALLY-101

feat(api): add Slack Channel integrations

---

api/integrations_slack_channel.go
api/integrations_slack_channel_test.go
cli/cmd/integration.go
cli/cmd/integration_slack_channel.go

Users now can create Slack Channel Alert Integrations via the CLI:
```
? Choose an integration type to create:  Slack Channel Alert
▸ Name:  #tech-ally-notify
▸ Slack URL:  https://hooks.slack.com/services/1234/ABC/abc123
▸ Alert Severity Level:  Critical
The integration was created.
```

feat(cli): Create Slack Channel Alerts 🚨

---

api/integrations_cont_reg.go
api/integrations_cont_reg_test.go

This change adds the Get and Update functions for the Container Registry
integrations.

feat(api): get/update container registry integrations

---

api/_examples/aws-cloudwatch-alert-channel/main.go
api/_examples/slack-alert-channel/main.go
api/integration_alert_channels.go
api/integration_alert_channels_aws_cloudwatch.go
api/integration_alert_channels_aws_cloudwatch_test.go
api/integration_alert_channels_slack.go
api/integration_alert_channels_slack_test.go
api/integration_alert_channels_test.go
api/integrations.go
cli/cmd/integration.go
cli/cmd/integration_aws_cloudwatch.go
cli/cmd/integration_slack_channel.go

Users now can create AWS CloudWatch Alert Channel Integrations via the CLI:
? Choose an integration type to create:  AWS CloudWatch Alert Channel
▸ Name:  cloud-watch-test
▸ Event Bus ARN:  arn:aws:events:us-west-2:1234567890:event-bus/default
▸ Alert Severity Level:  All
The integration was created.
With this change users can now do CRUD operations of AWS CloudWatch
Alert Channels (Integrations), here is a basic usage:
Initialize a new `AwsCloudWatchAlertChannel` struct, then use the new
instance to do CRUD operations.
```go
return err
}
awsCloudWatch := api.NewAwsCloudWatchAlertChannel("foo",
api.AwsCloudWatchData{
EventBusArn: "arn:aws:events:us-west-2:1234567890:event-bus/default",
MinAlertSeverity: …
```

feature: AWS CloudWatch Alert Channel Integrations

---

api/_examples/pagerduty-alert-channel/main.go
api/integration_alert_channels_pagerduty.go
api/integration_alert_channels_pagerduty_test.go
api/integrations.go

With this change users can now do CRUD operations of PagerDuty
Alert Channels (Integrations), here is a basic usage:
Initialize a new `PagerDutyAlertChannel` struct, then use the new
instance to do CRUD operations.
```go
return err
}
alert := api.NewPagerDutyAlertChannel("foo",
api.PagerDutyData{
IntegrationKey:   "1234abc8901abc567abc123abc78e012",
MinAlertSeverity: api.MediumAlertLevel,
},
)
client.Integrations.CreatePagerDutyAlertChannel(alert)
```

feat(api): add PagerDuty alert channel integrations

---

cli/cmd/integration.go
cli/cmd/integration_pagerduty.go

Users now can create PagerDuty Alert Channel Integrations via the CLI:
```
? Choose an integration type to create:  PagerDuty Alert Channel
▸ Name:  pagerduty-test
▸ Integration Key:  1234abc8901abc567abc123abc78e012
▸ Alert Severity Level:  All
The integration was created.
```

feat(cli): Create PagerDuty Alert Channels 🚨

---

cli/cmd/integration.go
integration/integration_test.go

When trying to access an integration GUID that doesn't exist, the CLI
will return an error message like the following one:
```
$ lacework integrations show TECHALLY_1
Usage:
lacework integration show <int_guid> [flags]
Flags:
-h, --help   help for show
Global Flags:
-a, --account string      account subdomain of URL (i.e. <ACCOUNT>.lacework.net)
-k, --api_key string      access key id
-s, --api_secret string   secret access key
--debug               turn on debug logging
--json                switch commands output from human-readable to json format
--nocolor             turn off colors
--noninteractive      turn off interactive mode (disable spinners, prompts, etc.)
-p, --profile string      switch between profiles configured at ~/.lacework.toml
ERROR the provided integration GUID was …
```

fix(cli): error showing non-existing integration

---

.circleci/config.yml
Makefile

This change is adding support to run Lacework CLI integration tests on Windows machines.

ci(integration): add windows support

---

cli/cmd/compliance.go
cli/cmd/compliance_aws.go
cli/cmd/compliance_azure.go
cli/cmd/compliance_gcp.go

This change deprecates `--pdf-file` in favor of `--pdf`, example:
```
$ lacework compliance aws get-report 123456789000 --pdf
The AWS compliance report was downloaded at 'AWS_CIS_S3_Report_123456789000_my-account_20200729134124.pdf'
```
Closes https://github.com/lacework/go-sdk/issues/122

refactor(cli): replace '--pdf-file' for '--pdf'

---

api/integration_alert_channels_jira.go
api/integration_alert_channels_jira_test.go
api/integrations.go
cli/cmd/integration.go
cli/cmd/integration_jira.go

With this change users can now do CRUD operations of Jira
Alert Channels (Integrations), here is a basic usage:
Initialize a new `JiraAlertChannel` struct, then use the new
instance to do CRUD operations.
```go
return err
}
jiraAlert := api.NewJiraAlertChannel("foo",
api.JiraAlertChannelData{
MinAlertSeverity: api.CriticalAlertLevel,
JiraType:         api.JiraCloudType,
JiraUrl:          "mycompany.atlassian.net",
IssueType:        "Bug",
ProjectID:        "EXAMPLE",
Username:         "me",
ApiToken:         "my-api-token",
IssueGrouping:    "Resources",
},
)
client.Integrations.CreateJiraAlertChannel(jiraAlert)
```

feat(api): add Jira alert channel integrations

---

api/auth.go
api/client.go
cli/cmd/access_token.go
integration/help_test.go

This new command will allow users to generate access tokens:
```
$ lacework access-token --duration_seconds 7200
```
Closes https://github.com/lacework/go-sdk/issues/172

feat(cli): new access-tokens command

---

api/integration_alert_channels_aws_cloudwatch.go
api/integration_alert_channels_aws_cloudwatch_test.go
api/integration_alert_channels_jira.go
api/integration_alert_channels_jira_test.go
api/integration_alert_channels_pagerduty.go
api/integration_alert_channels_pagerduty_test.go
api/integration_alert_channels_slack.go
api/integration_alert_channels_slack_test.go
cli/cmd/integration.go
cli/cmd/integration_aws_cloudwatch.go
cli/cmd/integration_jira.go
cli/cmd/integration_pagerduty.go
cli/cmd/integration_slack_channel.go

The team was not aware of the fact that that the `min_alert_severity`
field is a legacy field that is no longer in use by the platform, it was
deprecated in favor of Alert Rules.

refactor: remove legacy field min_alert_severity

---

api/api.go
api/client.go
api/lql.go
cli/cmd/lql.go

This feature is NOT yet released but we want to start experimenting and
using LQL inside the Lacework CLI, the feature is hidden and the endpoit
is not enabled on any Lacework account in production.
To run a simple LQL query, run:
```
$ lacework lql 'SimpleLQL_3(RecentComplianceReports Data) {SELECT Data.*}'
```

alpha+feat: run LQL queries

---

cli/cmd/configure.go
integration/configure_test.go

This change will add a better user-experience to the `lacework configure`
command so that if the user provides the complete URL as the account
name we will subtract the account and notify the end-user:
```
$ lacework configure
Passing '.lacework.net' domain not required. Using 'tech-ally'
▸ Account: tech-ally
▸ Access Key ID: TECHALLY_1234567890
▸ Secret Access Key: (*****************************91f3)
You are all set!
```
Closes https://github.com/lacework/go-sdk/issues/86

feat(cli): better ux in account validation

---

api/events.go
cli/cmd/event.go
cli/cmd/integration.go
integration/event_test.go

Show me all the events from the past day:
``` 
$ lacework events list --days 1
```
Show me all the events from the past three days:
``` 
$ lacework events list --days 3
```
Show me all the events from the last 7 days that has severity high and above (Critical & High)
```
$ lacework events list --severity high
```
Show me all the events from the last day that has severity medium and above (Critical, High and Medium)
```
$ lacework events list --severity medium --days 1
```
Provide only the start time for the time range:
```
$ lacework events list --start 2020-08-18T00:00:00Z
```
Closes https://github.com/lacework/go-sdk/issues/195
Closes https://github.com/lacework/go-sdk/issues/192

feat: add event flags --severity and --days

---

cli/cmd/event.go
integration/event_test.go

Users can now use this new command to do further investigation on an
event:
```
$ lacework event open 123
```
Additionally, we now display a URL at the end of the command:
```
$ lacework event show 123
...
For further investigation of this event navigate to https://account.lacework.net/ui/investigation/recents/EventDossier-123
```
Closes https://github.com/lacework/go-sdk/issues/194

feat(cli): new open event command

---

api/_examples/aws-cloudwatch-alert-channel/main.go
api/_examples/jira-cloud-with-custom-template-alert-channel/main.go
api/_examples/slack-alert-channel/main.go
api/integration_alert_channels_jira.go
api/integration_alert_channels_jira_test.go
cli/cmd/integration_jira.go
integration/event_test.go

This change allows users to use the `CustomTemplateFile` field inside
the `JiraAlertChannelData` struct to pass a Custom Jira Template.
An example:
```go
func main() {
lacework, err := api.NewClient("account", api.WithApiKeys("KEY", "SECRET"))
log.Fatal(err)
}
jiraTemplateJSON := `{
"fields": {
"labels": [
"myLabel"
],
"priority":
{
"id": "1"
}
}
}`
jira := api.JiraAlertChannelData{
JiraType:      api.JiraCloudAlertType,
JiraUrl:       "mycompany.atlassian.net",
IssueType:     "Bug",
ProjectID:     "TEST",
Username:      "my@username.com",
ApiToken:      "my-api-token",
IssueGrouping: "Resources",
}
jira.EncodeCustomTemplateFile(jiraTemplateJSON)
jiraAlert := api.NewJiraAlertChannel("integration_name", jira)
client.Integrations.CreateJiraAlertChannel(jiraAlert)
}
``` …

feat(api): encode custom_template_file for Jira int

---

api/integration_alert_channels_jira.go
api/integration_alert_channels_jira_test.go
cli/cmd/integration.go

This will help the CLI and Terraform provider to decode the Custom Template File that the API returns:
```
$ lacework int show TECHALLY_9D32C5DB324FEB13B9D24988E6216B5EC448A3B8B2631DF
INTEGRATION GUID                     |              NAME              | TYPE | STATUS  | STATE
-----------------------------------------------------------+--------------------------------+------+---------+--------
TECHALLY_9D32C5DB324FEB13B9D24988E6216B5EC448A3B8B2631DF | My Jira Cloud Alert Channel    | JIRA | Enabled | Check
INTEGRATION DETAILS
-------------------------------------------------------------
JIRA INTEGRATION TYPE | JIRA_CLOUD
JIRA URL              | mycompany.atlassian.net
PROJECT KEY           | EXAMPLE
USERNAME              | my@username.com
ISSUE TYPE            | Bug
ISSUE GROUPING …
```

feat: add decoder for jira custom_template_file

---

api/integrations_ctr_reg.go
api/integrations_ctr_reg_ecr.go
api/integrations_ctr_reg_ecr_test.go
api/integrations_ctr_reg_test.go
cli/cmd/integration.go
cli/cmd/integration_docker_v2.go
cli/cmd/integration_ecr.go
cli/cmd/integration_gcr.go

```go
api.NewDockerHubRegistryIntegration(integrationName, api.ContainerRegData{})
```
```go
api.NewDockerV2RegistryIntegration(integrationName, api.ContainerRegData{})
```
```go
api.NewAwsEcrRegistryIntegration(integrationName, api.AwsEcrData{})
```
```go
api.NewGcrRegistryIntegration(integrationName, api.ContainerRegData{})
```

feat: add DockerV2, ECR and GCR container registries

---

cli/cmd/package_manifest.go
cli/cmd/root.go
cli/cmd/vuln_host.go
integration/host_vulnerability_test.go

This Pull Request is improving the way we scan package-manifests, this is all
about User Experience (UX).
We want to help our users to adopt our CI/CD story and make it easy for them
to scan their package manifests, with that mentality we are introducing a couple
new feature to the Lacework CLI.
Generating a package manifest could be confusing for some users, if you are an
expert you will probably have your own Python scripts ready to be piped to our
APIs, but if you are not, we have a new command for you: 
```
root@7c42aed31953:/# lacework vulnerability host generate-pkg-manifest
{
"os_pkg_info_list": [
{
"os": "ubuntu",
"os_ver": "18.04",
"pkg": "adduser",
"pkg_ver": "3.116ubuntu1"
},
{
"os": "ubuntu",
"os_ver": "18.04",
"pkg": "zlib1g",
"pkg_ver": "1:1.2.11.dfsg-0ubuntu2"
}
]
}
``` …

feat(ux): generate package-manifest automatically

---

api/vulnerabilities_host.go
cli/cmd/vuln_host.go
integration/host_vulnerability_test.go

Since all our other commands always provide a nice summary table, we are
adding one to the `scan-pkg-manifest` command! :100:
New output looks like:
```
$ lacework vuln host scan-pkg-manifest --local --fixable
VULNERABILITIES
------------------------------------
SEVERITY    COUNT   FIXABLE
-------------+-------+----------
Critical         0         0
High            16         0
Medium           6         1
Low              8         1
Negligible       0         0
CVE       | SEVERITY | SCORE | PACKAGE |   VERSION    |  FIX VERSION
-----------------+----------+-------+---------+--------------+-----------------
CVE-2019-3817  | Medium   | 8.8   | librepo | 1.11.0-2.el8 | 0:1.10.3-3.el8
CVE-2018-20534 | Low      | 6.5   | librepo | 1.11.0-2.el8 | 0:1.10.3-3.el8
```
Signed-off-by: Salim …

feat(cli): add scan-pkg-manifest summary 📈

---

cli/README.md
cli/install.sh

When installing the Lacework CLI we use the default directory /usr/local/bin but
some operating systems require sudo privileges to put files in that location, we
need to make the installation directory customizable. 🥇
To install the Lacework CLI on a custom directory use:
```bash
$ curl https://raw.githubusercontent.com/lacework/go-sdk/master/cli/install.sh | bash -s -- -d /custom/path
```
Closes https://github.com/lacework/go-sdk/issues/221

feat(cli): allow custom installation directory -d 📁

---

cli/cmd/cli_state.go
cli/cmd/cli_unix.go
cli/cmd/cli_windows.go
cli/cmd/configure.go
cli/cmd/event.go
cli/cmd/root.go
integration/configure_list_test.go
integration/configure_show_test.go
integration/configure_unix_test.go
integration/configure_windows_test.go
integration/framework_test.go
integration/help_test.go

We are adding two new subcommands to the `lacework configure` command.
The `lacework configure list` command will list all profiles configured
into the configuration file `~/.lacework.toml`
The `lacework configure show <config_key>` command prints the current
computed configuration data from the specified configuration key. The
order of precedence to compute the configuration is flags, environment
variables, and the configuration file ~/.lacework.toml.
The available configuration keys are:
* `profile`
* `account`
* `api_secret`
* `api_key`
To show the configuration from a different profile, use the flag `--profile`
```
$ lacework configure show account --profile my-profile
```
Closes https://github.com/lacework/go-sdk/issues/209

feat(cli): programatic access to profile data

---

cli/cmd/package_manifest.go
cli/cmd/vuln_host.go
scripts/release.sh

We have identified a bug in the Lacework CLI where we didn't add the
epoch for Centos/RHEL systems, this field would change drastically
the results of the package manifest scanner and therefore, we were
having inaccurate results.
This PR is adding the epoch and matching the output with the container
vulnerability scanner when there are no vulnerabilities via the package
manifest scanner.
```
[root@1f341170e7db /]# lacework vuln host scan-pkg-manifest --local
Great news! The localhost has no vulnerabilities... (time for 🌮 )
```
Jira: ALLY-215

fix(cli): add epoch to package manifest

---

api/api.go
api/compliance.go
api/integrations_aws.go
api/integrations_aws_test.go
api/integrations_azure.go
api/integrations_azure_test.go
api/integrations_gcp.go
api/integrations_gcp_test.go

We are implementing a temporal workaround to mimic the behavior that is
codified inside the Lacework UI where, it automatically triggers an initial
report after the creation of Cloud Account Integrations, specifically for
Compliance (`AWS_CFG`, `GCP_CFG`, and `AZURE_CFG`)
This pull request coves the following projects:
* Go Client: https://github.com/lacework/go-sdk/tree/master/api
* Lacework CLI: https://github.com/lacework/go-sdk/tree/master/cli
We will remove this workaround when RAIN-13422 is done.
JIRA: ALLY-196

feat(api): trigger initial report automatically

---

.circleci/config.yml
.gitignore
cli/cmd/vuln_container.go
cli/cmd/vulnerability.go
integration/container_vulnerability_test.go
integration/framework_test.go
scripts/release.sh

I missed to add the logic to generate the HTML file for the commands
`scan` and `scan-status`. :facepalm:
I am also adding tests to cover the new HTML flag, as well as some improvements
to the release script.

fix(cli): generate html for scan commands

---

integration/container_vulnerability_test.go

Since `amazonlinux-2` tag has no vulnerabilities:
```
➜  ~ lacework vuln ctr scan index.docker.io lacework/lacework-cli amazonlinux-2 --poll --html
A new vulnerability scan has been requested. (request_id: c60ae155-858c-4e76-8874-33010c081e8b)
Great news! This container image has no vulnerabilities... (time for 🌮 )
```

ci: set container tag to debian-10 that has vulns

---

api/errors.go
api/errors_test.go
api/integrations_test.go

This change is making the error check handler to understand better the
error messages sent from the Lacework API, it also formats them a bit
better so that human can read them.
```
[POST] https://tech-ally.lacework.net/api/v1/external/vulnerabilities/container/repository/images/scan: 400
```
```
[POST] https://tech-ally.lacework.net/api/v1/external/vulnerabilities/container/repository/images/scan
[400] Could not find integraion matching the registry provided
```
This will also improve the error messages from the Lacework CLI:
```
$ lacework vuln ctr scan foo bar tag
ERROR unable to request on-demand vulnerability scan: [POST] https://tech-ally.lacework.net/api/v1/external/vulnerabilities/container/repository/images/scan: 400
```
```
$ lacework vuln ctr scan foo bar tag
ERROR unable to …
```

refactor(api): better error check handler

---

api/_examples/jira-cloud-with-custom-template-alert-channel/main.go
api/integrations_aws.go
api/integrations_aws_test.go
cli/cmd/integration_aws.go

This change is enabling the Go API to send a Base64 encode file
containing the Accoutn Mapping File, documentation can be found:
https://support.lacework.com/hc/en-us/articles/360055993554-Setup-of-Organization-AWS-CloudTrail-Integration
**Jira:** ALLY-235

feat(api): enable account mapping file for CT int

---

api/integrations_aws.go
api/integrations_aws_test.go
cli/cmd/integration.go
cli/cmd/integration_aws.go

This refactor is modifying the behavior of the Encode and Decode
functions to use `[]byte` instead of `string`, this way we won't be
casting its content back and forth like this example:
https://github.com/lacework/terraform-provider-lacework/pull/43
Additionally, I have made the `lacework integration show` command to
display the account mapping content.
```
$ lacework int show TECHALLY_53DFFB3E788A30BD84AD1822B06473018B2B4CBA0C1AD4C
INTEGRATION GUID                     |              NAME              |    TYPE    | STATUS  | STATE
-----------------------------------------------------------+--------------------------------+------------+---------+--------
TECHALLY_53DFFB3E788A30BD84AD1822B06473018B2B4CBA0C1AD4C | A consolidated CloudTrail      | AWS_CT_SQS | Enabled | Ok
INTEGRATION …
```

refactor: account mapping file for consolidated CT

---

api/vulnerabilities_host.go
cli/cmd/package_manifest.go
cli/cmd/vuln_host.go
cli/cmd/vuln_html.go

The API response coming from the Lacework server contains too much
information that could confuse our users, this change is cleaning the
response by removing all vulnerabilities that don't match, that is, those
vulnerabilities that have the evaluation status equal to `VULNERABLE`.
This fix is modifying both, the human-readable and JSON outputs.
With these changes, the CLI results match what the UI shows on the daily scan:

fix: false positive results in pkg-manifest scan

---

cli/install.sh

Closes https://github.com/lacework/go-sdk/issues/249
JIRA: https://lacework.atlassian.net/browse/ALLY-250

fix(install.sh): avoid logging with 'info' cmd

---

api/agent.go
cli/cmd/agent.go

This change is making the `api.AgentTokenResponse` to have the field
`Props` to be a pointer of `AgentTokenProps`, this way we are not
sending an empty description and updating it.

fix(api): avoid updating AgentTokenResponse.Props

---

cli/cmd/agent.go
cli/cmd/compliance.go
cli/cmd/compliance_aws.go
cli/cmd/compliance_azure.go
cli/cmd/compliance_gcp.go
cli/cmd/configure.go
cli/cmd/event.go
cli/cmd/integration.go
cli/cmd/table_render.go
cli/cmd/table_render_test.go
cli/cmd/vuln_container.go
cli/cmd/vuln_host.go
cli/cmd/vulnerability.go
integration/agent_token_test.go
integration/host_vulnerability_test.go

This refactor is adding a new function named `renderSimpleTable()` used
to render any simple table within the Lacework CLI, every command should
leverage this function unless there are extra customizations required,
if so, use instead `renderCustomTable()`. The benefit of this function
is the ability to switch/update the look and feel of the human-readable
format across the entire project.
The function `renderSimpleTable()` receives two arguments, the headers
(`[]string`), and the rows. (`[][]string`)
For example, to render a simple table like the following one:
```
KEY    VALUE
-------+---------
key1   value1
key2   value2
key3   value3
```
The code would look like:
```go
cli.OutputHuman(
renderSimpleTable(
[]string{"KEY", "VALUE"},
[][]string{
[]string{"key1", "value1"}, …
```

refactor(cli): abstract rendering tables (human-readable)

---

.circleci/config.yml
Makefile
go.mod
scripts/release.sh

From community contribution: https://github.com/lacework/go-sdk/pull/235
We are upgrading the Go version to 1.15. On this version the **macOS arch 386 is
unsupported** and therefore, we are roving the building and releasing that binary.
```
$ make install-cli
1 errors occurred:
--> darwin/386 error: exit status 2
Stderr: cmd/go: unsupported GOOS/GOARCH pair darwin/386
```

build: upgrade Go version to 1.15

---

cli/cmd/integration.go

The account mapping file is not rendering correctly:
```
ACCOUNT MAPPING FILE    {
"defaultLaceworkAccountAws":
"customerdemo",
"integration_mappings": {
"mini-ally": {
"aws_accounts": [
"123456789012"       ]
},     "tech-ally": {
"aws_accounts": [
"123456789012"       ]     }
} }
```
After this change this field will look correctly:
```
ACCOUNT MAPPING FILE    {
"defaultLaceworkAccountAws": "customerdemo",
"integration_mappings": {
"mini-ally": {
"aws_accounts": [
"123456789012"
]
},
"tech-ally": {
"aws_accounts": [
"123456789012"
]
}
}
}
```

fix(cli): render account mapping file correctly

---

api/_examples/webhook-alert-channel/main.go
api/integration_alert_channels_slack.go
api/integration_alert_channels_webhook.go
api/integration_alert_channels_webhook_test.go
api/integrations.go
cli/cmd/integration.go
cli/cmd/integration_webhook.go

Users can do CRUD operations of Webhook Channel Alerts
+
Users can create Webhook Channel Alert Integrations via the CLI
Signed-off-by: Darren Murray darren.murray@lacework.net

feat(api): add Webhook integration

---

README.md
cli/README.md
cli/cmd/root.go
cli/cmd/version.go
integration/framework_test.go
integration/version_test.go
lwupdater/README.md
lwupdater/_examples/main.go
lwupdater/updater.go
lwupdater/updater_test.go

As a Lacework user that leverages the Command-line Interface,
I would like to have a daily reminder that there is a new version I can upgrade to,
So that I know about the new features and functionalities released and I can easily upgrade and use them.
This change is adding a post function that will verify the version of the Lacework CLI daily,
this function will run (only once a day) on every command.
New users will have the following experience:
```
$ lacework integrations list
INTEGRATION GUID                             NAME              TYPE        STATUS    STATE
-----------------------------------------------------------+-------------------+---------------+---------+--------
TECHALLY_82043CC9554F32F8CE80317B54C486926B56A25CC9E0977   #tech-ally-notify   SLACK_CHANNEL   Enabled …
```

feat(cli): daily version check

---

api/integrations_aws.go
api/integrations_aws_test.go
api/integrations_azure.go
api/integrations_azure_test.go
api/integrations_gcp.go
api/integrations_gcp_test.go

The automatic report triggering is now happening in the platform as part
of the creation of new compliance integrations. We are removing the
workaround we put in place while the platfom team was working on this.
JIRA: ALLY-257

refactor(api): remove automatic report trigger

---

.circleci/config.yml

Add condition before mv command to prevent "No such file or directory" error 

ci: fix mv on non exisitent directory

---

api/_examples/aws-s3-alert-channel/main.go
api/integration_alert_channels_aws_s3.go
api/integration_alert_channels_aws_s3_test.go
api/integrations.go
cli/cmd/integration.go
cli/cmd/integration_aws_s3_channel.go

feat: add AWS S3 alert channel integration

---

cli/install.sh

Before this change, any error trying to install the Lacework CLI
was ignored, this change is fixing that bug by propagating the
error to the end-user.
```
[ec2-user@ip-10-0-1-19 ~]$ curl https://raw.githubusercontent.com/lacework/go-sdk/2470b0480b753867a55484ea0a0156ac83d70201/cli/install.sh | bash
--> install: Installing the Lacework CLI
--> install: Downloading via curl: https://github.com/lacework/go-sdk/releases/latest/download/lacework-cli-linux-amd64.tar.gz
--> install: Downloading via curl: https://github.com/lacework/go-sdk/releases/latest/download/lacework-cli-linux-amd64.tar.gz.sha256sum
renamed '/var/tmp/tmp.hPKMHbT7oF/lacework-cli-latest.tar.gz' -> 'lacework-cli-linux-amd64.tar.gz'
renamed '/var/tmp/tmp.hPKMHbT7oF/lacework-cli-latest.tar.gz.sha256sum' -> …
```

fix(cli): propagate errors from install.sh

---

.circleci/config.yml
cli/cmd/honeyvent.go
cli/cmd/package_manifest.go
cli/cmd/package_manifest_test.go

The default behavior of most Linux distros is to keep the last `N` kernel
packages installed for users that need to fall back in case the new
kernel does not boot.  However, the presence of the package does not mean
that kernel is active.  We must continue to allow the standard kernel
package preservation behavior without providing false-positives of
vulnerabilities that are not active.
This feature detects the active kernel and removes any other
installed-and-inactive kernel from the generated package manifest.
Additionally, we are adding instrumentation to trace the CLI feature
`gen_pkg_manifest` and understand how often is it used and find out
if there are problems with it.
With feature data:
```json
{
"active_kernel": "4.14.209-160.339.amzn2.x86_64",
"kernel_suppressed_158": …
```

feat(cli): gen-pkg-manifest detect running kernel

---

.circleci/config.yml
.gitignore
Makefile
scripts/release.sh

Enabling generating and storing code coverage in HTML format! 🙌🏽
Now every commit/pull-request will generate an HTML artifact that can be found inside Circle CI:
Job Example: https://app.circleci.com/pipelines/github/lacework/go-sdk/896/workflows/60a38854-ed2f-48e7-8907-35eb774a1f00/jobs/3217/artifacts

ci: generate code coverage in HTML format

---

api/client.go
cli/cmd/honeyvent.go
cli/cmd/package_manifest.go
cli/cmd/package_manifest_test.go
cli/cmd/vuln_host.go

As a user of the Lacework CLI,
I would like to be able to submit scans of package manifests bigger than 1,000 packages,
So I don't have to implement a splitting mechanism and run multiple CLI commands for a single manifest.
The CLI will now check if the package manifest has more than the maximum
number of packages, if so, it will split the package manifest into
multiple chunks and trigger multiple API requests.
**NOTE:** We disallow more than 10 parallel requests (workers), which
are more than 10,000 packages on a single manifest/system.
Closes https://github.com/lacework/go-sdk/issues/237
**JIRA: ALLY-275**

feat(cli): support manifest bigger than 1k packages

---

cli/cmd/configure.go
integration/configure_unix_test.go

We have found out that users are trying to pass the full URL as the
account setting when running the `configure` command:
```
$ lacework configure
▸ Account: http://my-account.lacework.net/
```
This change is adding a check to catch when users pass the prefix
`http://` or `https://`.
**JIRA: ALLY-280**

feat(cli): add account check to catch http(s)://

---

cli/cmd/root.go

If the user is running the command `lacework version` we don't need to
run a daily version check, so we are skipping it for that command.
Closes https://github.com/lacework/go-sdk/issues/287
JIRA: ALLY-285

fix(cli): skip daily version check for version cmd

---

cli/cmd/cli_unix.go
cli/cmd/cli_unix_test.go

Update the display message from UpdateCommand() function to check for homebrew managed Lacework CLI users. Displays `brew upgrade lacework-cli` command instead of the default curl command.

feat(cli): support Homebrew upgrade command

---

cli/cmd/cli_unix.go
cli/cmd/honeyvent.go
cli/cmd/honeyvent_test.go

Add telemetry to detect when customers are running the Lacework CLI that has been installed via Homebrew.

feat: Add telemetry to detect Homebrew installations

---

cli/install.sh

If the user provides a target, the `install.sh` script should honor that option
and try to install it without verifying the running system.
Example: Running on a macOS ARM arch, we get the following error.
```
$ curl https://raw.githubusercontent.com/lacework/go-sdk/master/cli/install.sh | bash -s -- -t darwin-amd64
--> install: Installing the Lacework CLI
xxx install: architecture not supported: arm64
```
This change is fixing the script to respect the provided target, the expected behavior of running the above
command on the same ARM system should be:
```
$ curl https://raw.githubusercontent.com/lacework/go-sdk/master/cli/install.sh | bash -s -- -t darwin-amd64
--> install: Installing the Lacework CLI
--> install: Downloading via wget: …
```

fix(cli): install.sh should respect target override

---

cli/cmd/version.go
cli/install.sh
integration/event_test.go

When users install the CLI we should not run the daily update check
since it could create files on the home directory of a mortal user.
Additionally, we are turning off telemetry so that we don't have
multiple events being reported on install.
JIRA: ALLY-305

fix(cli): avoid daily update check during install

---

integration/event_test.go

If our Lacework account doesn't have any events (which has been the case for the past week),
these tests will fail continuously. This change is fixing the events test to only verify table headers
when there are events.

test: fix intermittent events test

---

api/_examples/microsoft-teams-alert-channel/main.go
api/integration_alert_channels_microsoft_teams.go
api/integration_alert_channels_microsoft_teams_test.go
api/integrations.go
cli/cmd/integration.go
cli/cmd/integration_microsoft_teams.go

feat: New Microsoft Teams alert channel

---

integration/container_vulnerability_test.go

The team have decided to disable these integration tests that have been failing
constantly, we will enable them once RAIN-15300 is resolved.

test(cli): disable failing tests (RAIN-15300)

---

.circleci/config.yml
Makefile
cli/cmd/vulnerability.go
integration/container_vulnerability_test.go

We are improving the retry mechanism to be exponential instead
of a fixed time. The times now will start with 5s, then wait for
10s, 16s, 25s, and so forth.
Closes RAIN-15292
We did 5s intervals
We are doing exponential wait times; 5s, 10s, 16s, 25s, and so forth.

refactor(cli): exponential retries polling scans

---

api/client.go
api/client_test.go
cli/cmd/cli_state.go

Currently, the Lacework CLI has a timeout of 60 seconds and users
are experiencing the following errors:
```
context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```
We are increasing the timeout to match what we have on NGINX which
is 120 seconds, we add 5 more seconds to let NGINX close the connection
instead of the Lacework CLI.
Closes RAIN-15291

fix(cli): match API client timeout with NGINX

---

cli/cmd/vuln_host.go

This update is to reflect the new limit of packages that the
Lacework CLI supports.
The Wiki has been updated already: https://github.com/lacework/go-sdk/wiki/CLI-Documentation#host-vulnerability-assessments

doc(cli): update scan-pkg-manifest help to 10k pkgs

---

api/compliance.go
cli/README.md
cli/cmd/compliance.go
cli/cmd/compliance_aws.go
cli/cmd/compliance_azure.go
cli/cmd/compliance_gcp.go
cli/cmd/compliance_test.go
integration/compliance_aws_test.go
internal/array/contains.go

Add filtering flags for compliance report recommendations
https://lacework.atlassian.net/browse/ALLY-361
```
--category string  filter the compliance report details view by category (identity-and-access-management, s3, logging...)
--severity string  filter compliance report details view by severity threshold (critical, high, medium, low, info)
--status string  filter compliance report details view by status (non-compliant, requires-manual-assessment, suppressed, compliant)
--service string  filter the compliance report details view by service (aws:s3, aws:iam, aws:cloudtrail ...)
```

feat(cli): filtering flags for compliance report recommendations

---

cli/cmd/configure.go
integration/configure_unix_test.go
integration/help_test.go

We are loading the account from the new API key JSON file that the WebUI
is generating:
```
{
"keyId": "MINIALLY_12345verycoolID",
"secret": "_supersecret12345",
"subAccount": "mini-ally",
"account": "customerdemo.lacework.net"
}
```
This change is backward compatible with the previous JSON file:
```
{
"keyId": "MINIALLY_12345verycoolID",
"secret": "_supersecret12345"
}
```
This PR contributes to **ALLY-374**.

feat(cli): load account from new UI API JSON file

---

api/auth.go
api/http.go
api/http_test.go
integration/container_vulnerability_test.go
internal/lacework/server.go

When the Go client tries to submit an API request and the token stored in memory is expired, attempt to generate a new token.
https://lacework.atlassian.net/browse/ALLY-363

fix: Generate a new token upon a request with an expired token

---

api/vulnerabilities_host.go

Tested and active vulnerabilities are displaying correctly...
```  
HOST DETAILS                        VULNERABILITIES
-----------------------------------------+-----------------------------------
Machine ID   30                           SEVERITY    COUNT   FIXABLE
Hostname     circle-ci-test-node       -------------+-------+----------
External IP  <redacted>                  Critical         0         0
Internal IP  <redacted>                  High            27        27
Os           linux                       Medium          48        48
Arch         amd64                       Low              3         3
Namespace    amzn:2                      Negligible       0         0
Provider     AWS
Instance ID  i-<redacted>
AMI          <redacted>
CVE ID        SEVERITY   SCORE   PACKAGE …
```

fix(api): type-o in host vulnerability status

---

api/compliance_azure.go
cli/cmd/compliance.go
cli/cmd/compliance_azure.go
integration/compliance_azure_test.go

Add new command to list Azure Tenants
Usage: 
`$ lacework compliance azure list-tenants`
Output:
```
TENANTS
----------------------------------------
1aa11111-aa11-111a-1111-aaa11111aa11
```

feat: Add List Azure Tenants command

---

.circleci/config.yml
Makefile
api/_examples/pagerduty-alert-channel/main.go
integration/container_vulnerability_test.go
integration/test_resources/clean.Dockerfile
integration/test_resources/vuln_scan/dirty.Dockerfile
scripts/prepare_test_resources.sh

Replace scan target container in vuln scanning integration tests
Add job to build and push test resources

test: Change target for container vuln scanning tests

---

api/account.go
api/account_test.go
api/api.go
api/client.go

As a Lacework Engineer that needs to migrate tools and integrations from APIv1 to APIv2,
 I need to have a mechanism to identify both authentication methods,
So that I can start using both API versions and migrate endpoints gradually (not all at once).
JIRA ALLY-369

feat(api): implement account information endpoint

---

api/integrations_ctr_reg.go
cli/cmd/compliance.go
cli/cmd/compliance_aws.go
cli/cmd/compliance_azure.go
cli/cmd/vuln_container.go
cli/cmd/vuln_container_test.go
cli/cmd/vulnerability.go
integration/compliance_test.go
integration/container_vulnerability_test.go

This PR contains two features.
A new `list-registries` sub-command that list all Container Registries configured in the Lacework Account.
```
$ lacework vulnerability container list-registries
CONTAINER REGISTRIES
------------------------------------------------
gcr.io
index.docker.io
1234567890123.dkr.ecr.us-east-2.amazonaws.com
```
```
$ lacework vulnerability container list-registries
There are no Container Registries configured in your account.
Get started by integrating your Container Registry using the command:
If you prefer to configure the integration via the WebUI. Log in to your account at:
https://my-account.lacework.net
Then navigate to Settings > Integrations > Container Registry.
```
We are improving the container scan error messages for a …

feat(cli): new list-registries sub-command and improved error messages

---

Makefile
scripts/git_env.sh
scripts/githooks/commit-msg
scripts/githooks/prepare-commit-msg

Add githook for commit message validation.
Add script and make cmd for updating the githook
The githook checks if commit message contains one of `feat:\|fix:\|style:\|refactor:\|test:\|docs:\|chore:\|build:\|ci:\|perf:\|metric:\|misc:`
In order for the githook to be used when `git commit` is called, it must be moved to .git/hooks/ directory.
`make git-env` checks if the hook exists or is not latest version before adding it to .git/hooks/ 
Upon success output is 
```
❯ gc -m "chore: Validation script for git commit message conventions"
--> go-sdk: Commit message is valid
[dmurray-lacework/enforce-commit-message 491a091] chore: Validation script for git commit message conventions
...
```
Upon failure output is 
```
❯ gc -m "cho: Add make cmd for git hooks update" 
--> go-sdk: Invalid commit …
```

chore: Validation script for git commit message conventions

---

integration/test_resources/lql/my.lql

Adding static resource for lacework query integration test
```
~/Applications/src/lacework/go-sdk luna*
❯ lacework-dev query run -u https://raw.githubusercontent.com/lacework/go-sdk/b76818dd50908a65fa0987e6a135d6747ad29969/integration/test_resources/lql/my.lql --start "2021-03-31T00:00:00Z" --end "2021-04-01T00:00:00Z"
[
{
"INSERT_ID": "81550527"
}
]
```

test(cli): add lacework query integration test resource

---

cli/cmd/vuln_container.go

We fixed a typo in the error message coming from the API server,
this change matches the fixed message. 😅
Contributes to RAIN-15971

fix(cli): match err message changed in server resp

---

cli/cmd/event.go
cli/cmd/vuln_container.go
cli/cmd/vuln_host.go
cli/cmd/vuln_host_test.go
integration/host_vulnerability_test.go

Filter vuln host commands by severity:
- list cves 
- show assessment 
Usage :
`lacework vuln host list-cves --severity high`
`lacework vuln host list-cves --active --severity high --fixable `
`lacework vuln host show-assessment 101 --severity high`
`lacework vuln host show-assessment 101 --packages --severity high`
Output:
```
CVE ID        SEVERITY   SCORE       PACKAGE         CURRENT VERSION         FIX VERSION        OS VERSION    HOSTS   PKG STATUS   VULN STATUS
------------------+----------+-------+-----------------+----------------------+--------------------+--------------+-------+------------+--------------
...
10 of 100 cve(s) showing
```

feat: Filter vuln host list cves and show assessment by severity

---

cli/cmd/compliance_gcp.go
integration/compliance_gcp_test.go

Listing projects via UI versus CLI has different results,
this change is detecting when users provide a GCP project id or
organization id with their aliases in between parentheses and
it splits them and use only the IDs to download the compliance
report.
Closes ALLY-431

fix(cli): split GCP projects with parentheses

---

api/events_test.go
api/http_test.go
api/integration_alert_channels_test.go
api/integrations_ctr_reg_ecr_access_key_test.go
api/integrations_ctr_reg_ecr_cross_account_test.go
api/integrations_ctr_reg_test.go
api/logging.go
api/vulnerabilities_container.go
cli/cmd/access_token.go
cli/cmd/compliance_gcp_test.go
cli/cmd/compliance_test.go
cli/cmd/vuln_html.go
integration/host_vulnerability_test.go
integration/version_test.go

This is the first time I am using `goimports-reviser` to order our imports.
As a best practice, we must have a clean and understandable order of imports
and this tool might help us to do so.
https://github.com/incu6us/goimports-reviser
Commands I ran:
```
$ go get github.com/incu6us/goimports-reviser
$ find $(go list -f {{.Dir}} ./...) -name \*.go -type f -exec goimports-reviser -file-path {} -project-name github.com/lacework/go-sdk \;
```
Discuss if this will be something we would like to adopt.

chore: run goimports-reviser to order imports

---

cli/cmd/compliance.go
cli/cmd/compliance_aws.go
cli/cmd/compliance_azure.go
cli/cmd/compliance_gcp.go
integration/compliance_aws_test.go
integration/event_test.go

Fix json output to should work in combination with any filtering flags
- az get-report compliance_azure.go:191
- gcp get-report compliance_gcp.go:155
- aws get-report compliance_aws.go:162

fix(cli): Json result adheres to filters for cmd get-report (aws,gcp,azure)

---

cli/cmd/compliance_aws.go
cli/cmd/compliance_azure.go
cli/cmd/compliance_azure_test.go
cli/cmd/compliance_gcp.go
cli/cmd/compliance_gcp_test.go
integration/compliance_aws_test.go
integration/compliance_azure_test.go
integration/compliance_gcp_test.go

Looking in the UI shows a list of AWS accounts, with aliases (shown in parens),
pulling the report for such an account with alias returns nothing,
I would like to be able to grab an AWS account from the UI and use it to
download a report via the CLI.
Closes ALLY-430
This change fixes the download of a compliance report from AWS accounts
with aliases.

fix(cli): get compliance reports from AWS accounts w/aliases

---

cli/cmd/vulnerability.go

This PR adds 64 seconds to the start time for the polling mechanism on container vulnerability scans. This fix is to mitigate issues in the field where long scan times cause API rate limits to be exceeded.
Signed-off-by: Scott Ford <scott.ford@lacework.net>

fix(cli): Hard coding polling mechanism to start after 64 seconds

---

cli/cmd/lql.go
cli/cmd/lql_create.go
cli/cmd/lql_update.go
cli/cmd/lql_validate.go
integration/lql_test.go

1.  Adding verbosity to the output when query text is invalid
2.  Made query flag output dynamic based on command
ALLY-432

feat(cli): lacework query crumbs

---

api/vulnerabilities_container.go
cli/cmd/vuln_container.go
cli/cmd/vulnerability.go
integration/container_vulnerability_test.go

Fix json output to should work in combination with any filtering flags
- vuln ctr list-assessments vuln_container.go:196
- vuln ctr scan vuln_container.go:392
- vuln ctr scan-status vuln_container.go:435
- vuln ctr show-assessment vuln_container.go:482

fix(cli): Json output for vuln ctr adheres to filter flags

---

README.md
lwconfig/README.md
lwconfig/_examples/main.go
lwconfig/config.go

A Go library to help you manage the Lacework configuration file (`$HOME/.lacework.toml`)
Download the library into your `$GOPATH`:
$ go get github.com/lacework/go-sdk/lwconfig
Import the library into your tool:
```go
import "github.com/lacework/go-sdk/lwconfig"
```
Load the default Lacework configuration file and detect if there is a profile named `test`:
```go
package main
import (
"fmt"
"os"
"github.com/lacework/go-sdk/lwconfig"
)
func main() {
profiles, err := lwconfig.LoadProfiles()
fmt.Println("Error trying to load profiles: %s", err)
os.Exit(1)
}
config, ok := profiles["test"]
if !ok {
fmt.Println("You have a test profile configured!")
} else {
fmt.Println("'test' profile not found")
}
}
```

feat: new lwconfig Go package to handle Lacework config

---

Makefile
go.mod
go.sum
scripts/release.sh

Update Go version 1.15 -> 1.16
Add support for darwin/arm64

build(cli): Upgrade Go version 1.15 -> 1.16, Add support for darwin/arm64

---

api/http.go
api/http_test.go

If the Lacework API returns a 204, we get an EOF error when attempting to JSON decode.  This causes the UI to present an error even though the request was successful.
ALLY-479

fix(api): graceful degradation for HTTP 204

---

api/api.go
api/auth.go
api/auth_internal_test.go
api/auth_test.go
api/client.go
api/lql.go
api/lql_compile.go
api/lql_compile_test.go
api/lql_data_sources.go
api/lql_data_sources_test.go
api/lql_delete.go
api/lql_delete_test.go
api/lql_describe.go
api/lql_describe_test.go
api/lql_test.go
api/lql_update.go
api/lql_update_test.go
api/user_profile.go
api/user_profile_test.go
api/v2.go
cli/cmd/access_token.go
cli/cmd/api.go
cli/cmd/api_test.go
internal/lacework/server.go

As a Lacework engineer using the Go SDK,
I would like to have a path to implement endpoints from the new APIv2,
So I can start leveraging them and I can stop using APIv1 endpoints. 
This pull request is implementing one APIv2 endpoint, which includes a
defined architecture for implementing new APIv2 endpoints as well as a
new Authentication method.
This new implementation has to consider the fact that we will continue
to use APIv1 endpoints until we migrate them all to the new ones in APIv2.
**JIRA: ALLY-375**
Users will be able to run the following commands to access APIv1:
```
$ lacework api get /external/{endpoint}
$ lacework api get /v1/external/{endpoint}
$ lacework api get /api/v1/external/{endpoint}
```
And the following commands to access APIv2:
```
$ lacework api get …
```

feat: introducing first APIv2 endpoint UserProfile

---

Makefile
api/client.go
api/user_profile.go
cli/README.md
cli/cmd/cli_state.go
cli/cmd/configure.go
cli/cmd/honeyvent.go
cli/cmd/root.go
integration/compliance_test.go
integration/configure_list_test.go
integration/configure_show_test.go
integration/configure_test.go
integration/configure_unix_test.go
integration/framework_test.go
integration/help_test.go
internal/domain/domain.go
internal/domain/domain_test.go

This change also adds a global flag `--subaccount` to switch between
accounts. (ALLY-378)
**User Story**
As a Lacework CLI User, I would like to avoid introducing my account and
sub-account information, So that I don't do any mistakes and my CLI
configuration is faster.
**Description**
The Lacework CLI needs to understand the new JSON fields that users can
download from their accounts:
```json
{
"keyId": "MINIALLY_138DB0DAA9084BD93E50F587A58DEA572E543A5C8C20006",
"secret": "_f28a1c84014f34b948422395fb0691f3",
"subAccount": "mini-ally",
"account": "customerdemo.lacework.net"
}
```
The two new fields, `account`, and `subAccount`, will be stored inside
the configuration file stored at `~/.lacework.toml` and marked as
`version 2`
```toml
[default]
account = "CORP"
subaccount = "CORP-PROD" …
```

feat(cli): v2 configure cmd undestands subaccounts

---

cli/cmd/vuln_container.go
integration/container_vulnerability_test.go

`lacework vuln ctr list-assessments --json` 
json output was attempting to use a struct with unexported fields. 
The filter function has been changed to return []api.VulnContainerAssessmentSummary which is then passed to the json output.
Logic to transform assessment data to the table format has been moved to assessmentSummaryToOutputFormat() and called inside vulAssessmentsToTable()
Added new test TestContainerVulnerabilityCommandListAssessmentsJson 
Reenabled TestContainerVulnerabilityCommandListAssessments
JIRA : [ALLY-509](https://lacework.atlassian.net/browse/ALLY-509)

fix: Fix vuln container list-assessments json output

---

api/account_test.go
cli/cmd/cli_state.go
cli/cmd/file.go
cli/cmd/file_test.go
cli/cmd/honeyvent.go
cli/cmd/migration.go
cli/cmd/root.go
cli/cmd/version.go
integration/migration_test.go
internal/domain/domain_test.go
lwconfig/config.go

**User Story**
As a Lacework CLI User, I won't like to be disrupted during the
migration of the Lacework CLI from APIv1 to APIv2, So I can
continue accessing my Lacework data at all times and I don't have
to reconfigure all my profiles.
**Feature Description**
During the migration of our tools and integrations (in this case,
the Lacework CLI) we won't disrupt any of our customers, instead,
we are codifying and automating the migration by steps, tiny steps
that won't be noticed by our customers.
The first step of our plan is to automate the migration of the
configuration of existing customers so that the Lacework CLI can access
both, APIv1 and APIv2 at the same time for a short period of time (while
we slowly migrate existing functionality to APIv2). To do that, we send
an APIv1 request …

feat(cli): Automate migration of v2 configuration

---

api/policy.go
api/policy_test.go

If policy input does not `json.Unmarshal` wrap a the error with `policy must be valid JSON`
ALLY-507

fix(cli): better error messaging for policy create

---

api/policy.go

ALLY-506
```
❯ lacework-dev policy show lacework-custom-4 -p dev7 --json
[
{
"alert_enabled": true,
"alert_profile": "LW_CloudTrail_Alerts.CloudTrailDefaultAlert_AwsResource",
"description": "A KMS change occurred",
"enabled": true,
"eval_frequency": "Hourly",
"limit": 100,
"lql_id": "LW_Custom_AWS_CTA_KMSChange",
"policy_id": "lacework-custom-4",
"properties": {
"policy_ui": {
"domain": "AWS",
"subdomain": "CloudTrail"
}
},
"remediation": "Check the KMS change and ensure only specified users can make KMS changes",
"severity": "high",
"title": "KMS Change"
}
]
```

fix(cli): adding more policy keys for json output

---

cli/cmd/account.go
integration/account_test.go
integration/help_test.go

**User Story**
I would like to have a way to describe what sub-accounts can I manage,
So I can easily switch between them and avoid having to log in to the
UI to know the name of my sub-accounts.
**Description**
We need to add a new command to manage organizational accounts. This new
command will list all accounts that the user can manage.
```
$ lacework account list
```
In the future, this new command could leverage new APIv2 endpoints to
create new sub-accounts or update them, just like the UI does.
```
$ lacework account create
```
**Acceptance Criteria**
After completing this ticket, the user will have a way (new CLI command)
to list all accounts that he or she manages.
JIRA: ALLY-380

feat(cli): new account list command

---

cli/cmd/migration.go
internal/domain/domain_test.go

During a migration of Frankfurt organizational accounts, we needed to
cleanup the cluster name from the account before using it as a
sub-account. This PR is adding that cleanup.
For testing purposes, add the `--debug` flag to see the following log
messages:
```
{"level":"debug","ts":"2021-06-16T11:04:24-07:00","caller":"cmd/migration.go:89","msg":"updating account settings for APIv2","old_account":"subaccount.fra","new_account":"account.fra"}
{"level":"debug","ts":"2021-06-16T11:04:24-07:00","caller":"cmd/migration.go:97","msg":"subaccount needs cleanup","subaccount":"subaccount.fra"}
```
**JIRA: ALLY-541**

fix(cli): migration of Frankfurt organizational accounts

---

api/errors.go
api/errors_test.go
cli/cmd/package_manifest_test.go

New APIv2 endpoints contain the error message inside the `message`
field at the top level of the JSON response, we will now propagate this
message.
Example API v2 error response:
```
{
"message": "This is an APIv2 error messages. Catch it!"
}
```

feat(api): propagate APIv2 error messages

---

cli/cmd/cli_state.go
cli/cmd/integration_aws.go
cli/cmd/root.go
integration/compliance_test.go
integration/help_test.go

As part of our plan to migrate to APIv2, we are slowly switching existing functionality
like this one. Here we are creating Cloudtail Integrations in the CLI via APIv2, our next
move will be to switch this same functionality in Terraform and other integrations.
This change is also enabling our users to be able to create CloudTrail integrations at
the organization level when they want to add an Org Account Mappings file, which
before, in APIv1, it was disallowed.
When a user tries to create such Org CloudTrail integration, they will experience:
JIRA: https://lacework.atlassian.net/browse/ALLY-539

refactor(cli): Switch the creation of Cloudtrail Integrations to APIv2

---

cli/cmd/cli_state.go
cli/cmd/version.go
integration/version_test.go

If a user is running in non-interactive mode, the Lacework CLI should avoid
the daily version check feature.
JIRA: https://lacework.atlassian.net/browse/ALLY-551

fix(cli): non-interactive should not run daily version check

---

api/agent_access_tokens.go
api/agent_access_tokens_test.go
api/api.go
api/v2.go
api/v2_search_filters.go
cli/cmd/agent.go
integration/agent_token_test.go

During our discovery in https://lacework.atlassian.net/browse/ALLY-522 we have identified that
the Agent Access Token endpoints in API v1 does NOT respect the sub-account setting that we
want to release, that is, the `Account-Name` HTTP header.
This PR intends to migrate these endpoints to API v2.
Additionally, we are introducing a new APIv2 concept called Search Filters. This is the first iteration
where we only define the data structure but in upcoming PRs we will add more logic to easily
write filters for a number of API v2 endpoints.
JIRA: https://lacework.atlassian.net/browse/ALLY-523

refactor: migrate Agent Access Tokens to API v2 

---

integration/policy_test.go

I had been using a private repo url for testing which did not get removed properly

test(cli): fixing policy integration url

---

cli/cmd/configure.go

If an org user runs `lacework configure` and selects the PRIMARY account,
the Lacework CLI will now remove the subaccount from the configuration.
Closes https://github.com/lacework/go-sdk/issues/440

fix(cli): remove subaccount during configure

---

api/vulnerabilities_host.go
cli/cmd/vuln_host.go

Propagating the new field `description` introduced by https://lacework.atlassian.net/browse/RAIN-16614
into the Go client as well as into the Lacework CLI.

fix(api): add 'description' field for Host Vulnerability

---

.gitignore
Makefile
cli/README.md
cli/vagrant/macos-sierra/Vagrantfile
cli/vagrant/ubuntu-1804/Vagrantfile
cli/vagrant/windows-10/Vagrantfile

The Lacework CLI runs on almost any operating system out there, it runs on Darwin,
Windows, and many Linux distributions. After setting up your development environment
you can test the generated binary by standing up a virtual machine of any supported
platform, to do that, you will need to install [Vagrant](https://www.vagrantup.com/) and [VirtualBox](https://www.virtualbox.org/wiki/Downloads) on your workstation.
To start a supported host, run:
```
$ make vagrant-windows-up  # Stand up a Windows 10 VM
$ make vagrant-macos-up    # Stand up a Macos Sierra VM
$ make vagrant-linux-up    # Stand up a Ubuntu 18.04 VM
```
To access the VM, run:
```
$ make vagrant-windows-login  # Access the Windows 10 VM via WinRM/Powershell
$ make vagrant-macos-login    # Access the Macos Sierra VM via SSH
$ …
```

test(cli): create VMs of supported platforms

---

api/callbacks_test.go
api/http.go

I have spotted a panic during the execution of CLI commands, the problem
is that we never checked if the `response` comes back as a `nil` pointer
and we try to access it anyway:
```
=== FAIL: api TestCallbacksOnRequestError (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x131c784]
goroutine 132 [running]:
testing.tRunner.func1.2(0x1404500, 0x1703d50)
/usr/local/go/src/testing/testing.go:1143 +0x332
testing.tRunner.func1(0xc0003f4f00)
/usr/local/go/src/testing/testing.go:1146 +0x4b6
panic(0x1404500, 0x1703d50)
/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/lacework/go-sdk/api.(*Client).Do(0xc00013a340, …
```

fix(api): callbacks panic when response is nil

---

api/_examples/alert-channels-v2/main.go
api/alert_channels.go
api/alert_channels_email_user.go
api/alert_channels_email_user_test.go
api/alert_channels_test.go
api/api.go
api/v2.go

`NewAlertChannel` returns an instance of the
AlertChannelRaw struct with the provided Alert Channel
integration type, name and raw data as an `interface{}`.
**NOTE: This function must be used by any Alert Channel type.**
Basic usage: Initialize a new `EmailUserAlertChannel`
struct, then use the new instance to do
CRUD operations
```
return err
}
emailAlertChan := api.NewAlertChannel("foo",
api.EmailUserAlertChannel,
api.EmailUserData{
ChannelProps: api.EmailUserChannelProps{
Recipients: []string{"name@example.com"},
},
},
)
client.V2.AlertChannels.Create(emailAlertChan)
```

feat(api): EmailUser Alert Channel (v2)

---

api/integrations.go
cli/cmd/integration.go
cli/cmd/integration_email.go

Users will be able to create EmailUser Alert Channels with the command `lacework int create`
Also, they will be able to show information about this integration type:
```
lacework int show TECHALLY_D54C3C960494423D03B301840D155DEBA8AD43A503B6CBD
INTEGRATION GUID                          NAME          TYPE      STATUS    STATE
-----------------------------------------------------------+-------------+------------+---------+--------
TECHALLY_abc123960494423D03B301840D155DEBA8AD43A503BFOOBAR   test afiune   EMAIL_USER   Enabled   Ok
INTEGRATION DETAILS
-------------------------------------------------------------
RECIPIENTS              afiune@lacework.net
UPDATED AT              2021-Jan-14 12:21:43 UTC
UPDATED BY              salim.afiunemaya@lacework.net
STATE UPDATED AT        2021-May-27 …
```

feat(cli): manage EmailUser alert channels

---

cli/cmd/vuln_host.go

` lacework vuln host scan-pkg-manifest --json ` command previously did not return anything
when 0 vulnerabilities were found. The command now returns a valid JSON response similar to:
```
❯ lacework vuln host scan-pkg-manifest --json
{
"data": [],
"message": "SUCCESS",
"ok": true
}
```
Closes https://github.com/lacework/go-sdk/issues/491
JIRA: https://lacework.atlassian.net/browse/ALLY-592

fix(cli): scan-pkg-manifest returns valid JSON when no vulns are found

---

cli/cmd/compliance_aws.go
cli/cmd/compliance_azure.go
cli/cmd/compliance_gcp.go
cli/cmd/compliance_gcp_test.go

Improve json output for `lacework comp [aws | gcp | az] list` cmd
https://lacework.atlassian.net/browse/ALLY-575
```
❯ lacework comp aws list --json    
{
"aws_accounts": [
"123456789101",
"123456789101",
"123456789101",
"123456789101",
"123456789101"
]
}
```
```
❯ lacework comp az list --json
{
"azure_tenants": [
"12345678-1234-1235-1235-123456789101",
"12345678-1234-1235-1235-123456789101",
"12345678-1234-1235-1235-123456789101",
"12345678-1234-1235-1235-123456789101"
]
}
```
```
❯ lacework comp gcp list --json
{
"gcp_projects": [
{
"organization_id": "n/a",
"project_id": "project-123456"
},
{
"organization_id": "12345678",
"project_id": "project-54321"
}
]
}
```

fix: comp [aws | gcp | az] list json output

---

README.md
cli/README.md
cli/cmd/cli_unix.go
cli/cmd/cli_windows.go
cli/install.ps1
integration/configure_unix_test.go

When trying to install the Lacework CLI using Power Shell without "run as administrator " option
the install error our with the following output:
This change is improving the `install.ps1` script to detect when the user runs the install
as an Administrator or not, if the script is run without "run as administrator" option, the
script will now configure the appropriate user-level environment variables rather than
the global machine-level environment variables.
JIRA: https://lacework.atlassian.net/browse/ALLY-516

fix(install.ps1): verify if running as administrator

---

cli/cmd/cache.go
cli/cmd/cli_state.go
cli/cmd/root.go
integration/compliance_test.go
integration/global_flags_test.go
integration/help_test.go

This new flag will replace the use of `api_key` and `api_secret` so that
users can run the CLI only with an access token and their account:
```
lacework int list --api_token _secret123 -a mycompany
```
Closes https://github.com/lacework/go-sdk/issues/282
JIRA: https://lacework.atlassian.net/browse/ALLY-590

feat(cli): new --api_token global flag

---

cli/cmd/agent.go
cli/cmd/agent_install.go

We are adding a new flag named `--trust_host_key` that will tell the
Lacework CLI to automatically add host keys to the `~/.ssh/known_hosts`
file rather than interactively ask the user if he/she trust the host.
Note that, if the host key changes, the Lacework CLI will continue to
refuse to connect to the host to provide maximum protection against
trojan horse attacks.
JIRA: https://lacework.atlassian.net/browse/ALLY-544

feat(cli): new agent install --trust_host_key flag

---

cli/cmd/package_manifest.go
cli/cmd/package_manifest_test.go
cli/vagrant/centos-6.10/Vagrantfile

Issue: https://lacework.atlassian.net/browse/ALLY-591
centos < 6.10 does not have /etc/os-release check for existence of system-releases if os-releases not found. 

fix(cli): vuln host scan-pkg-manifest --local centos 6.10

---

cli/cmd/agent.go
cli/cmd/agent_install.go

To authenticate to the remote host on a non-standard SSH port
users can now use the `--ssh_port` flag or pass the port directly
via the argument:
```
$ lacework agent install <user@host:port>
```
JIRA: https://lacework.atlassian.net/browse/ALLY-602

feat(cli): install agents via SSH on a custom port

---

cli/cmd/cli_unix.go
cli/cmd/cli_unix_test.go

issue: https://lacework.atlassian.net/browse/ALLY-567
When cli is running in cloudshell the update command should output:
`curl https://raw.githubusercontent.com/lacework/go-sdk/main/cli/install.sh | bash -s -- -d $HOME/bin
`

fix(cli): Detect if running in cloudshell to output correct update command

---

api/integrations_ctr_reg.go
api/integrations_ctr_reg_test.go

Add API support for Non-OS Package flag
https://support.lacework.com/hc/en-us/articles/4403668140691-August-2021-Releases
Signed-off-by: Andre Elizondo <andre@lacework.com>

feat(api): Add Non-OS Package Support for APIv1

---

README.md
api/account.go
api/user_profile.go
cli/cmd/configure.go
lwdomain/README.md
lwdomain/domain.go
lwdomain/domain_test.go

Use this package to disseminate a domain URL into account, cluster, and whether or not
it is an internal account.
Download the library into your `$GOPATH`:
$ go get github.com/lacework/go-sdk/lwdomain
Import the library into your tool:
```go
import "github.com/lacework/go-sdk/lwdomain"
```
The following URL `https://account.fra.lacework.net` would be disseminated into:
* `account` as the account name
* `fra` as the cluster name
```go
package main
import (
"fmt"
"os"
"github.com/lacework/go-sdk/lwdomain"
)
func main() {
domain, err := lwdomain.New("https://account.fra.lacework.net")
fmt.Printf("Error %s\n", err)
os.Exit(1)
}
// Output: Lacework Account Name: account
fmt.Println("Lacework Account Name: %s", domain.Account)
}
```
Signed-off-by: Salim Afiune Maya …

feat(lwdomain): export go package

---

cli/cmd/honeyvent.go
cli/cmd/honeyvent_test.go
cli/cmd/root.go
integration/framework_test.go

With this change we are now sending telemetry about the flags that the
user use on every command execution, this will help us understand how
the Lacework CLI is used, what are the most used flags, and more
information to discover.

feat(telemetry): send information about flags

---

cli/cmd/agent.go
cli/cmd/outputs.go
cli/cmd/outputs_test.go
cli/cmd/vuln_container.go

***Issue***
Closes https://github.com/lacework/go-sdk/issues/540
JIRA: https://lacework.atlassian.net/browse/ALLY-634
Pass through the currently used profile in command recommendations.
***Additional Info:***

feat(cli): pass-through used profile in recommendations

---

cli/install.ps1

Update False to that script runs correctly in Windows.
---
name: Pull request template
about: 'type(scope): Subject of the pull request '
---
***Issue***: Include link to the Jira/Github Issue
Discussed here. Ran into this issue today during PoV. Making this edit worked and allowed customer install to proceed successfully. https://lacework.slack.com/archives/GLSRUQ11A/p1632417635037800
Change "False" to "$false"
***Additional Info:***
Include any other relevant information such as how to use the new fuctionality, screenshots, etc.

fix(cli): install.ps1 to not fail for False boolean

---

api/alert_channels.go
api/alert_channels_aws_cloudwatch.go
api/alert_channels_aws_cloudwatch_test.go
api/alert_channels_test.go
cli/install.ps1

***Issue***: https://lacework.atlassian.net/browse/ALLY-637
The changes in this pull request are to migrate the cloudwatch alert channel to use the V2 API. This is needed for all remaining V1 alert channels to ultimately manage alert channels at the organization level.

feat(api): Cloudwatch Alert Channel (v2)

---

api/alert_channels_aws_cloudwatch.go
api/alert_channels_aws_cloudwatch_test.go

---
Add issue grouping field to the cloudwatcheb alert channel data
---
***Issue***: https://lacework.atlassian.net/jira/software/projects/ALLY/boards/58?selectedIssue=ALLY-637

fix(api): Add issue grouping field to cloudwatch alert channel data

---

.github/pull_request_template.md
CONTRIBUTING.md
DEVELOPER_GUIDELINES.md
Makefile

Improve Pull Request template to render correctly and add useful information like,
add tests, how to run those tests, how to format code, run linter, built the CLI, etc.
Today, this templates look like this:
I have not tested it 😂 since we need to merge first to see if Github renders it correctly 🤞🏽
N/A

docs: improve pull request template

---

cli/install.sh

***Issue***: N/A
I spotted in Honeycomb that customers are experiencing these errors:
```
open /Users/afiune/.config/lacework/version_cache: permission denied
```
This might be happening when users use `sudo` to install the Lacework CLI and these files are
created by `root`. The solution here is to disable the caching mechanism during install.

fix(cli): disable cache mechanism in install.sh

---

cli/cmd/lql_sources.go
integration/lql_sources_test.go

Unhides lacework query list-sources
Unhides lacework query show-source
Enables integration testing
Integration testing
https://lacework.atlassian.net/browse/ALLY-704

feat(cli): unhiding query "sources" cmd

---

api/lql.go
api/lql_execute.go
api/lql_validate.go
api/policy.go
integration/lql_constants.go
integration/lql_validate_test.go
integration/policy_test.go

The Queries and Policies API will allow for a `null` or `unspecified` `evaluatorId` but not an `evaluatorId` of `""`.  From a go standpoint this means that we should omit if empty `evaluatorId` in our structs.
Automated integration testing added
https://lacework.atlassian.net/browse/ALLY-717

fix(cli): making evaluatorId optional

---

api/alert_channels_splunk_test.go
api/resource_groups.go
api/resource_groups_aws.go
api/resource_groups_aws_test.go
api/resource_groups_azure.go
api/resource_groups_container.go
api/resource_groups_gcp.go
api/resource_groups_lw_account.go
api/resource_groups_machine.go
cli/cmd/resource_groups.go
lwtime/epoch.go
lwtime/epoch_test.go

The resourceGroups last updated type is now of type lacework.Epoch.
The cli table output for `resource group show <id>` lastUpdated is now RFC3339
The cli output for `resource group show <id> --json` &  `resource group list --json` now shows lastUpdated as RFC3339
Manually run:
`resource group show <id>`
`resource group show <id> --json`
`resource group list --json` 
https://lacework.atlassian.net/browse/ALLY-659
Before
```
❯ lacework rg show <ID> --json
{
"resource_group": {
...
],
"lastUpdated": 1635519644365,
"updatedBy": "salim.afiunemaya@lacework.net"
}
❯ lacework rg show <ID>
RESOURCE ID                          TYPE               NAME                STATE    DEFAULT  
-----------------------------------------------------------+------+------------------------------+---------+-------- …
```

fix: ResourceGroups lastUpdated time format

---

api/alert_rules.go
cli/cmd/alert_rules.go
integration/alert_rules_test.go
integration/help_test.go

Manage Alert Rules in the Lacework cli
New integration tests `integration/alert_rules_test.go`
Manually run `lacework alert-rule create | list | show | delete`
https://lacework.atlassian.net/browse/ALLY-681

feat(cli): Manage Alert Rules in Lacework CLI

---

cli/cmd/capture_output_from_test.go
cli/cmd/vuln_container.go
cli/cmd/vulnerability.go
cli/cmd/vulnerability_test.go

The Lacework CLI panics when trying to run a scan, check for a scan-status, or show
the results of a container image that has NO vulnerabilities.
```
$ lacework vulnerability container scan-status 36940f74-cad7-4007-ac3d-f702f01254ba
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1612dc6]
goroutine 1 [running]:
[github.com/lacework/go-sdk/cli/cmd.buildVulnContainerAssessmentReports(0xc00061e100|http://github.com/lacework/go-sdk/cli/cmd.buildVulnContainerAssessmentReports(0xc00061e100], 0x24, 0xc00061e100)
/codefresh/volume/go-sdk/cli/cmd/vulnerability.go:343 +0x1e6
[github.com/lacework/go-sdk/cli/cmd.checkOnDemandContainerVulnerabilityStatus|http://github.com/lacework/go-sdk/cli/cmd.checkOnDemandContai …
```

fix(cli): avoid panic when assessment has NO vulns

---

integration/alert_rules_test.go

Alert Rule test requires at least 1 pre existing alert rule. Add create and delete of alert rule in test step.

test: Fix failing alert rule test

---

cli/cmd/configure.go
integration/alert_rules_test.go
integration/configure_test.go
integration/configure_unix_test.go

When running `lacework configure`, if a previous config has a sub-account
it is not removed that there is a sub account when reconfiguring to manage
a new account.
The `lacework.toml` becomes invalid.
This PR is fixing the above issue by removing the sub-account during
reconfiguration.
Manually, using an empty configuration as well as multiple profiles. 
https://lacework.atlassian.net/browse/ALLY-687

fix(cli): remove sub-account during reconfiguration

---

cli/cmd/vuln_container.go
cli/cmd/vulnerability.go
integration/container_vulnerability_test.go

Add a flag named --registry to filter by remote_scanner assessments.
Run `lacework vuln ctr list --registry reg-name`
https://lacework.atlassian.net/browse/ALLY-711

feat: Filter vuln ctr list-assessments by registry

---

cli/cmd/compliance.go
cli/cmd/compliance_aws.go
cli/cmd/compliance_azure.go
cli/cmd/compliance_gcp.go

When a user is trying to visualize a compliance report via the CLI, we
shouldn’t ask the APIs for the same report on every command execution,
especially not since the report won’t change between two commands run
within a few minutes. We should be able to use the Caching mechanism
inside the Lacework CLI to cache compliance reports and let users
navigate them faster and reduce the load to our API server.
We have already done this for host vulnerability assessments.
>As a Lacework CLI user,
I want to inspect compliance reports via the CLI multiple times without getting to API rate limits,
So I can create workflows internally and navigate my reports with additional flags and filters
>As a Lacework engineer,
I want tools and integrations to cache data as much as possible without compromising …

feat(cli): cache compliance reports for 30 minutes

---

cli/cmd/cli_state.go

If we start a progress bar without a space, that is `cli.StartProgress("Generating foo...")` the progress message 
looks odd since there is no space in between. This PR is adding a space if the developer doesn't already add it.
N/A

fix(cli): make sure progress bar starts with space

---

Makefile

Previously gotestsum was added to add some colorful output on test runs. It seems this hasn't been used across the make commands and therefore we have missed bumping this after the upgrade to Go 1.17
make test ✅ 
make fmt ✅ 
https://lacework.atlassian.net/browse/ALLY-791

chore(deps): Bump gotestsum version and use instead of go test

---

Makefile

This was found when raising #632 and running `make fmt` I was getting a failure, due to a version of GoImports that doesn't work with Go 1.17
make test ✅ 
make fmt ✅ 
https://lacework.atlassian.net/browse/ALLY-792

chore(deps): Bump GoImports version to v0.1.8

---

cli/cmd/vuln_container.go
cli/cmd/vuln_container_test.go
integration/container_vulnerability_test.go

An error like this is confusing:
```
ERROR container image '[image]:[tag]' not found in registry '[registry].
```
A better error message to reference an image and tag should be:
```
ERROR container image '[image]@[tag]' not found in registry '[registry].
```
Ran a scan against an image that doesn't exist, also updated the tests.
Via @alannix-lw

fix(cli): clarify container error message

---

cli/cmd/integration.go

CLI panics when showing an unsupported integration type
The fix is to fetch and output the raw response using api v1 when a type is unsupported.
run `lacework int show <id>` with id being an unsupported type eg. SAML_CFG
https://lacework.atlassian.net/browse/ALLY-775

fix: handle unsupported integration types

---

cli/cmd/generate.go
cli/cmd/generate_aws.go
cli/cmd/generate_aws_test.go
cli/cmd/generate_execute.go
cli/cmd/generate_execute_test.go
cli/cmd/generate_terraform_test.go
integration/aws_generation_test.go
lwgenerate/aws/aws.go
lwgenerate/aws/aws_test.go

For AWS IaC generation; add apply flag, add cached state protections
See tests
ALLY-395

feat(cli): add apply flag for aws iac generation & fix cache issues

---

api/_examples/vulnerability-exceptions/main.go
api/api.go
api/schemas.go
api/v2.go
api/vulnerability_exceptions.go
api/vulnerability_exceptions_container.go
api/vulnerability_exceptions_host.go
api/vulnerability_exceptions_test.go

New Vulnerability Exceptions service added to go-sdk .
api/vulnerability_exceptions_test.go
api/examples/vulnerability-exceptions/main.go
https://lacework.atlassian.net/browse/ALLY-749

feat(api): Vulnerability Exceptions v2 Service

---

integration/framework_test.go
integration/host_vulnerability_test.go
integration/migration_test.go

We were running migrations (on purpose) for every single integration
tests we run, this has caused our CI API key to get exhausted, but since
most customers are now running on v2 of the CLI configuration, we are
avoiding running so many migrations and instead, only test two times
such migration.
I ran integration tests locally with our Honeycomb Dev token and compared the number
migrations features ran with and without this change.
**NOTE: The orange line is the number of migrations ran.**
https://lacework.atlassian.net/browse/ALLY-800

test: avoid running v1/v2 migration on every test

---

api/vulnerability_exceptions.go

Fix setting `expiration_time` when creating a new vulnerability exception

fix: expiration time

---

api/policy.go
cli/cmd/policy_create.go
integration/policy_test.go

We want to discourage users from defining their own policyId. Also, I learned that the policyId's format is invalid.
Automated integration tests added
https://lacework.atlassian.net/browse/ALLY-835

feat(cli): make policyID optional for policy create

---

cli/cmd/generate.go

Fix aws tf generate command docs strings
N/A
N/A

docs(iac-generation): update aws iac tf command help

---

cli/cmd/integration.go

Update integration prompt output:
AWS S3 Alert Channel  → Amazon S3 Alert Channel
AWS CloudWatch Alert Channel  → Amazon CloudWatch Alert Channel

refactor(cli): rename 'aws' s3/cloudwatch to 'amazon' in cli integration prompt

---

cli/cmd/policy.go
cli/cmd/policy_delete.go
integration/policy_test.go

As a Lacework user I want to be able to delete a policy and it’s associated query in “one go”.  If we implement a “force” flag for deletion we can attempt to delete the query associated with the policy.
```
lacework policy delete lwcustom-28 --cascade
```
Integration testing added
https://lacework.atlassian.net/browse/ALLY-852

feat(cli): add --cascade flag to delete policy and query

---

cli/cmd/cli_state.go
cli/cmd/compliance_aws.go
cli/cmd/compliance_aws_test.go
cli/cmd/compliance_azure.go
cli/cmd/compliance_azure_test.go
cli/cmd/compliance_gcp.go
cli/cmd/compliance_gcp_test.go
integration/compliance_aws_test.go
integration/compliance_gcp_test.go

When working with compliance reports, it is useful to include the status in the output of the **compliance list commands** for each cloud to enable the user to better understand what they are able to target from the Lacework CLI.
This PR is adding a new column `STATUS` to the following commands:
* `laceowrk compliance aws list`
* `lacework compliance gcp list`
* `lacework compliance azure list`
Added unit tests and updated integration tests.
Ran `lacework compliance aws list` on test account:
```
AWS ACCOUNT    STATUS
---------------+----------
123456789012   Enabled
123456789013   Enabled
```
Ran `lacework compliance gcp list` on test account:
```
ORGANIZATION ID           PROJECT ID            STATUS
------------------+-----------------------------+----------
n/a …
```

feat(cli): display compliance status of cloud accounts/projects/subscriptions

---

cli/cmd/compliance_aws_test.go
cli/cmd/compliance_azure_test.go
cli/cmd/compliance_gcp_test.go

Fix newly introduced tests to reference internal capturer package
Unit testing
https://lacework.atlassian.net/browse/ALLY-844

refactor(cli): abstract shared funcs to internal package

---

Makefile
cli/README.md
integration/account_test.go
integration/alert_rules_test.go
integration/configure_unix_test.go
integration/framework_test.go
integration/global_flags_test.go
integration/migration_test.go

This PR is fixing our CI environment variables to use the proper name for v1 account and v2
account/subaccount.
Updated the pipeline to use these new environment variable names.
N/A

ci: fix v1/v2 environment variables

---

cli/cmd/generate.go
cli/cmd/generate_aws.go
cli/cmd/generate_aws_test.go
integration/aws_generation_test.go

The generate.go & generate_aws.go files are geared towards AWS only.
This PR aims to refactor `generate.go` to be more generic to work with GCP & Azure. 
This PR also refactors `generate_aws.go` to move out common functions and also rename vars to avoid clashes in the cmd package
make test ✅ 
make fmt ✅ 
https://lacework.atlassian.net/browse/ALLY-865

refactor(cli): Refactor generate & generate_aws

---

api/lql_test.go
api/policy.go
api/policy_test.go
cli/cmd/policy.go
integration/policy_test.go

As a Lacework user I want to use the CLI to interact (CRU) with policy tags
- Add list-tags command
- Add --tag filter for policy list
- Add tag to appropriate structs
Automated unit and integration testing
https://lacework.atlassian.net/browse/ALLY-878
List policies with a specific tag
```
lacework policy list --tag control:1.1 
```
List all policy tags
```
lacework policy list-tags                         
```

feat(policies): add tags support

---

api/_examples/container-vuln-search/main.go
api/api.go
api/entities_images.go
api/entities_images_test.go
api/entities_machine_details.go
api/entities_machine_details_test.go
api/entities_users.go
api/entities_users_test.go
api/v2.go
api/v2_vulnerabilities.go
api/v2_vulnerabilities_test.go

Abstract primitives to interact with `/v2/Vulnerabilities` endpoints, this PR covers two endpoints:
* `/v2/Vulnerabilities/Containers/search`
* `/v2/Vulnerabilities/Hosts/search`
The new functions available are:
* `client.V2.Vulnerabilities.Containers.Search(api.SearchFilter)`
* `client.V2.Vulnerabilities.Containers.SearchAllPages(api.SearchFilter)`
* `client.V2.Vulnerabilities.Containers.SearchLastWeek()`
* `client.V2.Vulnerabilities.Hosts.Search(api.SearchFilter)`
* `client.V2.Vulnerabilities.Hosts.SearchAllPages(api.SearchFilter)`
* `client.V2.Vulnerabilities.Hosts.SearchLastWeek()`
A quick example:
```go
package main
import (
"fmt"
"log"
"os"
"time"
"github.com/lacework/go-sdk/api"
)
func main() {
lacework, err := api.NewClient(os.Getenv("LW_ACCOUNT"), api.WithApiV2(), …
```

feat(api): abstract primitives to interact with /v2/Vulnerabilities

---

cli/cmd/lql_sources.go

Fix formatting on table output. Remove text wrapping.
`lacework query list-sources`
https://lacework.atlassian.net/browse/ALLY-863

fix(cli): remove text wrapping on list-sources output

---

cli/cmd/configure.go
cli/cmd/configure_switch_profile.go
cli/cmd/root.go
integration/configure_switch_profile_test.go
integration/configure_test.go
integration/configure_unix_test.go
integration/configure_windows_test.go
integration/help_test.go

I would like to switch between my configured profiles
without using an interactive prompt, env var or editing the
`lacework.toml` config file directly.
**New Command**
```
$ lacework configure switch-profile profile2
Profile switched to 'profile2' (no more --profile)
```
Ran commands locally and added tests.
https://lacework.atlassian.net/browse/ALLY-797

feat(cli): switch-profile command

---

cli/cmd/generate_execute.go

This code might need to be refactored but for now, this seems to work
fine/better, if we don't create a new terminal, the output will be
removed, maybe because during initialization the library records the
current STDOUT? (not sure)

fix(terraform): create a new terminal

---

cli/cmd/generate_execute.go
go.mod
go.sum
vendor/github.com/abiosoft/colima/LICENSE
vendor/github.com/abiosoft/colima/util/terminal/output.go
vendor/github.com/abiosoft/colima/util/terminal/terminal.go
vendor/golang.org/x/crypto/ssh/terminal/terminal.go
vendor/modules.txt

Prior to this PR, running Terraform commands from the CLI gives limited feedback.  This change gives the end customer a live view of what Terraform is doing while still preserving the existing error handling behavior.
Executing the CLI && make test
N/A

feat(terraform): improve user feedback running terraform commands

---

api/compliance.go
api/compliance_aws.go
api/compliance_azure.go
api/compliance_gcp.go
cli/cmd/compliance.go
cli/cmd/compliance_aws.go
cli/cmd/compliance_azure.go
cli/cmd/compliance_gcp.go
cli/cmd/compliance_test.go
integration/compliance_aws_test.go

The lacework compliance command can now return a list of resources affected by a recommendation ID.
`lacework comp aws get <account_id> <reccomendation_id>`
`lacework comp gcp get <organization_id> <project_id>`
`lacework comp az get <tenant_id> <subscriptions_id>`
- Add unit test for regex validation `cli/cmd/compliance_test.go`
- Add integration tests  `integration/compliance_aws_test.go`
-  run `lacework comp aws get <account_id> <reccomendation_id>`
-  run `lacework comp gcp get <organization_id> <project_id>`
-  run `lacework comp az get <tenant_id> <subscriptions_id>`
https://lacework.atlassian.net/browse/ALLY-816
Usage:
```
// Output if no resources are affected
RECOMMENDATION DETAILS          
-----------------------------------------
ID                   AWS_CIS_2_5     
SEVERITY …
```

feat(cli): show resources affected by a compliance recommendation

---

cli/cmd/generate.go
cli/cmd/generate_aws.go
cli/cmd/generate_execute.go
integration/aws_generation_test.go

Currently, the default output location for the Terraform generation is `~/lacework/main.tf`
We should create a file for each cloud to ensure we don't override TF from another cloud.
With this change, we can pass any filename to the output location
eg. 
```
~/lacework/aws.tf
~/lacework/azure.tf
~/lacework/gcp.tf
```
make test ✅ 
run dev version of CLI and confirmed output location ✅ 
make fmt ✅ 
https://lacework.atlassian.net/browse/ALLY-890

refactor(cli): Create cloud specific TF file

---

cli/cmd/policy.go

Policies (LQL): Delete registered twice resulting in strange help output
```
lacework policy --help
Available Commands:
create      Create a policy
delete      Delete a policy
delete      Delete a policy
list        List policies
list-tags   List policy tags
show        Show policy
update      Update a policy
```
Manually
https://lacework.atlassian.net/browse/ALLY-900

fix(cli): delete listed twice on help

---

cli/cmd/lql_list.go
cli/cmd/lql_sources.go
cli/cmd/policy.go
integration/lql_list_test.go
integration/lql_sources_test.go
integration/policy_test.go

As a Lacework user, I would like the `lacework query ls`, `lacework query sources`, `lacework policy ls`, and `lacework policy list-tags` outputs to be sorted such that I can easily find items that I’m looking for
Manually tested
Integration tested
https://lacework.atlassian.net/browse/ALLY-910

feat(cli): sort query and policy list output

---

integration/host_vulnerability_test.go

Our QA tests are failing with:
```
=== FAIL: integration  (0.00s)                                                                                                                      
Setting up host tests                                                                                                                               
2022/03/08 03:25:44 Unable to get host for cveId                                                                                                    
[GET] https://qa4.qa4.corp.lacework.net/api/v1/external/vulnerabilities/host/cveId/                                                               
[404] HTTP 404 Not Found                                                                                                                          
FAIL …
```

test(integration): fix finding host id

---

Makefile
api/lql.go
cli/cmd/lql_update.go
integration/aws_generation_test.go
integration/configure_unix_test.go
integration/framework_test.go
integration/lql_update_test.go
integration/test_resources/help/query_update

I want to update a query without having to type the query again,
So I can modify my queries faster via inline modifications.
This change is adding the ability to load a query into the default
editor from the user so that they can easily make inline modifications.
Simply run the command `lacework query update [query_id]` and an editor
will open with the query preloaded, modify it, save and close the file
for the Lacework CLI to apply those modifications.
Ran it locally to do an inline editing:
https://lacework.atlassian.net/browse/ALLY-875

feat(cli): update query by loading it from the platform

---

integration/lql_update_test.go
integration/lql_update_unix_test.go

Our Windows CI pipeline is broken, this fixes the following error:
```
=== FAIL: integration TestQueryUpdateFromIDEditor (1.37s)
panic: unsupported [recovered]
panic: unsupported
```
Will run the Windows pipeline.
N/A

test(windows): fix TestQueryUpdateFromIDEditor

---

Makefile
cli/README.md

When working on new tests or existing tests, you can use a regex to run
only specific integration tests. For example, to run only the tests related
to the command `lacework query update` use the command:
```
make integration regex=TestQueryUpdate
```
**Note that it is a best practice to follow a naming convention where we name
test functions after their actual commands so that we can use these patterns.**
This command will match the regex `TestQueryUpdate*` and will execute any integration
test that matches that pattern. For more information about what regular expressions you
can use, visit https://pkg.go.dev/cmd/go#hdr-Testing_flags.
**TIP:** If you are NOT modifying the CLI code and instead, you are only updating
the integration tests, you can use the directive `make integration-only` …

chore(cli): run regex of integration test

---

cli/cmd/lql.go
cli/cmd/lql_create.go
cli/cmd/lql_internal_test.go
cli/cmd/lql_preview.go
cli/cmd/policy.go
cli/cmd/policy_create.go
cli/cmd/policy_create_internal_test.go
cli/cmd/policy_update_internal_test.go
integration/lql_constants.go
integration/lql_create_test.go
integration/lql_test.go
integration/lql_update_test.go
integration/lql_update_unix_test.go
integration/lql_validate_test.go
integration/policy_test.go
integration/test_resources/help/policy_create
integration/test_resources/help/query_create

Deprecate Evaluator ID from the Go-SDK and Lacework CLI
Existing and updated integration testing
https://lacework.atlassian.net/browse/ALLY-905

refactor(cli): further deprecate evaluatorId

---

integration/policy_test.go

The filter output is expecting to only see 'critical'  severity. It expects result not to contain 'lacework-global-1' however it is matching 'lacework-global-1**' eg 'lacework-global-189'
Fixed by adding a space  to the expected output so we do not match lacework-global-189 etc

test: fix policy severity filter test

---

api/_examples/cloud-accounts/aws-eks-audit/main.go
api/_examples/cloud-accounts/aws-eks-ct-sqs/main.go
api/_examples/cloud-accouts/main.go
api/cloud_accounts.go
api/cloud_accounts_aws_eks_audit.go
api/cloud_accounts_aws_eks_audit_test.go

In order to facilitate the creation of the EKS Audit Log Terraform Module, we need to add support for the AwsEksAudit cloud account integration
make fmt ✅ 
make test ✅ 
https://lacework.atlassian.net/browse/ALLY-945

feat(api): Implement AwsEksAudit CloudAccount interface

---

cli/cmd/lql.go
integration/lql_test.go
integration/test_resources/help/query_run

>As a Lacework user, I would like the CLI to default to an unambiguous time range.  Furthermore, certain Lacework batch operations run daily and we may need to “look back” further than just the “current day”.
Use "Last 24 Hours" instead of "Today"
Change is covered by existing integration
https://lacework.atlassian.net/browse/ALLY-943

feat(lql): more suitable default for lql run

---

cli/cmd/compliance_gcp.go

Add missing gcp report types to `lacework compliance gcp get-report` command
Run : 
`lacework compliance gcp get-report <organization> <project_id> --type NIST_CSF`
`lacework compliance gcp get-report <organization> <project_id> --type ISO_27001`
`lacework ...PCI_Rev2`
`lacework ...NIST_CSF`
`lacework ...NIST_800_171_REV2`
`lacework ...HIPAA_Rev2`
`lacework ...NIST_800_171_REV2`

fix: add missing gcp compliance report types to get-report command

---

api/datasources.go
cli/cmd/lql_sources.go
integration/lql_sources_test.go

> As a Lacework user I would like to understand the underlying relationships (i.e. implicit joins) of a given Lacework datasource.
At some point `sourceRelationships` was added to `v2/Datasources` we want to ensure that we can output this information if requested via verbose (i.e. json) output for list-sources as well as an additional table for show-source
Automated integration
Manually
https://lacework.atlassian.net/browse/ALLY-974

feat(cli): adds lql datasource relationships 

---

cli/cmd/lql.go
cli/cmd/outputs.go
integration/lql_create_test.go
integration/lql_create_unix_test.go

I want to have a boilerplate template when creating new LQL queries,
So I don't have to type the entire query from scratch.
I run the command `lacework query create` without inputs and my default editor opened with:
N/A - Needed for my Hackathon Project.

feat(cli): default template when creating LQL queries

---

cli/cmd/lql.go
cli/cmd/lql_create.go
cli/cmd/lql_update.go
cli/cmd/lql_validate.go
integration/lql_test.go

`lacework query run` was confused about how to get the query
Manually
Partial Integration Automation (we don't have integration testing for Lacework Content Library yet)
https://lacework.atlassian.net/browse/ALLY-977

fix(cli): fix lacework query run from library

---

cli/cmd/errors_lql.go
cli/cmd/lql.go
internal/failon/count_operation.go

Refactor how `--fail_on_count` bubbles up the error code and message by following
the best practice of policy enforcement. 
Ran the command `lacework query run LW_Global_AWS_CTA_IAMAccessKeyChange --fail_on_count '!=0'` and got:
```
[ ... ]
ERROR ENFORCE POLICY: query matched fail_on_count expression. [count:22] [expr:!=0] (exit code: 9)
```
https://lacework.atlassian.net/browse/ALLY-485

refactor: enforce query fail on count

---

cli/cmd/package_manifest.go
cli/cmd/package_manifest_test.go

We have added CVE data for ESM-enabled machines. This PR is adding
support for the CLI to detect when ESM is enabled on Ubuntu machines and
if so, it will add `esm` to the OS version.
Built a CLI binary and deployed it to an EC2 instance with ESM-enabled
```
root@ip-172-31-66-25:~# lacework version
lacework v0.31.1-dev (sha:521f2e40d175ddcc66c234611434999581ecf569) (time:20220413174742)
```
Generated a package manifest and verified that is returns the right os version with `esm` append
```
root@ip-172-31-66-25:~# lacework vuln host generate-pkg-manifest
{
"os_pkg_info_list": [
{
"os": "ubuntu",
"os_ver": "16.04esm",
"pkg": "accountsservice",
"pkg_ver": "0.6.40-2ubuntu11.6"
},
{
"os": "ubuntu",
"os_ver": "16.04esm",
"pkg": "acl", …
```

feat(cli): ubuntu ESM support

---

cli/cmd/lql_sources.go
integration/lql_sources_test.go

Only display datasource relationship information if actually available
Automated Integration
ALLY-974

fix(cli): only display datasource relationships when avail

---

cli/cmd/cli_state.go
cli/cmd/lql.go
cli/cmd/lql_show.go
cli/cmd/outputs.go
cli/cmd/policy.go
integration/lql_show_test.go
integration/policy_test.go
integration/test_resources/help/policy_show
integration/test_resources/help/query_show

Since the Lacework CLI support YAML format, we need to have a way to present queries with that format,
this PR adds a new flag `--yaml` to output the query in YAML format.
Added integration tests. 🚀
Hackathon https://lacework.atlassian.net/browse/HACK-55

feat(cli): output query in YAML format

---

api/v2_vulnerabilities.go

This is necessary as using the current response to iterate over pages
corrupts data that are slices, such as the tags within imageInfo. This is because
the memory address from the previous response will still contain data from the previous request.
By creating a new response using the nextPage url we get a new spot in memory to put the next
requests data.

fix(api): add newResponse for function SearchAllPages

---

cli/cmd/compliance_azure.go

As a user I would like to fully understand the implications of compliance report disable and be able to abandon ship if necessary.
Manually
https://lacework.atlassian.net/browse/ALLY-996

feat(cli): add azure compliance report disable warning

---

cli/cmd/compliance_azure.go
cli/cmd/compliance_gcp.go

As a user, I would like to fully understand the implications of compliance report disable and be able to abandon ship if necessary.
Manually
https://lacework.atlassian.net/browse/ALLY-997

feat(cli): add gcp compliance report disable warning

---

api/api.go
api/cloud_accounts.go
api/cloud_accounts_test.go
cli/cmd/cloud_account.go
cli/cmd/integration.go
cli/docs/lacework_cloud-account.md
cli/docs/lacework_cloud-account_list.md
cli/docs/lacework_integration.md
cli/docs/lacework_integration_create.md
cli/docs/lacework_integration_delete.md
integration/cloud_account_test.go
integration/test_resources/help/cloud-account
integration/test_resources/help/cloud-account_list
integration/test_resources/help/integration

Currently, the `lacework integrations list` command uses the v1 integration API which does not show new cloud account integrations such as the `AwsEksAudit` CA integration.
We should add `lacework cloud-accounts list` as a supported command to ensure users can display all of their cloud account integrations via the CLI. We should aim to add full CRUD for cloud-accounts, but this is a first step to allow the users to at least see their AWS EKS integrations. Ticket to cover full CRUD https://lacework.atlassian.net/browse/ALLY-999
https://lacework.atlassian.net/browse/ALLY-956

feat: Add support for APIv2 CloudAccounts List

---

cli/cmd/policy_library.go

As a user sync’ing policies I would prefer that they don’t sync the state portion of the policy definition such that policies that I have enabled or disabled remain enabled/disabled as such.
Manually.  We do not have CDK integration testing yet.
https://lacework.atlassian.net/browse/ALLY-1008

fix(cli): policy-sync should not touch policy state

---

internal/file/file.go
internal/file/file_test.go

Running Lacework CLI to check for host vulnerabilities on local Ubuntu images caused a panic.
The affected commands are:
```
lacework vulnerability host scan-pkg-manifest --local
```
and
```
lacework vulnerability host generate-pkg-manifest
```
This PR fixes this issue.
Added unit tests that replicate the issue (panic)
Closes https://lacework.atlassian.net/browse/ALLY-1004

fix(cli): panic while detecting ESM on Ubuntu sys

---

internal/file/file_test.go

Disable a test in our CI system since the pipeline runs as root, and root has access to every file and directory.
Run the test locally and the CI system should skip this test.
https://lacework.atlassian.net/browse/ALLY-1004

test: disable file test since CI runs as root

---

api/entities_machine_details.go
cli/cmd/flags.go
integration/test_resources/help/agent_list

The API has a structure defined for machine details tags.  The problem is the platform does not return a deterministic set of tags.  At a minimum the structure needs to be extended to output the set of tags known to GKE.
Manual
Existing automation
https://lacework.atlassian.net/browse/ALLY-1009

fix(cli): Add MachineDetail tags 

---

api/_examples/cloud-accounts/aws-eks-audit/main.go
api/cloud_accounts_aws_eks_audit.go
api/cloud_accounts_aws_eks_audit_test.go

Adding `S3BucketArn` to the AwsEksAudit schema to enable BYOB for customer integrations
blocked by https://github.com/lacework/rainbow/pull/8699
Currently only unit tests. 
https://lacework.atlassian.net/browse/ALLY-993

feat(api): Add S3BucketArn field to allow BYOB for AWS EKS Audit Log

---

cli/cmd/lql.go

When running the `lacework query run` command, display the start time and end time of time range the query is executing in the progress spinner.
run cmd 
`lacework query run <query-id>`
`lacework query run <query-id> --start -1hr`
example output:
```
>  Executing query in the time range 2022-May-25 13:12:43 UTC - 2022-May-26 13:12:43 UTC 
```
https://lacework.atlassian.net/browse/ALLY-938

feat: show query start time in progress spinner

---

cli/cmd/errors.go
cli/cmd/errors_test.go
integration/container_vulnerability_test.go
integration/host_vulnerability_test.go

As a Lacework CLI user “ENFORCE POLICY” terminology is confusing and overloaded when I ask the CLI to fail on certain criteria.
Existing automation has been updated
https://lacework.atlassian.net/browse/ALLY-1011

refactor(cli): updated terminology for fail_on

---

integration/host_vulnerability_test.go

Our nightly build is failing with:
```
=== Failed                                                                                                                                                            
=== FAIL: integration TestHostScanPkgManifestFailOnSeverity (8.44s)                                                                                                   
host_vulnerability_test.go:275:                                                                                                                                   
Error Trace:    host_vulnerability_test.go:275                                                                                                        
Error:          Not equal: …
```

test: fix pipeline to check for low vulns

---

api/lql_execute.go
api/lql_execute_internal_test.go
api/lql_execute_test.go
cli/cmd/lql.go
cli/cmd/lql_internal_test.go
cli/cmd/lql_preview.go

> I feel the way this function is written allows us to make easy mistakes such as 1) having the arguments in a different order and getting the start/end time wrong, and 2) passing less than two arguments which will throw a panic trying to access elements that don't exist since we are not checking that the array has at least two elements.
Unit testing
https://lacework.atlassian.net/browse/ALLY-1015

refactor(cli): query run progress message

---

cli/cmd/compliance_gcp.go

fix `lacework comp gcp enable <report_type>`
The CLI command `lacework compliance gcp enable` had been incorrectly set to send `disable` in the request body. This only affected the Gcp command. Aws and Azure were correct.
This fix set the correct request body.

fix(cli): compliance gcp enable command

---

cli/cmd/component.go
cli/cmd/lacework_content_library.go
cli/cmd/lacework_content_library_internal_test.go
lwcomponent/component.go
lwcomponent/component_test.go
lwcomponent/status.go

Finishing touches to release the CDK.
Improved `GetComponent()` to follow Golang idiomatic best practices, new usage:
```go
// GetComponent returns the pointer of a component, if the component is not
// found, this function will return a `nil` pointer and `false`
//
// Usage:
// ```go
// component, found := s.GetComponent(name)
// if !found {
//   fmt.Println("Component %s not found", name)
// }
// ```
``` 
Fixed `IsInstalled()` to return `true` when a component is installed but needs an update, this
is a different status and it was not being caught when a component was installed but needed
to be updated.
Tested locally and in Windows! 🪟
https://lacework.atlassian.net/browse/ALLY-964

refactor(cdk): improve GetComponent / IsInstalled funcs

---

lwgenerate/constants.go
lwgenerate/gcp/gcp_test.go

Use the latest version of our Terraform GCP config module https://registry.terraform.io/modules/lacework/config/gcp/2.1.0
Manually ran a generate command via the Lacework CLI
N/A - Escalation

chore(lwgenerate): bump GCP config module to ~> 2.0

---

cli/cmd/lql.go
cli/cmd/root.go

I wanted to make a style change to switch the use of if statements in favor of a switch statement, doing so
I saw one leftover `fmt.Println()` which I am removing. 
Nice feature @hazedav !!
Ran a query with a matching expression and without it.
https://lacework.atlassian.net/browse/ALLY-485

style(cli): use switch instead of if statements

---

api/_examples/cloud-accounts/gcp-gke-audit/main.go
api/cloud_accounts.go
api/cloud_accounts_gcp_gke_audit.go
api/cloud_accounts_gcp_gke_audit_test.go

In order to facilitate the creation of the GKE Audit Log Terraform Module, we need to add support for the GcpGkeAudit cloud account integration
make fmt ✅ 
make test ✅ 
https://lacework.atlassian.net/browse/ALLY-1012

feat(api): Implement GcpGkeAudit CloudAccount interface

---

cli/cmd/component.go

Since we are building the tree of commands from the available components, if there are
more than one component, the function injected gets overridden to the last component
loaded. Which essentially means that all commands will be running the same "last"
component.
This fixes that issue by loading the component dynamically, and then, running it. 
Installed two components and run them separately.
Additionally, removed the Long description and moved it to be the Short one. Looks better.
```
➜  go-sdk git:(afiune/fix-cdk-run-component) lacework help
The Lacework Command Line Interface is a tool that helps you manage the
Lacework cloud security platform. Use it to manage compliance reports,
external integrations, vulnerability scans, and other operations.
Start by configuring the Lacework CLI …
```

fix(cdk): run component dynamically

---

cli/cmd/component.go

To integrate the Soluble CLI into the Lacework CLI we are planning to add it as a
component (an extension) so that customers can discover and use it out-of-the-box.
This new environmental variable will allow us to inject the name of the component
at runtime so that all the help messages reflect the correct component name.
Depends on https://github.com/soluble-ai/soluble-cli/pull/431
Built both, the Lacework CLI and the Soluble CLI and tested:
https://lacework.atlassian.net/browse/RAIN-33521

feat(cdk): pass env variable LW_COMPONENT_NAME

---

cli/cmd/agent_list.go

Customers are reporting issues running the command `lacework agent list`, specifically on Windows machines.
Error message:
```
ERROR unable to list agents via MachineDetails search:
[POST] https://account.lacework.net/api/v2/Entities/MachineDetails/search
[400] endTime cannot be after current time
```
We shared a built binary to the customer and they validated that it now works.
https://lacework.atlassian.net/browse/ALLY-1067

fix(cli): subtract 1 minute from machine details end time

---

cli/install.ps1

This change is fixing the problem where, if a Windows workstation has
our agent installed and the user tries to install the Lacework CLI, the
installation script fails with:
```
Cannot remove item C:/Program Data/Lacework/Logs/LWData_0.log because it
is being used.
```
The solution is updating the installation script to avoid removing the
entire directory and instead, forcing the installation of the Lacework
CLI.
I used our Vagrant Windows 10 box and tested the script locally, also users can point
directly to this script with the following commands:
```
Set-ExecutionPolicy Bypass -Scope Process -Force;
iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/lacework/go-sdk/0917a32a5380804883b4bdf6728add …
```

fix(cli): install.ps1 avoid Windows agent collision

---

api/vulnerabilities_container.go
cli/cmd/vuln_container.go
cli/cmd/vulnerability_exceptions_test.go
cli/cmd/vulnerability_test.go
cli/cmd/vulnerabilty_exceptions.go
integration/event_test.go

Add `Status` field to container scan assessment output.
Create a new vulnerability exception. Add the cve-id as a criteria
`lacework ve create`
Run a new container assessment.
Run `lacework vulnerability container scan-status <scan-id>`
https://lacework.atlassian.net/browse/ALLY-1038

feat(cli): include status in vuln ctr scan assesment output

---

cli/cmd/cli_state.go

All API settings are prefixed with `LW_API_{XYZ}`, the API token should follow that pattern.
No need since this is not used just yet. 
Contributes to https://lacework.atlassian.net/browse/ALLY-1083

fix(cli): use proper env var name LW_API_TOKEN

---

api/integrations_aws.go
cli/cmd/policy_exceptions.go
integration/test_resources/help/no-command-provided
integration/test_resources/help/policy
integration/test_resources/help/policy-exception
integration/test_resources/help/policy-exception_create
integration/test_resources/help/policy-exception_delete
integration/test_resources/help/policy-exception_list
integration/test_resources/help/policy-exception_show
internal/array/unique.go

Add new commands to manage Lacework policy exceptions using the CLI
Run new commands
`lacework policy-exception list`
`lacework policy-exception list [policy-id]`
`lacework policy-exception show [policy-id] [exception-id]`
`lacework policy-exception delete [policy-id] [exception-id]`
`lacework policy-exception create`
https://lacework.atlassian.net/browse/ALLY-1060

feat(cli): policy exceptions crud

---

cli/cmd/cli_unix.go
cli/cmd/cli_windows.go
cli/cmd/component.go
cli/cmd/outputs.go
cli/cmd/root.go

This change is adding colors to the CDK commnads:
Run all commands locally.
https://lacework.atlassian.net/browse/ALLY-1088

feat(cli): colorize CDK commands

---

api/README.md

This will fix the api readme file to point to the right examples directory.
verified the new path is the correct one
haven't created one for this

docs: fix path to examples in readme

---

api/lql.go
api/lql_execute.go
api/lql_validate.go
api/policy.go
cli/cmd/lql.go
cli/cmd/lql_update.go
cli/cmd/lql_validate.go

We deprecated evaluatorId and now it should be fully removed
Automated integration testing (still includes examples with and without evaluatorId)
https://lacework.atlassian.net/browse/ALLY-1094

chore(lql): fully remove evaluatorId

---

cli/install.ps1
scripts/chocolatey/build/tools/chocolateyinstall.ps1

When an non-admin Windows user would install the Lacework CLI, we were
modifying the User's $Path environment variable incorrectly. In fact, we
were overriding the entire $Path to be the System's $Path (at the Machine)
This change is fixing this issue by properly updating the Users' or
System wide $Path environment variable.
Used our local Windows dev environment.
To test this code run this code:
```powershell
Set-ExecutionPolicy Bypass -Scope Process -Force
iex ((New-Object System.Net.WebClient).DownloadString('https://github.com/lacework/go-sdk/raw/5d03ed7e05e99d6df09f81d214e03f9a46f71553/cli/install.ps1'))
```
Jira:
- https://lacework.atlassian.net/browse/LINK-812
- https://lacework.atlassian.net/browse/ALLY-1103

fix(install.ps1): modify User $Path correctly

---

cli/cmd/lql.go
cli/docs/lacework_query_run.md
integration/test_resources/help/query_run

Adding example for `--failon` flag
Automated testing
Manual testing `lacework query run -h`
https://lacework.atlassian.net/browse/ALLY-1093

docs(cli): updating help for query run

---

api/vulnerability_exceptions.go
api/vulnerability_exceptions_test.go

Signed-off-by: Darren Murray [darren.murray@lacework.net](mailto:darren.murray@lacework.net)
Issue:
https://lacework.atlassian.net/browse/ALLY-1085
Fixes https://github.com/lacework/terraform-provider-lacework/issues/339
Description:
Allow fixable to be nil value

fix: vulnerabilty_exception fixable parameter omit when unset

---

api/client.go
api/client_test.go

This change is fixing a problem where users of the Go SDK try to use the FQDN downloaded from
the Lacework console to create a new API client, we are now verifying and cleaning it up.
Added unit tests.
Closes https://github.com/lacework/go-sdk/issues/860

fix(api): detect FQDN as account in api.NewClient()

---

cli/cmd/component.go
lwcomponent/component.go

As a user of the Lacework CLI adopting the new Cloud Development Kit (CDK),
I want to know what are the things I can do after installing a new component and,
what things changed when I upgraded an existing component,
So that I can quickly start using the new component and know what things changed with a component upgrade.  
Our CDK Components should leave a trail/crumb after installation or
update, these messages will be shown by the Lacework CLI, every
component owns the message that will be displayed.
Updated the content-library and tested in QAN:
Example message for the inline vulnerability scanner:
When following the breadcrumbs:
https://lacework.atlassian.net/browse/ALLY-1079
Relates to:
* https://github.com/lacework/rainbow/pull/9320
* …

feat(cdk): leave breadcrumbs after installation and update

---

Makefile
cli/cmd/component.go
integration/component_test.go

The command `lacework component list` wasn't working with the `--json` flag. This change
fixes that problem and display proper JSON output.
Added integration tests and checked on QAN.
N/A

fix(cdk): JSON output for 'component list' command

---

cli/cmd/lql_preview.go

Add newline to "No results found for datasource"
Manually
Existing Integration
https://lacework.atlassian.net/browse/ALLY-1122

fix(lql): add line break when no preview found

---

cli/cmd/alert_profiles.go

Fix alert profile filter used in `lacework alert-profile update`
This will return the correct list of profiles that can be updated. Non default profiles

fix: alert profile filter

---

integration/policy_test.go

Our nightly build failed. This fixes the following issue:
```
=== FAIL: integration TestPolicyShow/YAML_Output (0.48s)                                                                                                         
policy_test.go:364:                                                                                                                                          
Error Trace:    /codefresh/volume/go-sdk/integration/policy_test.go:364                                                                          
Error:          "policyId: lacework-global-1\npolicyType: Violation\nqueryId: LW_Global_AWS_CTA_VPCChange\ntitle: VPC Change\nenabled: true\ndesc
ription: A VPC was created, deleted or changed\nremediation: Check that the VPC change was expected. Ensure only specified …
```

ci: fix policy test

---

integration/framework_test.go
integration/version_test.go
lwupdater/updater.go
lwupdater/updater_test.go

Every time we run `lacework version` with a development version of the CLI we get the out of date
message, this change is avoiding it by not checking the version if it contains `-dev`.
Added tests, built the CLI locally and ran `lacework version`.
```
$ lacework version
lacework v0.39.1-dev (sha:7ac9e6cf43be68e603f79a105c8d29c5c01a50d1) (time:20220804163533)
```
N/A

fix(lwupdater): avoid comparing dev versions

---

cli/cmd/generate_aws.go
cli/cmd/generate_azure.go
cli/cmd/generate_gcp.go
integration/test_resources/help/cloud-account_iac-generate_aws
integration/test_resources/help/cloud-account_iac-generate_azure
integration/test_resources/help/cloud-account_iac-generate_gcp

In response to user feedback, documented the default location of the Terraform code generation commands when not specified via the --output flag. Kept it simple by adding as a mention to the help for the flag itself, since the command output itself shows the location as well. 
Updated pipeline tests.
N/A

docs(cli): add default output location

---

cli/cmd/policy_exceptions.go

Replace usage for v1 api in CLI with v2 api.
Existing tests on CI pass
Run `lacework policy policy-exception create` -> enter accountIds as constraint key
https://lacework.atlassian.net/browse/ALLY-1145

refactor(cli): migrate fetch accountIds in policy exception to API v2

---

scripts/chocolatey/build/lacework-cli.nuspec
scripts/chocolatey/build/tools/chocolateyinstall.ps1
scripts/chocolatey/build/tools/chocolateyuninstall.ps1

Address changes requested by chocolatey moderation process
Completed
```
- The iconUrl should be switched from github raw to a CDN: https://docs.chocolatey.org/en-us/create/create-packages#package-icon-guidelines
- Any changes to environment variables should be undone in a chocolateyUninstall.ps1
- Checksum(s) should be hardcoded into the package instead of being downloaded at runtime.
```
https://lacework.atlassian.net/browse/ALLY-1152

refactor(chocolatey): address moderation requested changes

---

cli/cmd/generate_gcp.go
integration/gcp_generation_test.go
integration/test_resources/help/cloud-account_iac-generate_gcp
lwgenerate/gcp/gcp.go
lwgenerate/gcp/gcp_test.go

The CLI parameter enable_ubla could never be set to false.
Use --enable_ubla=false to disable the TF gcp-audit-log feature.
Unit and integration testing
[ALLY-1188](https://lacework.atlassian.net/browse/ALLY-1188)

fix(ALLY-1188): Enable the disable of enable_ebla

---

scripts/codefresh.ps1

We never disabled windows tests as part of https://github.com/lacework/go-sdk/pull/917
Windows tests should pass...
https://lacework.atlassian.net/browse/RAIN-37563

test(win): disable failing integration test

---

api/alerts.go
api/alerts_close.go
api/alerts_close_test.go
api/alerts_comment.go
api/alerts_comment_test.go
api/alerts_details.go
api/alerts_details_events.go
api/alerts_details_events_test.go
api/alerts_details_integrations.go
api/alerts_details_integrations_test.go
api/alerts_details_investigation.go
api/alerts_details_investigation_test.go
api/alerts_details_related.go
api/alerts_details_related_test.go
api/alerts_details_test.go
api/alerts_details_timeline.go
api/alerts_details_timeline_test.go
api/alerts_test.go
api/api.go
api/v2.go

Adds:
```
List()
ListByTime(start, end time.Time)
Get(id int, scope alertScope)
GetDetails(id int)
GetEvents(id int)
GetRelatedAlerts(id int)
GetInvestigation(id int)
GetIntegrations(id int)
GetTimeline(id int)
Comment(id int, comment string)
Close(request AlertCloseRequest)
```
...and corresponding data structures
...and tests!
Alert search (https://lacework.atlassian.net/browse/ALLY-1206)
Alert entity map buildout (https://lacework.atlassian.net/browse/ALLY-1207)
Comprehensive unit test coverage
https://lacework.atlassian.net/browse/ALLY-1185

feat(api): introducing alertsv2 api

---

lwrunner/runner.go
lwrunner/runner_test.go

This change fixes the issue where we try to add a known host to the
known_hosts file but the directory ~/.ssh does not exist.
Now we are creating that directory first.
Replicated the issue inside our unit tests:
```
=== Failed
=== FAIL: lwrunner TestLwRunnerAddKnownHost (0.19s)
runner_test.go:132:
Error Trace:    /Users/afiune/github/go-sdk/lwrunner/runner_test.go:132
Error:          Received unexpected error:
open /var/folders/pn/rtky3yx17fx60dc03njhm_fw0000gn/T/lwrunner1052124622/.ssh/known_hosts: no such file or directory
Test:           TestLwRunnerAddKnownHost
```
Closes https://github.com/lacework/go-sdk/issues/915
Jira https://lacework.atlassian.net/browse/ALLY-1195

fix(lwrunner): create ~/.ssh directory if not exist

---

cli/cmd/generate_aws.go
cli/cmd/generate_azure.go
cli/cmd/generate_gcp.go
integration/aws_generation_test.go
integration/azure_generation_test.go
integration/gcp_generation_test.go

Not overwriting existing TF would lead to using an empty location string for console output and Terraform apply
- unit testing
- integration testing
- manual testing
[ALLY-1203](https://lacework.atlassian.net/browse/ALLY-1203)

fix: generate TF overwrite

---

cli/cmd/package_manifest_test.go

The error message for 'api/v1/external/vulnerabilities/scan' when user is not authorized has changed. Likely due to Rbac updates.
This is causing CI to fail. Updated with new error message
Run cli/cmd/package_manifest_test.go:134

test: update error msg test

---

cli/cmd/generate_azure.go
integration/aws_generation_test.go
integration/azure_generation_test.go
integration/gcp_generation_test.go
lwgenerate/aws/aws_test.go
lwgenerate/azure/azure.go
lwgenerate/azure/azure_test.go
lwgenerate/azure/test-data/activity-log-with-all-subscriptions.tf
lwgenerate/azure/test-data/activity-log-with-existing-storage.tf
lwgenerate/azure/test-data/activity-log-with-lacework-profile.tf
lwgenerate/azure/test-data/activity-log-with-list-subscriptions.tf
lwgenerate/azure/test-data/activity-log-with-location.tf
lwgenerate/azure/test-data/activity_log_with_config.tf
lwgenerate/azure/test-data/activity_log_without_config.tf
lwgenerate/azure/test-data/config-log-with-list-subscriptions.tf
lwgenerate/azure/test-data/config-with-all-subscriptions.tf
lwgenerate/azure/test-data/config-with-management-group.tf
lwgenerate/azure/test-data/config-with-storage-account.tf
lwgenerate/azure/test-data/config_without_activity_log.tf
lwgenerate/azure/test-data/customer-ad-details.tf
lwgenerate/azure/test-data/renamed_activity_log.tf
lwgenerate/azure/test-data/renamed_config.tf
lwgenerate/constants.go
lwgenerate/gcp/gcp_test.go

Azure TF requires the Lacework provider and the Lacework API profile defined, if a default profile hasn't been configured.
```
> terraform plan
╷
│ Error: Invalid provider configuration
│
│ Provider "registry.terraform.io/lacework/lacework" requires explicit configuration. Add a provider block to the root module and configure the provider's required arguments as described in
│ the provider documentation.
│
╵
╷
│ Error: Unable to create Lacework API client
│
│   with provider["registry.terraform.io/lacework/lacework"],
│   on <empty> line 0:
│   (source code not available)
│
│ profile 'default' not found.
│
│ Try using the Lacework CLI command 'lacework configure --profile default'
```
This error doesn't occur if `.lacework.toml` contains a default block.  It is a problem for the …

fix: azure Lacework provider & profile flag

---

cli/cmd/generate_aws.go
integration/aws_generation_test.go
integration/test_resources/help/generate_cloud-account_aws
lwgenerate/aws/aws.go
lwgenerate/aws/aws_test.go

[AWS cloud-trail](https://github.com/lacework/terraform-aws-cloudtrail#inputs) module expects `sns_topic_encryption` for encryption variables.
- unit
- integration
- manual
[RAIN-38110](https://lacework.atlassian.net/browse/RAIN-38110)

fix: aws terraform sns variables

---

lwcomponent/component.go
lwcomponent/component_test.go

When attempting to `json.Unmarshal` the `lwcomponent.Component` object several quirks are present.
```
{
"name": "abc",
"description": "def",
"type": "BINARY",
"version": {},
"artifacts": [
{
"os": "darwin",
"arch": "amd64",
"url": "",
"signature": ""
}
],
"breadcrumbs": {},
"command_name": ""
}
```
1.  Some items should be omitted if empty (i.e. `url` and `command_name`)
2. `version` should be a string not a dict
Unit tests added
https://lacework.atlassian.net/browse/ALLY-1229

fix(lwcomponent): better JSON handling components

---

integration/gke_generation_test.go

Nightly builds failing at windows testing stage - GKE integration tests missing flags to exclude from windows.  Adding this.

fix: gke integration test flags

---

Makefile

Running `make install-cli` continually fails on ARM architecture environments. Further investigation revealed that the `mv` command sequence in the Makefile's `install-cli` target only accounts for x64 and x86 environments. 
```bash
mv bin/lacework-cli-darwin-386 /usr/local/bin/lacework-dev
mv: rename bin/lacework-cli-darwin-386 to /usr/local/bin/lacework-dev: No such file or directory
make: *** [install-cli] Error 1
```
Ran `make install-cli` locally on an M1
* https://lacework.atlassian.net/browse/ALLY-1230

build: fix install-cli Makefile target to account for ARM builds

---

api/_examples/cloud-accounts/aws-agentless-scanning-org/main.go
api/cloud_accounts.go
api/cloud_accounts_aws_sidekick_org.go
api/cloud_accounts_aws_sidekick_org_test.go
api/cloud_accounts_aws_sidekick_test.go

This adds a new Cloud Account type `AwsSidekickOrg`, which is shorthand for Agentless Workload Scanning with AWS Organization integration. Or rather: multi-account AWS support. Previously with `AwsSidekick` it is single-account style integration.
With unit tests and by adding this into the vendor directory for `lacework/terraform-provider-lacework` and running `make test` for that repo locally.
RAIN-38397

feat(api): New AwsSidekickOrg Cloud Account type

---

cli/cmd/component.go
lwcomponent/component.go

Wanna develop a new CDK component? Run the command:
```
lacework component dev <component_name>
```
https://user-images.githubusercontent.com/5712253/196309255-37f17404-620f-4ae3-982e-acc7b81986c8.mp4
https://lacework.atlassian.net/browse/ALLY-1186

feat(cdk): dev-mode command

---

Makefile

Essentially, our CI has been failing since yesterday, we need to continue doing development
in this repo so we decided to disable the affected tests.

test(cli): disable compliance tests

---

cli/cmd/compliance.go
cli/cmd/compliance_aws.go
cli/cmd/compliance_azure.go
cli/cmd/compliance_gcp.go
cli/cmd/compliance_test.go
integration/compliance_aws_test.go
integration/compliance_azure_test.go
integration/compliance_gcp_test.go

Update the command `compliance aws|gcp|azure get-report <id>` to use the v2 api
Update `compliance_aws_test.go` and `compliance_test.go` with v2 mock responses.
Manually run:
`compliance aws|gcp|azure get-report <id>`
`compliance aws|gcp|azure get-report <id> --details`
`compliance aws|gcp|azure get-report <id> --json`
`compliance aws|gcp|azure get-report <id> [rec_id]`
https://lacework.atlassian.net/browse/ALLY-1212

refactor(cli): migrate cmd compliance aws|gcp|azure get-report

---

api/v2.go
api/v2_test.go

`NextPage` was dropping the query portion of URI's
Unit testing
https://lacework.atlassian.net/browse/ALLY-1242

fix(cli): add query parameters to paging path

---

cli/cmd/component.go
cli/cmd/component_test.go

Before this change, when someone would try to use global flags such as `--profile`, `--debug`, etc. while running a component, the CLI would bypass the parsing of all flags and it would send all arguments directly to the underlying component. This caused problems when switching profiles, activating debug logs, etc. (no global flag was working)
This change is implementing a parsing mechanism that will filter all real global flags from the provided arguments and pass the rest as arguments to the component. The filtered global flags are also parsed and applied.
Wrote unit tests for the filter function, note that I mocked a few things such as a couple structs and global
flags that will be generated at runtime by the underlying [Go package …

fix(cdk): parse global flags when running components

---

cli/cmd/generate.go
cli/cmd/generate_aws_eks_audit.go
cli/cmd/generate_aws_eks_audit_test.go
cli/cmd/generate_aws_test.go
cli/cmd/generate_k8s.go
integration/aws_eks_audit_generation_test.go
integration/framework_test.go
integration/test_resources/help/generate_k8s
integration/test_resources/help/generate_k8s_eks
lwgenerate/aws/aws.go
lwgenerate/aws_eks_audit/aws_eks_audit.go
lwgenerate/aws_eks_audit/aws_eks_audit_test.go
lwgenerate/constants.go
lwgenerate/hcl.go

Lacework CLI extension to include menus and generation of TF for EKS Audit Log
Manually ✅ 
Unit tests ✅ 
Integration tests ✅
https://lacework.atlassian.net/browse/RAIN-30917

feat(generate): Add Terraform generation for AWS EKS Audit Log

---

cli/cmd/cli_state.go
cli/cmd/component.go
cli/cmd/component_test.go

We were not passing a number of global flags via environment variables, this change adds them all.
Ran CDK commands
https://lacework.atlassian.net/browse/ALLY-1243

fix(cdk): Pass all global flags via env variables

---

cli/main.go
lwcomponent/error.go
lwcomponent/executable.go

**Current Behavior:**
When running a component, if the component fails, we print two error messages:
```
$ lacework iac fdsasd
Error: unknown command "fdsasd" for "iac"
ERROR unable to run component: exit status 1
```
**New Behavior:**
We detect that the error is a component failing to run and we avoid outputting two error messages:
```
$ lacework iac fdsasd
Error: unknown command "fdsasd" for "iac"
```
Ran manually both, component and non-component commands.
https://lacework.atlassian.net/browse/ALLY-1259

fix(cdk): Avoid double component error messages

---

cli/cmd/root.go
cli/main.go

This is just a style change since we should not check for error types inside our `main` package
but instead inside the `Execute()` function of the `cmd` package.

style(cdk): detect lwcomponent error inside Execute() 

---

cli/cmd/cache.go
cli/cmd/component.go

When the cached token expires running `lacework iac ...` does not pass LW_API_TOKEN.
With the iac component installed, I run `lacework access-token -d 10` to generate a very short lived token.
Initially a command like `lacework iac org list` will succeed.  But after ~10 seconds you will get:
```
samshen@Sams-Lacework-Laptop go-sdk % lacework iac org list
[Error] GET https://api.demo.soluble.cloud/api/v1/users/profile returned 401 in 463ms
[Error] {
"ok" : false,
"status" : 401,
"error" : "Unauthorized",
"timestamp" : "2022-11-07T17:21:12.923519Z",
"message" : "401"
}
[ Info] Are you not logged in?  Use lacework iac auth profile to verify.
[ Info] See https://docs.lacework.com/iac/ for more information.
Error: https://api.demo.soluble.cloud/api/v1/users/profile returned 401
ERROR unable to …
```

fix(cdk) pass valid LW_API_TOKEN to components

---

cli/cmd/agent_aws-install_ec2ic.go
cli/cmd/agent_aws-install_ec2ssh.go
integration/test_resources/help/agent_aws-install_ec2ic
integration/test_resources/help/agent_aws-install_ec2ssh

This commit switches the method of passing the agent token to
`aws-install`, and is a breaking change for the CLI.
The old method that was released in `v0.43.0` was to pass it as
a required arg. The new method in this PR will rely on passing the
token as an optional flag (`--token`) and asking the user to provide
it interactively if that flag is not present.
Fixes RAIN-42457
We initially decided to release the `aws-install` subcommand with the agent token as a required arg. We've changed our minds on this and have decided that it's better to ask the customer interactively (once) to select an agent token, or to explicitly pass it as a flag. The initial rationale to pass the agent token as a required arg was based on a poor design …

feat(cli)!: pass agent token as flag for `aws-install`

---

cli/cmd/aws.go
lwrunner/awsrunner.go
lwrunner/awsrunner_test.go

This commit refactors and adds unit tests for the SSH username
assignment logic in the `aws-install` CLI subcommand.
Specifically, this commit:
* Breaks down the AMI image name fetch and the lookup table code into
helper functions
* Adds unit tests for these helper functions
* Enforces using the username passed as the `--ssh_username` CLI arg
Fixes RAIN-42812
Added unit tests, ran integration tests from the agent repo
https://lacework.atlassian.net/browse/RAIN-42812

refactor(cli): fixup + test `aws-install` SSH user

---

cli/cmd/component.go
cli/cmd/root.go

ALLY-1279
For CDK components which are type `CLI_COMMAND` the CLI automatically creates child commands for them.  The `RunE` portion of these child commands has special handling for global flags.  However, the `PersistentPreRunE` portion of the rootCmd performs tasks (i.e. establishes a NewClient or does Migration) without the knowledge of these flags.
Since `RunE` is essentially “pre run” for CDK components we should:
1. have the root command check if we’re running a component, and if so avoid certain tasks
2. perform the tasks avoided by the root command within the RunE of the component
Manually
https://lacework.atlassian.net/browse/ALLY-1279

fix(cli): rootCmd to intelligently PreRun components 

---

cli/cmd/cli_state.go
cli/cmd/component.go
cli/cmd/component_args.go
cli/cmd/component_args_test.go
cli/cmd/honeyvent.go
cli/cmd/root.go
scripts/release.sh

Improves how we send a Honeyvent for components, this change also moves the logic of
parsing flags and initializing CLI state to the `PersistentPreRunE()` func. 
I will add a number of integrations tests but first I want to check if this logic looks good or not?
N/A

feat(cdk): improve honeyvent data for components

---

integration/aws_eks_audit_generation_test.go
integration/aws_generation_test.go
integration/azure_generation_test.go
integration/framework_test.go
integration/gcp_generation_test.go
integration/gke_generation_test.go

Tidying Azure and AWS integration tests.  Making use of the `MsgRspHandler` interface.
`TestMain` for integration tests that installs Terraform in tmpfs.  Each TF generation integration test will now install and validate the terraform.
Avoid a repeat of [ALLY-1275](https://lacework.atlassian.net/browse/ALLY-1275) by catching Terraform version incompatibility in our integration testing.
Catch Terraform module input errors.
- unit
- integration
[ALLY-1189](https://lacework.atlassian.net/browse/ALLY-1189)

Jon stewart/ally 1189/tf validate

---

cli/cmd/compliance_aws.go
cli/cmd/compliance_azure.go
cli/cmd/compliance_gcp.go
cli/cmd/vulnerability.go
cli/cmd/vulnerabilty_exceptions.go
lwseverity/severity.go
lwseverity/severity_test.go

Support use cases where the CLI needs to validate a severity (i.e. via input).
Current Pattern:
```
if !array.ContainsStr(api.ValidEventSeverities, vulCmdState.Severity) {
return errors.Errorf("the severity %s is not valid, use one of %s",
vulCmdState.Severity, strings.Join(api.ValidEventSeverities, ", "),
)
}
```
Updated Pattern:
```
if !lwseverity.IsValid(vulCmdState.Severity) {
return errors.Errorf("the severity %s is not valid, use one of %s",
vulCmdState.Severity, lwseverity.ValidSeverities.String(),
)
}
```
Unit Testing
Existing Integration Testing
https://lacework.atlassian.net/browse/ALLY-1284

feat(lwseverity): add valid severity use cases

---

api/cloud_accounts.go
api/cloud_accounts_gcp_sidekick.go
api/cloud_accounts_gcp_sidekick_test.go
api/integrations.go
api/integrations_gcp.go

This features adds the Sidekick Integration type needed by terraform provider module to access the new integration.
Closes Internal Ticker - #RAIN-43475
Created and deleted integration from provider repo. 
Added unit test to verify create, get and update operations for GcpSidekick integration.
```
bash-3.2$ go test -v -run "TestCloudAccountsGcpSidekick"
=== RUN   TestCloudAccountsGcpSidekickCreate
--- PASS: TestCloudAccountsGcpSidekickCreate (0.00s)
=== RUN   TestCloudAccountsGcpSidekickGet
--- PASS: TestCloudAccountsGcpSidekickGet (0.00s)
=== RUN   TestCloudAccountsGcpSidekickUpdate
--- PASS: TestCloudAccountsGcpSidekickUpdate (0.00s)
PASS
ok      github.com/lacework/go-sdk/api  0.149s
bash-3.2$
```
RAIN-43475

feat: Add new cloud account type GCP Sidekick Integration

---

Makefile
api/container_registries_dockerhub.go
api/container_registries_dockerhub_test.go
cli/cmd/integration_docker_hub.go

Users trying to use our Terraform resource to manage Docker Hub integrations are failing with:
```
lacework_integration_docker_hub.this: Creating...
╷
│ Error:
│ [POST] https://account.lacework.net/api/v2/ContainerRegistries
│ [400] Error validating integration. Please verify the configuration details entered.
│
│ with lacework_integration_docker_hub.this,
│ on dockerhub_integration.tf line 1, in resource "lacework_integration_docker_hub" "this":
│ 1: resource "lacework_integration_docker_hub" "this" {
``` 
This change is fixing a few issues in the `api` package that interacts with container registry integrations.
Wrote tests 😄 
https://lacework.atlassian.net/browse/LINK-1089

fix(api): container registry dockerhub 🐛 

---

scripts/release.sh

find_latest_version() in  release script does not sort semver correctly. When trying to return the latest version v1.0.0 is returned at below v0.46.0 in the list.

ci: fix release script; sort versions in find_latest_version

---

api/v2_vulnerabilities.go

Fix highest found severity sorting
Run `lacework vuln ctr --fail_on_severity` with different thresholds, and confirm exit code is correct
https://lacework.atlassian.net/browse/ALLY-1301

fix: fix vuln ctr fail_on_severity

---

.gitignore
cli/cmd/agent_gcp-install-osl.go
cli/cmd/compliance_azure.go
integration/test_resources/help/agent_gcp-install_osl
integration/test_resources/help/compliance_azure

Documentation Autogeneration was broken due to usage of <>. Per request from the docs team.
https://lacework.atlassian.net/browse/ALLY-1302

docs: fix documentation autogeneration

---

cli/README.md
cli/cmd/generate_execute.go
cli/cmd/generate_terraform_test.go

No longer referring to deprecated command.
- unit test
[ALLY-1297](https://lacework.atlassian.net/browse/ALLY-1297)

fix: generate success message

---

Makefile

On some arm64 platforms, the `uname -m` command will return 'aarch64' and not 'arm64'. This results in the incorrect lacework cli executable to be installed, namely a 386 version of it. This commit ensures that aarch64 is treated identically to arm64.
Test plan:
1. On an M1 mac, I open a Docker container:
```
docker run -it --rm --entrypoint /bin/bash -v `pwd`:/go-sdk golang:1.18
```
2. Verify that `uname -m` outputs aarch64.
3. I install the cli:
```
cd /go-sdk
make prepare
make install-cli
```
4. Verify that the installed version works:
```
lacework version
```
The fact that the Lacework version worked means that we're no longer invoking a 386 binary (which of course immediately crashed)/

build(cli): Support aarch64 architecture

---

cli/cmd/vuln_container_scan.go

Currently when the` <tag|digest>` argument is set for the Container Vulnerability Scan command in the CLI, it is not used in any filtering to return the required results
This was raised by a customer and the fix is required as it is a blocker for the customer's very time sensitive promotion
This was tested by using the cli command `lacework vuln ctr scan index.docker.io lacework/lacework-cli <tag|digest> --poll ` with alternative `tag` and `digest` values and then examining the results returned and checking that the filter has actually been applied
```
lacework vuln ctr scan index.docker.io lacework/lacework-cli  ubuntu-1804 --poll
ID          sha256:ba6399b27f9bb063f95b12588e49125a69e528f6692cd0b7077a2464d91bf7e5       SEVERITY   COUNT   FIXABLE
Digest …
```

fix: vuln ctr scan to use tag/digest argument to filter

---

api/policy.go
cli/cmd/policy.go

When running a lacework policy show <policId> we should parse & display the supported policy exception constraints, as we now have this info available in the response
Tested locally
https://lacework.atlassian.net/browse/GROW-1314

feat: Display supported policy exception constraints

---

.go-version
api/v2_suppressions_aws.go
api/v2_suppressions_test.go
cli/cmd/suppressions.go
cli/cmd/suppressions_aws.go
cli/cmd/suppressions_aws_test.go

As part of the legacy compliance deprecation effort, the legacy cfg-analyzers will be decommissioned some time in January 2023. As a result customers will be moved across to the new LPP policies and CIS benchmarks. This is likely to cause a lot of noise for customers as they will have suppressions in place for resources which they expect to be in a non compliant state.
At present there is no easy path for customers to migrate their old suppressions to the new exceptions policies.
We do have a scripted approach created by Marc Garcia: https://github.com/lacework-dev/scripts/tree/main/lw-suppressions-migration
However it was decided that we should add this to the CLI as a more "official" approach.
This PR adds the following hidden commands:
``` …
```

feat: Add support from hidden suppressions migration command

---

cli/cmd/compliance_aws.go
cli/cmd/compliance_azure.go
cli/cmd/compliance_gcp.go

Api v2 returns the report type in a different format. Revert the format change in cvs output 
The v1 api csv reports had the report_type field format as `AWS_CIS_S3`
The v2 api report_type field format was`CIS Amazon Web Services Foundations Benchmark v1.4.0`
This change reverts back to `AWS_CIS_S3`
Run the compliance get-report cmd with csv flag
https://lacework.atlassian.net/browse/ALLY-1306

fix: revert compliance csv report_type field format

---

cli/cmd/alert.go
cli/cmd/alert_list.go
cli/cmd/alert_list_fixable.go
cli/cmd/alert_list_fixable_internal_test.go
cli/cmd/component.go
cli/cmd/content_library.go
cli/cmd/content_library_internal_test.go
cli/cmd/lql.go
cli/cmd/lql_create.go
cli/cmd/lql_library.go
cli/cmd/lql_update.go
cli/cmd/lql_validate.go
cli/cmd/policy.go
cli/cmd/policy_library.go
integration/alert_list_test.go

For CLI consumers which have the `remediate` CDK component installed they will get a new feature (flag) in the `lacework alert ls` command.  When using the `--fixable` flag you will also get an additional breadcrumb.
```
❯ lacework-dev component list
STATUS            NAME         VERSION                      DESCRIPTION                      
----------------+-----------------+---------+-----------------------------------------------------
...
Installed       remediate         0.0.1     A tool to isolate and remediate resources           
...
Components version: 0.2.0
```
```
❯ lacework-dev alert list -h
List all alerts.
...
Flags:
--end string        end time for alerts (default "now")
--fixable           filter alerts by fixability
...
```
```
❯ lacework-dev alert list --fixable
ALERT …
```

feat(cli): add filter for fixable alerts

---

api/policy.go

The lacework cli injects an empty string for the alertProfile when creating a policy.
```
lacework policies create -f p
fails when p contains the json:
{
"policyType": "Compliance",
"severity": "high",
"title": "Trouble ahead",
"description": "Trouble indeed, my friend",
"remediation": "oh boy, it will not be easy",
"enabled": true,
"alertEnabled": true,
"queryId": "SomeQuery"
}
```
The debug output contains:
```
{"level":"debug","ts":"2022-12-14T15:16:58-05:00","caller":"api/http.go:91","msg":"request","id":"60eb86346e026cc0","account":"dev8.dev8.corp","method":"POST","url":"https://dev8.dev8.corp.lacework.net","endpoint":"/api/v2/Policies","headers":{"Accept":["application/json"],"Authorization":["..."],"Content-Type":["application/json"],"Method":["POST"],"User-Agent":["Command-Line/0.4 …
```

fix: avoid injecting empty alertProfile

---

cli/cmd/cdk.go

Signed-off-by: Kolbeinn Karlsson <kolbeinn.karlsson@lacework.net>
With this PR, the environment variable LW_API_SERVER_URL will be passed to CLI components. This will make cli component development and testing a lot easier.
In the component I'm working on, `remediate`, I created a simple function called foo with the following code:
```
func foo(cmd *cobra.Command, args []string) {
fmt.Printf("LW_API_SERVER_URL: %v\n", os.Getenv("LW_API_SERVER_URL"))
}
```
Then I called it with the environment variable explicitly set and implicitly set:
```
> lacework-dev remediate foo
LW_API_SERVER_URL: https://dev7.dev7.corp.lacework.net
> LW_API_SERVER_URL=http://localhost lacework-dev remediate foo
LW_API_SERVER_URL: http://localhost
```

feat(cli): pass LW_API_SERVER_URL env variable to components

---

lwlogger/logger.go

Signed-off-by: Kolbeinn Karlsson <kolbeinn.karlsson@lacework.net>
lwlogger silently overrides any level passed to it with the value of the LW_LOG environment variable. This may not cause issues in the main CLI, but for CLI components, LW_LOG is always set, and thus there is no way to create any lwloggers without their level being overridden.
This PR changes it so that the lwlogger level is overridden with LW_LOG only if `level=""`. This is provides maximum flexibility for the logger. You can call `lwlogger.New("")` to have the level be determined by LW_LOG, or you can call `lwlogger.New(myDesiredLevel)` to explicitly set the level.
In the Lacework remediate component, I create a simple function foo with the following logic:
```
func foo(cmd *cobra.Command, args []string) {
loggerOne := …
```

fix(lwlogger): do not override explicit level argument

---

lwlogger/logger.go
lwlogger/logger_test.go

Merging multiple loggers into one creates a ton of power and flexibility for lwlogger. This enables you to easily create a logger that writes to multiple outputs (e.g. standard output and a file), potentially at varying levels (e.g. only write ERROR level messages to stdout but include INFO messages in the file). This is something we needed to do in the 'remediate' component. I figure other people might want to do the same so I propose we add this function to lwlogger itself. 
I added a unit test, TestLoggerMerge. Run it by running `go test ./lwlogger/...`.

feat(lwlogger): add merge logger function

---

cli/cmd/cdk.go

Maybe, components will need to know the version of the Lacework CLI they are running on.
Verified that the new variable was there.
https://lacework.atlassian.net/browse/GROW-1264

feat(cdk): pass LW_CLI_VERSION env variable

---

cli/cmd/cli_state.go
cli/cmd/root.go
integration/framework_test.go

Default to non-interactive output if stdout is not a terminal.
I've happen to have 1.2.0 installed and at the moment the latest version is 1.3.1.
```
; rm ~/.config/lacework/version_check
; lacework configure show account > /tmp/account.txt
; cat /tmp/account.txt
qan.qan.corp
A newer version of the Lacework CLI is available! The latest version is v1.3.1,
to update execute the following command:
brew upgrade lacework-cli
; rm ~/.config/lacework/version_check
; go run cli/main.go configure show account > /tmp/account.txt
; cat /tmp/account.txt
qan.qan.corp
```
After thinking about it a bit it's not the daily version check that's the problem, it's that we shouldn't assume we're interactive if stdout isn't a terminal.
https://lacework.atlassian.net/browse/RAIN-45976

feat: default to non-interactive if stdout is not a terminal

---

cli/cmd/component.go
lwcomponent/component.go
lwcomponent/component_internal_test.go
lwcomponent/component_test.go

This makes two changes to improve managing different versions of components:
- `lacework component install` and `lacework component update` now accept a `--verison` flag to force a specific version to be installed rather than the latest one.
- There is a new command `lacework component show <name>` that shows details for a component, including all available versions.
There's unit tests for the main interesting new utility functions which construct the update message and display the list of available versions to the user. I also exercised this manually to check end to end functionality.
https://lacework.atlassian.net/browse/GROW-1058

feat(GROW-1058): Improve management of component versions

---

integration/lwupdater_test.go
lwupdater/updater.go

This does two things to make the test less likely to fail:
- Moves it to integration tests so it isn't run locally where users might hit rate limits by running it repeatedly.
- Uses the `GITHUB_TOKEN` environment variable if present (which it is in CI) to authenticate the request and get higher rate limits.
The test being changed will be exercised by the CI on this PR.
https://lacework.atlassian.net/browse/GROW-1320
[GROW-1320]: https://lacework.atlassian.net/browse/GROW-1320?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(lwupdater): Make test that makes an API call more robust

---

Dockerfile

Our CircleCI orb is complaining with the following error message:
```
Build image is not supported. Please check that it contains a shell and /bin directory.
```
This is caused by the fact that the `scratch` base image has pretty much nothing inside,
not even a Shell. We made this decision so that our image is less than 20 MB. This is not
working for us anymore and we are refactoring our image to use `alpine` as our base image.
This change will only add a few MBs more to our image.
Running a CircleCI jobs to validate: https://github.com/lacework/circleci-orb-lacework/pull/40
Uploaded the image to a [temporal Docker repository](https://hub.docker.com/layers/techallylw/lacework-cli/alpine/images/sha256-539b1a823bbd654b39b05d6ff388433f8841e007083a8c7136bc3de82f938671?context=explore …

refactor: Use alpine as our base Docker image

---

cli/cmd/component.go

As a Lacework CDK developer,
I need a way to run a cleanup event for when my component is being uninstalled,
So that I can remove any file, cache, libraries, etc. before the component is removed.
When installing new CDK components, users use the command `lacework component install <component>` which runs the lifecycle event `cdk-init`, this event helps components to deploy any necessary file, cache, config, libraries, etc. during installation. When users want to uninstall the component, we should have a cleanup event to remove anything deployed.
There are no components that implement this lifecycle so there should not be any impact.
Jira: https://lacework.atlassian.net/browse/GROW-1081
Documentation: https://lacework.atlassian.net/l/cp/u18EHxx1
Signed-off-by: Salim Afiune Maya …

style(cdk): rename lifecycle event cdk-cleanup

---

api/v2.go
api/v2_suppressions.go
api/v2_suppressions_azure.go
api/v2_suppressions_gcp.go
cli/cmd/suppressions.go
cli/cmd/suppressions_aws.go
cli/cmd/suppressions_azure.go
cli/cmd/suppressions_gcp.go

Following on from https://github.com/lacework/go-sdk/pull/1069, there has been an ask to make the Azure & GCP suppressions objects available via the CLI to aide in any manual migration of the Azure & GCP suppressions
Installed CLI locally and verified the suppression objects are returned as expected
https://lacework.atlassian.net/browse/RAIN-45215

feat(RAIN-45215): Add Hidden Azure & GCP suppressions list commands

---

api/v2_search_filters.go
integration/compliance_aws_test.go

`compliance search <resource_arn>` command is not setting start time correctly when it is required to search > 7 days
Run the compliance search command with a resource that cannot be found in the last 7 days

fix: compliance search

---

cli/cmd/policy_exceptions.go

Output of CLI JSON before the keys are stripped from the API response.
Manual testing
https://lacework.atlassian.net/browse/GROW-1326

fix: policy-exception json keys

---

cli/cmd/compliance.go
integration/test_resources/help/compliance_aws
integration/test_resources/help/compliance_azure
integration/test_resources/help/compliance_google

It appears we may have left in some help test in relation to running legacy on demand scans, which is no longer supported in the CLI. We should remove this text.
Verified locally that the on demand scan help text no longer appears

chore: Update lacework compliance <csp> help text

---

integration/lwupdater_test.go

CI is complaining with:
```
=== FAIL: integration TestVersionLoadCacheError (0.00s)
lwupdater_test.go:82:
Error Trace:    C:\codefresh\volume\go-sdk\integration\lwupdater_test.go:82
Error:          "open C:\\Users\\ContainerAdministrator\\AppData\\Local\\Temp\\version_cache3254653061/version_cache: The system cannot find the file specified." does not contain "no such file or directory"
Test:           TestVersionLoadCacheError
```
CI should pass
N/A

test(lwupdater): fix windows test

---

Makefile
cli/cmd/vuln_container_scan.go
cli/cmd/vuln_container_show_assessments.go
integration/container_vulnerability_test.go
integration/host_vulnerability_test.go

Once a scan is complete, we fetch results using the Search API but and filtering by repository, image and tag/sha. Now we are adding two more filters to return accurate data. The request id and `is_reeval`.
This fixes:
* https://lacework.atlassian.net/browse/GROW-1350
* https://lacework.atlassian.net/browse/LINK-1245
I have re enabled all container vulnerability tests.
* https://lacework.atlassian.net/browse/GROW-1350
* https://lacework.atlassian.net/browse/LINK-1245

fix(cli): use request id to fetch scan results

---

cli/cmd/root.go
integration/test_resources/help/no-command-provided

The help command should show help for a component instead of help for the CLI.
Run `go run cli/main.go iac help org list` and note that it now displays help for `... iac org list` instead of help for the CLI itself.
https://lacework.atlassian.net/browse/RAIN-42930

feat(cdk): make help command work for components

---

cli/cmd/suppressions.go
cli/cmd/suppressions_aws.go
cli/cmd/suppressions_aws_test.go
cli/cmd/suppressions_gcp.go
cli/cmd/suppressions_gcp_test.go
vendor/github.com/aws/aws-sdk-go-v2/aws/arn/arn.go
vendor/modules.txt

As part of the legacy compliance deprecation effort, the legacy cfg-analyzers will be decommissioned some time in January 2023. As a result customers will be moved across to the new LPP policies and CIS benchmarks. This is likely to cause a lot of noise for customers as they will have suppressions in place for resources which they expect to be in a non compliant state.
At present there is no easy path for customers to migrate their old suppressions to the new exceptions policies.
We do have a scripted approach created by Marc Garcia: https://github.com/lacework-dev/scripts/tree/main/lw-suppressions-migration
This PR adds the following hidden commands:
```
lacework suppressions migrate gcp
```
suppressions has the following alias' `suppression, …

feat(cli): add hidden suppressions migrate gcp command

---

api/entities.go
api/entities_containers.go
cli/cmd/flags.go
cli/cmd/vuln_container.go
cli/cmd/vuln_container_list_assessments.go
cli/cmd/vuln_container_test.go
cli/cmd/vulnerability.go
integration/container_vulnerability_test.go
integration/test_resources/help/vulnerability_container
integration/test_resources/help/vulnerability_container_list-assessments
scripts/codefresh.ps1

As a Lacework CLI user that upgraded to version 1.0.0 or above,
I want to have the flag `--active` back,
Since I have running workflows that depend on it to give me actionable insights of vulnerabilities actively running on my environment
We removed this flag as part of the v1.0.0 release but we are adding it back!
Locally and integration tests should now display active containers.
https://lacework.atlassian.net/browse/GROW-1361

feat: add --active flag back to vuln ctr list-assessments

---

lwrunner/awsrunner.go

Calls to the EC2 API currently fail when the region of the runner is
different from the region of the credentials used to authenticate the
request.
This commit modifies the EC2 client that we create during `ec2ssm`
execution to use `run.Region` instead of `cfg.Region`.
Fixes RAIN-47298
Found a bug during a customer deployment around this. There was a workaround to use credentials with the same region as the runners, but we should be region agnostic.
Adding an instance in a different region to the `ec2ssm` integration test sandbox infra, PR to come
https://lacework.atlassian.net/browse/RAIN-47298

fix(cli): ec2ssm use runner region, not cfg region

---

cli/cmd/suppressions.go
cli/cmd/suppressions_azure.go
cli/cmd/suppressions_azure_test.go
cli/cmd/suppressions_gcp.go
cli/cmd/suppressions_gcp_test.go

As part of the legacy compliance deprecation effort, the legacy cfg-analyzers will be decommissioned some time in January 2023. As a result customers will be moved across to the new LPP policies and CIS benchmarks. This is likely to cause a lot of noise for customers as they will have suppressions in place for resources which they expect to be in a non compliant state.
At present there is no easy path for customers to migrate their old suppressions to the new exceptions policies.
We do have a scripted approach created by Marc Garcia: https://github.com/lacework-dev/scripts/tree/main/lw-suppressions-migration
This PR adds the following hidden commands:
```
lacework suppressions migrate azure
```
suppressions has the following alias' …

feat(cli): add hidden suppressions migrate azure command

---

lwtime/reltime.go

Relative time function sets "now" to local time rather than UTC
This has been causing issues in search apis where time filter is provided.
```
[400] endTime cannot be after current time
```
Set timezone to gmt +1, then run 
`lacework vuln ctr list-assessments`
- https://lacework.atlassian.net/browse/GROW-1393
- https://lacework.atlassian.net/browse/LINK-1322

fix: change ParseRelative time to use UTC instead of local time

---

lwtime/nattime.go
lwtime/reltime.go

The lwtime package should be returning relative and natural times universally UTC().  
Set timezone to gmt +1, then run
lacework vuln ctr list-assessments
```
~/Applications/src/lacework/go-sdk GROW-1393-duex
❯ lacework-dev vuln ctr list-assessments
There are no assessments in your environment.
~/Applications/src/lacework/go-sdk GROW-1393-duex 9s
❯ lacework vuln ctr list-assessments 
Usage:
lacework vulnerability container list-assessments [flags]
...
ERROR unable to search for active containers: 
[POST] https://dev7.dev7.corp.lacework.net/api/v2/Entities/Containers/search
[400] endTime cannot be after current time
```
https://lacework.atlassian.net/browse/GROW-1393

fix(lwtime): natural/relative time to use UTC instead of local time

---

api/api.go
api/component_data.go
api/component_data_test.go
api/v2.go

This PR adds support in the Go SDK for having components upload data back to the Lacework platform via the new `/v2/ComponentData` API end-points (added in https://github.com/lacework/rainbow/pull/11260). Rather than allowing the end-points to be called individually (which there is no intended use-case for), this adds a single new function which handles the whole flow of performing an upload: that is, requesting from the API server some pre-signed URLs to upload data to S3, performing the upload, and then sending the API server a confirmation that the upload was completed successfully. This encapsulates this flow in the SDK rather than duplicating it accross components so that if we need to change it in future we only need to change it here.
Each of the network steps includes retrying …

feat(api): Add support for the `ComponentData` API end-points

---

cli/cmd/cdk.go
cli/cmd/cdk_test.go
cli/cmd/cli_state.go
cli/cmd/component.go

There is a port collision when running multiple instances of the Lacework CLI when invoking components. Each instance of the Lacework CLI attempts to start a gRPC server on the same port, 1123, and only one of them succeeds. To reproduce:
```
lacework remediate version & lacework remediate version
```
The above command starts two instances of the Lacework CLI in parallel. The end result:
```
[1] 283414
{"level":"error","ts":"2023-02-08T15:04:15Z","caller":"cmd/component.go:200","msg":"couldn't serve gRPC server","error":"failed to listen: listen tcp 127.0.0.1:1123: bind: address already in use","errorVerbose":"listen tcp 127.0.0.1:1123: bind: address already in use\nfailed to listen\ngithub.com/lacework/go-sdk/cli/cmd.(*cliState).Serve\n\t/codefresh/volume/go-sdk/cli/cmd/cdk.go:106\ngithub …
```

fix(cli): gRPC port collision

---

cli/cmd/agent_aws-install_ec2ssm.go
lwrunner/awsrunner.go
lwrunner/awsrunner_test.go

In rare cases, `ssm.GetCommandInvocationOutput` has `nil` fields. This
often occurs when there was also an error returned.
This commit adds helper functions to safely get stdout and stderr from
SSM commands, as well as unit tests for these functions. This commit
also calls these functions where `ec2ssm` reads SSM command output.
Fixes RAIN-47644
Added unit tests for new code, checking that integration tests pass.
https://lacework.atlassian.net/browse/RAIN-47644

fix(ec2ssm): safely dereference SSM command output

---

api/client.go
api/client_test.go

If the account name contains `lacework.net`, we were using `lwdomain.New(...)` to parse it. But then we were only using `.Account` from the result, and discarding `.Cluster` and `.Internal` which are also needed to construct the proper URL. Instead, let's call `.String()` which [correctly](https://github.com/lacework/go-sdk/blob/19f1f3ca3d4e8d989ac4fae25830874e23a72731/lwdomain/domain.go#L91-L101) builds a string including all of those parts. Also adds full unit test coverage of all these cases.
~~Moderately urgent: Internal usage of SAST and SCA is currently broken due to this.~~ We worked around this, so it is no longer causing an incident for us. Still, it would be nice to get a fix in so others can avoid issues due to this in the future.

fix: parsing of account names containing `lacework.net`

---

api/reports_aws.go
api/reports_azure.go
api/reports_gcp.go
cli/cmd/compliance_aws.go
cli/cmd/compliance_azure.go
cli/cmd/compliance_gcp.go
integration/compliance_aws_test.go
integration/test_resources/help/compliance_aws_get-report
integration/test_resources/help/compliance_azure_get-report
integration/test_resources/help/compliance_google_get-report

Resolve conflicting supported report types in cli and api packages
- Remove list of supported report types from cli package.
- Only use list of support report types from api package in `lacework compliance` input validation
- Add new integration test for all `aws` report types
- Manually verify there is no error submitting valid report types for `gcp` & `azure`
`lacework compliance gcp get-report <project-id> <org-id> --type GCP_CMMC_1_02`
`lacework comp az get-report <tenant-id> <org-id>`
https://lacework.atlassian.net/browse/GROW-1427

fix: resolve supported aws report types in cli and api packages

---

lwseverity/severity.go
lwseverity/severity_test.go

Use stable sorting for severity sorting.  This preserves the order of items coming in such that if we first sort by ID this will become a secondary sort once sorting by severity.  This is needed since severities are not unique.
Unit testing added
https://lacework.atlassian.net/browse/GROW-1432

fix(lwseverity): use stable sorting for severity 

---

api/alerts_details_integrations.go
api/cloud_accounts.go
api/container_registries.go
cli/cmd/container_registry_test.go

Both, inline/proxy scanner integrations don’t have a `state`
object at all- so we will hard code them to be always `Ok`.
Added tests.
https://lacework.atlassian.net/browse/LINK-1361

fix(cli): inline/proxy scanner Ok state

---

cli/cmd/lql_show.go
cli/cmd/lql_sources.go
cli/cmd/lql_sources_internal_test.go
cli/cmd/policy.go
cli/cmd/policy_internal_test.go
integration/policy_test.go

Output improvement for a few query and policy commands. 
* refactor(cli): improve `policy list` command output
* refactor(cli): improve `policy show` command output
* feat(cli): display query inside `policy show` command
* refactor(cli): `query list-sources` and `query show-source` output
Look at the before and after and suggest any modification.
Main change here is the removal of the Query ID since it is way too long.
Main change here is the display of the Query Text.
And when a query is configured into the policy, we automatically display it.
Major refactor here is that we are printing a single column table and inside we are printing both, the datasource name and the description. This is the best way I can think of to print such loooong strings (150+ chars).
No big change here, just …

[CLI] Query/Policy Output Improvements

---

cli/cmd/component.go
cli/cmd/component_args.go
cli/cmd/component_args_test.go

A bug in the component arg parser makes `lacework sca -v` hang.
What `lacework sca -v` is supposed to do is print the version (where "supposed to do" means what cobra is trying to do.). This isn't done correctly either.
There's a unit test to check that -v is parsed correctly.    And run by hand to verify that `lacework sca -v` prints the version of the sca command.
GROW-1438

fix(cdk): handle -v flag for components

---

cli/cmd/component.go
lwcomponent/component.go

Quick nitpicks for `component` commands.
It now shows colors for the Status and has a few missing carriage returns.

style(cli): fix 'component' commands formatting

---

cli/cmd/generate_azure.go
integration/azure_generation_test.go
integration/test_resources/help/generate_cloud-account_azure
lwgenerate/azure/azure.go
lwgenerate/azure/azure_test.go
lwgenerate/azure/test-data/config-with-azurerm-subscription.tf

`lacework generate cloud-account azure` does not currently make use of subscription_id in the azurerm provider block. The azure resources will always use the default subscription. 
This change adds a new SubscriptionID var to GenerateAzureTfConfigurationArgs. 
The subscription_id can optionally be set in the interactive prompt or with the flag `--subscription_id`. The Default behaviour is the same as current behaviour with subscription_id unset.
Manual:
Tests:
https://lacework.atlassian.net/browse/GROW-1444

fix: add missing subscription_id from azurerm block

---

cli/cmd/root.go
integration/completion_unix_test.go
integration/completion_windows_test.go

We don't need to have authentication for any `lacework completion` command.
Ran this and it worked.
```
HOME=/tmp lacework completion bash
```
Also, added integration tests.
Closes https://github.com/lacework/go-sdk/issues/1182

fix(cli): avoid auth for completion cmds

---

README.md
cli/README.md

Add chocolatey install cmd to readme
`choco install lacework-cli`
https://community.chocolatey.org/packages/lacework-cli#install

docs: update install methods on Readme with chocolatey cmd

---

cli/cmd/honeyvent.go
cli/cmd/honeyvent_test.go

Honeycomb event flags are now only the flags
Unit testing and manual
https://lacework.atlassian.net/browse/GROW-1436

fix: honeyvent flag values

---

cli/cmd/vuln_host_scan_package_manifest.go
cli/cmd/vuln_host_scan_package_manifest_test.go

This change removes "GOOD" results from `lacework vuln host scan-pkg-manifest` and only shows "VULNERABLE"
Tests:

fix(cli): vuln host scan-pkg-manifest only show 'VULNERABLE' results

---

go.mod
go.sum
lwcomponent/component.go
vendor/github.com/cenkalti/backoff/v4/.gitignore
vendor/github.com/cenkalti/backoff/v4/LICENSE
vendor/github.com/cenkalti/backoff/v4/README.md
vendor/github.com/cenkalti/backoff/v4/backoff.go
vendor/github.com/cenkalti/backoff/v4/context.go
vendor/github.com/cenkalti/backoff/v4/exponential.go
vendor/github.com/cenkalti/backoff/v4/retry.go
vendor/github.com/cenkalti/backoff/v4/ticker.go
vendor/github.com/cenkalti/backoff/v4/timer.go
vendor/github.com/cenkalti/backoff/v4/tries.go
vendor/modules.txt

With SAST and SCA getting increasing usage internally we've stated to hit some API rate limits at installation time. We've already put a mitigation place by starting to cache the installed components in the GitHub Actions cache (https://github.com/lacework/code-security-action/pull/44), but ideally we'd like the installation to be a bit more robust to occasional network glitches and/or rate limits being hit. I suggest adding the retrying code in this PR to our call to the component listing end-point. There's probably more places we could have retrying, but this is pretty much the only place I've actually had reports of failures happening, so let's stick to just here for now.
cc. @lacework/codesec-action

feat: Add retrying to component listing

---

cli/cmd/vuln_host_list_hosts.go
integration/host_vulnerability_test.go

Showing vulnerabilities that have been 'Fixed' is confusing customers,
this change is filtering them out so we no longer show them.
We have a separate ticket to add custom time ranges https://lacework.atlassian.net/browse/GROW-1485
Ran test manually and added a test that checks that we no longer show the `Fixed` status.
https://lacework.atlassian.net/browse/LINK-1387

fix(cli): filter 'Fixed' host vulnerabilities

---

api/api.go
api/reports.go
api/reports_aws.go
api/reports_azure.go
api/reports_gcp.go
api/reports_test.go
cli/cmd/compliance.go
cli/cmd/compliance_aws.go
cli/cmd/compliance_azure.go
cli/cmd/compliance_gcp.go
integration/compliance_aws_test.go
integration/test_resources/help/compliance_aws_get-report
integration/test_resources/help/compliance_azure_get-report
integration/test_resources/help/compliance_google_get-report

This change adds a new flag to `lacework compliance <cloud>` cmd to allow fetching reports by report name instead of report type.
Usage:
`lacework compliance aws get-report <account_id>  --report_name 'AWS CSA CCM 4.0.5' `
`--report_name` cannot be used with `--type` flag.
Attempting to use both flags will return 
`ERROR '--type' and '--report_name' flags cannot be used together`
The default behaviour when neither `--report_name` or `--type` is specified will remain the same i.e the type parameter is used to fetch reports.
TODO:
TODO:
https://lacework.atlassian.net/browse/GROW-1404

feat(cli): support fetching AWS compliance reports by 'report_name'

---

api/cloud_accounts_gcp_at.go
api/cloud_accounts_gcp_at_test.go
api/cloud_accounts_gcp_cfg.go
api/cloud_accounts_gcp_cfg_test.go

When doing `PATCH` requests, we should not send empty fields for both, the private key and the private key id, if not, users will get a message similar to:
```
[400] Error validating integration. Please verify the configuration details entered.
```
This change avoids sending an empty GCP Private Key ID
Added unit test and run some Terraform and CLI commands to validate.
https://lacework.zendesk.com/agent/tickets/11161

fix(api): avoid sending empty GCP private_key_id

---

Makefile
api/api.go
api/report_definitions_test.go
api/reports_definitions.go
cli/cmd/report_definitions.go
cli/cmd/report_definitions_create.go
cli/cmd/report_definitions_test.go
cli/cmd/report_definitions_update.go
integration/report_definitions_update_test.go
integration/test_resources/help/report-definition_update

Support updating existing custom report definition from the CLI with the new command:
`lacework report-definitions update`
Testing Prereq:
Only custom report definitions can be updated. System created definitions cannot.
Either create a new custom report definition or use `F5B4F0B0124F4C9E3547DCC6E62A8C6D774E45E9610999FE5FA517EF` on tech-ally
Manual
Tests
https://lacework.atlassian.net/browse/GROW-1475

feat(cli): new report-definitions update command

---

api/v2_vulnerabilities.go
cli/cmd/vuln_html.go
cli/cmd/vuln_html_test.go

Since https://github.com/lacework/go-sdk/pull/1025 the generation of static HTML output has been broken, this change fixes it so that it renders like it was before.
Executed the command manually and verified the generated HTML output.
```
lacework vulnerability ctr show sha256:4f299b4fc8f7b7daf411401140a0b15c1b29f5ddb547d21f4005093c566c8a98 --html
CONTAINER IMAGE DETAILS                                          VULNERABILITIES
------------------------------------------------------------------------------------------+---------------------------------
ID          sha256:6cf101feaea119e21c340a4984a8a710f7720280d39708a469ffd68c5b539324       SEVERITY   COUNT   FIXABLE
Digest      sha256:4f299b4fc8f7b7daf411401140a0b15c1b29f5ddb547d21f4005093c566c8a98     -----------+-------+---------- …
```

fix(cli): HTML generation of vuln assessment

---

api/api.go
api/report_definitions_test.go
api/reports_definitions.go
cli/cmd/report_definitions.go
cli/cmd/report_definitions_diff.go
cli/cmd/report_definitions_revert.go
cli/cmd/report_definitions_test.go
integration/report_definitions_test.go
integration/test_resources/help/report-definition
integration/test_resources/help/report-definition_diff
integration/test_resources/help/report-definition_revert

Changes in this PR:
Support new cmd `lacework report-definitions revert <id> <version>`
Support new cmd `lacework report-definitions diff <id> <version> <version>`
Add new `--version` flag to `lacework report-definitions show` cmd: 
`lacework report-definitions show <id> --version <version>`
`lacework report-definitions show <id> --version all`
Manual
Tests
https://lacework.atlassian.net/browse/GROW-1487

feat(cli): new report-definitions revert command

---

cli/cmd/agent.go
cli/cmd/agent_aws-install_ec2ic.go
cli/cmd/agent_aws-install_ec2ssh.go
cli/cmd/agent_aws-install_ec2ssm.go
cli/cmd/agent_gcp-install-osl.go
integration/test_resources/help/agent_aws-install_ec2ic
integration/test_resources/help/agent_aws-install_ec2ssh
integration/test_resources/help/agent_aws-install_ec2ssm
integration/test_resources/help/agent_gcp-install_osl

This commit adds a new CLI flag called `server_url` to:
* `aws-install ec2ic`
* `aws-install ec2ssh`
* `aws-install ec2ssm`
* `gcp-install osl`
`server_url` allows the user to set the server URL that their agents
will connect to after deployment through the CLI.
This commit also updates the integration help texts with the new flag
and instructions for use.
Fixes RAIN-53798
New integration tests for all CTF commands at https://github.com/lacework/agent/pull/2103
https://lacework.atlassian.net/browse/RAIN-53798

feat(cli): add `server_url` flag for CTF commands

---

integration/alert_list_test.go
lwtime/nattime.go
lwtime/nattime_internal_test.go
lwtime/reltime.go
lwtime/reltime_internal_test.go
lwtime/reltime_test.go

Avoid issues with `now` ahead of current time when using natural and relative language flags.
When calculating the local time `now` and submitting it to the Lacework APIs, the clock on some
computers could have an offset (they could be ahead of time) with the Lacework platform, we have
seen a max of 1-2s offset so, we have decided to default `now` to `-2s` to avoid these issues.
We have also made this clock offset configurable, users can use the environment variable `LW_CLOCK_OFFSET`
to customize this parameter or put it back to the previous default (`-0s`).
Manual
Plus unit and integrations tests.
https://lacework.atlassian.net/browse/LINK-1507

fix: adjust endtime for natural time

---

api/_examples/feature-flags/main.go
api/api.go
api/feature_flags.go
api/feature_flags_test.go
api/v2.go

**Summary**
This PR adds support in the Go SDK for finding enabled feature flags matching a certain prefix. This exploits the end-point described in https://lacework.atlassian.net/wiki/spaces/ENG/pages/2805563571/New+API+end-point+for+feature+flagging 
**How did you test this change?**
New unit tests that call a mock API. Also, manual end-to-end testing against one of our development instances, see below
This PR will not merged before https://github.com/lacework/rainbow/pull/11782
**Issue**
https://lacework.atlassian.net/browse/COD-518

feat(api): Implement feature flagging endpoint

---

integration/alert_list_test.go
integration/version_test.go

When moving the daily version output from STDOUT to STDERR (https://github.com/lacework/go-sdk/pull/1207) we
forgot to update these tests that are blocking the release https://github.com/lacework/go-sdk/pull/1223
Ran the integration tests with and without the suffix `-dev` in the `VERSION` file
N/A

test(cli): fix daily version integration test

---

cli/cmd/lql.go

When running `lacework lql run` without arguments, we open an editor for the user
to write the query live, this change is starting new queries to run with the default one
that looks similar to:
```yaml
queryId: YourQueryID
queryText: |-
{
source {
--- Select a datasource. To list all available datasources, use 'lacework query sources'.
}
filter {
--- Add query filter(s), if any. If not, remove this block.
}
return {
--- List fields to return from the selected source. Use 'lacework query describe <datasource>'.
}
}
```
This functionality is being tested with;
- https://github.com/lacework/go-sdk/blob/main/integration/lql_create_unix_test.go#L32 
We are just enabling the same functionality from `lacework lql create` to `lacework lql run`.
N/A

feat(cli): enable default query for 'lql run' cmd

---

api/reports.go
api/reports_aws.go
api/reports_azure.go
api/reports_gcp.go
cli/cmd/compliance.go
cli/cmd/compliance_aws.go
cli/cmd/compliance_azure.go
cli/cmd/compliance_gcp.go
cli/cmd/compliance_test.go
integration/compliance_aws_test.go

We currently have three different formats (maybe more) of Compliance recommendation IDs.
* `"REC_ID": "AWS_CIS_1_3"`
* `"REC_ID": "1.10"`
* `"REC_ID": "lacework-global-76"`
If a user tries to access the resources of the second and third format, the CLI will show the following error:
```
$ lacework compliance aws get-report <AccountID> --details 1.10
ERROR
'1.10' is not a valid recommendation id
```
This change fixes that problem by removing the regex check.
Added tests and ran a few commands. All worked out well.
Jira https://lacework.atlassian.net/browse/RAIN-45227

fix(cli): allow multiple recommendation ID types

---

cli/cmd/generate_aws.go
cli/cmd/generate_aws_eks_audit.go

Not all AWS region are supported.  The `cn` region is not supported by Lacework ingestion.
https://github.com/lacework/services/pull/12158

fix: unsupported aws region

---

cli/cmd/vuln_container_show_assessments.go
cli/cmd/vuln_container_test.go

Remove filtering from CSV output
Tests
https://lacework.atlassian.net/browse/GROW-1490

refactor: do not filter csv output for vuln ctr show

---

cli/cmd/vuln_host_scan_package_manifest.go
cli/cmd/vuln_host_scan_package_manifest_test.go

The `VulnerabilityCounts()` used in the fail_on_severity evaluation are using the unfiltered results, eg. when vuln status is 'GOOD'. This change passes the response as a pointer so results are filtered when VulnerabilityCounts() is called.
Tests
Manual
Run `lacework vuln host scan-pkg-manifest` against manifest from amzn2-ami-hvm-2.0.20230320.0-x86_64-gp2 
* see manifest.json on LINK-1587 attachments
https://lacework.atlassian.net/browse/LINK-1587

fix: vuln host scan-pkg-manifest fail_on_severity

---

api/cloud_accounts_aws_sidekick_org.go
api/cloud_accounts_aws_sidekick_org_test.go
api/cloud_accounts_gcp_sidekick.go
api/cloud_accounts_gcp_sidekick_test.go

This is part of a new feature that will allow Agentless Workload Scanning customers take advantage of Lacework Organizations. This enables customers with an organization deployment (on either GCP or AWS) to add an optional account mapping file which we handle on the back end to direct data to specific Lacework sub-accounts in accordance with the file.
I verified this via unit testing (see added tests)
https://lacework.atlassian.net/browse/RAIN-54797

feat (RAIN-54797) Add account mapping for aws and gcp sidekick in api

---

cli/cmd/generate_aws.go
cli/docs/lacework_generate_cloud-account_aws.md
integration/aws_generation_test.go
integration/test_resources/help/generate_cloud-account_aws
lwgenerate/aws/aws.go
lwgenerate/aws/aws_test.go

Adding the `--use_s3_bucket_notification` flag to the generate AWS command.
- unit testing
- integration testing
- manual testing
https://lacework.atlassian.net/browse/GROW-1525

feat: CloudTrail S3 bucket notifications

---

api/cloud_accounts_aws_sidekick.go
api/cloud_accounts_aws_sidekick_org.go
api/cloud_accounts_gcp_sidekick.go

This is part of the work of multi-volume (secondary volume) and stopped instances scanning features for agentless workload scanning. We are finishing up the feature by adding a toggle / boolean for integrations to indicate if they want to turn on Multi-Volume scanning and/or Stopped Instances scanning. This is handled on the backend (in sidekick) to "turn on" the feature if the boolean is set to true. 
Tested via unit tests
https://lacework.atlassian.net/browse/RAIN-54831

add ScanMultiVolume bool field to Agentless integrations

---

cli/cmd/agent.go
cli/cmd/agent_aws-install_ec2ic.go
cli/cmd/agent_aws-install_ec2ssh.go
cli/cmd/agent_aws-install_ec2ssm.go
cli/cmd/aws.go
integration/test_resources/help/agent_aws-install_ec2ic
integration/test_resources/help/agent_aws-install_ec2ssh
integration/test_resources/help/agent_aws-install_ec2ssm
lwrunner/awsrunner.go

This commit adds a new CLI flag to the
`lacework agent aws-install <method>` command called
`credential_profile`. This flag allows the user to specify an AWS
credential profile for `aws-install` to use if the `default` profile is
not appropriate.
This flag applies for:
* `aws-install ec2ic`
* `aws-install ec2ssh`
* `aws-install ec2ssm`
Fixes RAIN-58289
A customer is asking for this as they are unable to use the `default` profile (https://lacework.slack.com/archives/CGW13JCKV/p1683741597786639)
Tested locally with a dry run of `ec2ssm` and a different profile than `default`. Not going to add this case to the integration tests as they do not support using different profiles
https://lacework.atlassian.net/browse/RAIN-58289

feat(aws-install): add `credential_profile` flag

---

api/v2_vulnerabilities.go
cli/cmd/vuln_host_show_assessment.go
cli/cmd/vuln_host_show_assessment_test.go
cli/cmd/vuln_host_test.go

The new APIv2 for host vulnerabilities introduced the concept (exposed) of evaluation GUIDs,
this id is used to group all vulnerabilities from a single evaluation (assessment).
Before this change, we were ignoring this field and therefore, we could end up with two problems:
1. Display more vulnerabilities from other evaluations
2. Display less vulnerabilities since we were NOT reading all pages and, we were looking only to a
single day (`-24h`) of data
This PR fixes a number of issues by:
* It now parses the `EvalGUID` in the `VulnerabilityHost` struct
* The `VulnerabilityCounts()` func now removes duplicates before counting
* The CLI cmd now searching for latest host evaluation first
* Then, using the `EvalGUID` the CLI fetches vulnerabilities that match
* Finally, we look at the past 7 …

fix(cli): Inconsistent results from host vuln show

---

cli/cmd/cloud_account.go
cli/cmd/integration_oci.go

This PR adds an option for OCI integration to the `lacework cloud-account create` command:
as well as the survey questions necessary to set up integration with an OCI cloud account:
I did a manual smoke test. I ran the Lacework binary with the debug option enabled (`./lacework-cli-darwin-arm64 cloud-account create --profile dev5 --debug`) and stepped through the interactive survey questions. Then I checked the debug logs to see if we made a well-formed request to the Lacework API:
```
{"level":"debug","ts":"2023-06-23T10:02:59Z","caller":"api/http.go:92","msg":"request","id":"42fd0ec1d79e3c03","account":"dev5.dev5.corp","method":"POST","url":"https://dev5.dev5.corp.lacework.net","endpoint":"/api/v2/CloudAccounts","headers":{"Accept":["application/json"],"Authorization":["_be18a8f0df465e702 …
```

feat(cli): cloud-account: oci integration

---

cli/cmd/component_dev.go

The interactive prompt for the command lacework component dev <name> will fail for GO/Python if required tools are not installed.  We need a pre-flight check to ensure that the requirements are met.
- Use `exec.LookPath` to check if a tool is installed.
- For Go scaffolding, `go` is required
- For Python scaffolding, `python3` and `shiv` are required.
https://lacework.atlassian.net/browse/GROW-1600

chore(GROW-1600): lacework component dev preflight check

---

cli/cmd/honeyvent.go
cli/cmd/honeyvent_test.go
cli/cmd/telemetry.go
cli/cmd/telemetry_test.go

Over in the Code Security team we want to add some observability in environments where we have the Lacework CLI and are running a bunch of command in sequence as well as doing some things outside of the CLI. We would like to land the two enhancements in this PR to support this:
- We now read a variable `LACEWORK_CONTEXT_ID` and report this. This will allow us to link up different invocations of the CLI into one unique context for the whole sequence of commands.
- We now support a hidden command `lacework telemetry upload` which accepts a JSON blob of telemetry to upload. We'll use this to report additional telemetry from the bits of our code running outside the CLI.
- One automated test was modified to check the new behaviour, and a new one was also added.
- I did manual end-to-end …

feat(COD-1255): Enhancements to how telemetry can be used

---

api/client.go

The newClient option `withTransport`, which allows you to specify a custom http client transport argument, has an overly strict type definition ([`http.Transport`](https://pkg.go.dev/net/http#Transport)). It uses the argument to set the `transport` field of the [`http.Client`](https://pkg.go.dev/net/http#Client) owned by `api.Client`. But the http.Client.transport field actually has a type of [`http.RoundTripper`](https://pkg.go.dev/net/http#RoundTripper) (an interface) and not `http.Transport` (a struct type that implements the RoundTripper interface). The naming does seem a bit misleading.
The result is that you can only pass a very limited set of arguments to `withTransport`. In my case, I'd like to be able to pass an instance of `httpmock.MockTransport` to use in automated tests. But …

fix(api): fix overly narrow type in withTransport argument

---

api/reports_aws.go
api/reports_azure.go
api/reports_gcp.go
cli/cmd/compliance_aws.go
cli/cmd/compliance_azure.go
cli/cmd/compliance_gcp.go
integration/compliance_aws_test.go
integration/compliance_azure_test.go
integration/compliance_gcp_test.go
integration/test_resources/help/compliance_aws_get-report
integration/test_resources/help/compliance_azure_get-report
integration/test_resources/help/compliance_google_get-report

This change
- Changes the default parameters for `compliance aws|az|gcp get-report` to use `report_name` over `type`
- Fix report type not being updated in --csv output
- Mark the `--type` flag as deprecated
Report names are discoverable via `lacework report-definitions list` but types are not. This makes fetching reports by name preferable. Validation can be performed by fetching a valid list of reports from the api.  New and custom reports can be discovered.
https://lacework.atlassian.net/browse/LINK-1816

feat: default compliance report to use report_name

---

cli/cmd/compliance.go
cli/cmd/compliance_aws.go
cli/cmd/compliance_azure.go
cli/cmd/compliance_gcp.go
integration/compliance_aws_test.go
integration/compliance_gcp_test.go

The platform today only returns a list of resources that are in violation, that means, “non-compliant” resources. We currently do not return the list of resources that are “compliant”, “requires-manual-assessment” or “could-not-assess”
- For those cases our CSV output will only show the number of resources.
Added integration tests and ran a few commands locally on my workstation.
https://lacework.atlassian.net/browse/GROW-2316
https://lacework.atlassian.net/browse/LINK-1864

fix(cli): compliance get-report blank CSV output

---

cli/cmd/generate_aws.go
cli/cmd/generate_aws_eks_audit.go

Update the AWS region regex with the values in https://github.com/lacework/rainbow/pull/12821/files.
Excluding:
```
'us-gov-east-1',
'us-gov-west-1',
'aws-global',
'aws-us-gov-global',
```
Manually with the `lacework generate` command.
https://lacework.atlassian.net/browse/GROW-2289

chore(GROW-2289): Update AWS region regex

---

lwgenerate/_examples/hcl/main.go
lwgenerate/hcl.go
lwgenerate/hcl_test.go

During HCL generation there's the need to support some more complex module attributes:
e.g.,
```
list(object({
value1 = string
mapping = list(object({
thing1 = string
thing2     = list(string)
}))
}))
```
Prior to this commit, using nested data for a module attribute didn't work correctly. This commit adds support for `map[string]interface{}` and `[]map[string]interface{}`. Because the same set of functions are used for converting Go types to cty.Value(s), any block attribute should now be able to use these data types.
See tests.

feat(lwgenerate): support complex/nested module attribute values

---

api/_examples/alert-rules/main.go
api/alert_rules.go
api/alert_rules_test.go

Add support for missing fields in the alert_rules api
In the EventCategory property the values Registry, SystemCall, HostVulnerability & ContainerVulnerability
The Sources property has been added with the values Agent, Aws, Azure, Gcp, K8s
The AlertCategory property has been added with the values Policy, Anomaly, Composite
https://lacework.atlassian.net/browse/GROW-2326

feat(api): support new fields in alert_rules api

---

api/alert_rules.go
cli/cmd/alert_rules.go
integration/alert_rules_test.go

Go JSON `omitempty` drops the field if provided with an empty array `[]`.
- unit test
- integration test
- cli command
- Terraform create+update alert_rules
https://lacework.atlassian.net/browse/GROW-2361

fix: alert rules empty arrays

---

api/_examples/resource-groups/main.go
api/feature_flags.go
api/resource_groups.go
api/resource_groups_aws.go
api/resource_groups_azure.go
api/resource_groups_container.go
api/resource_groups_gcp.go
api/resource_groups_lw_account.go
api/resource_groups_machine.go
api/resource_groups_v2.go
api/resource_groups_version_service.go
api/v2.go
cli/cmd/resource_group_v2.go
cli/cmd/resource_groups.go

Adds support for the CRUD operations for Resource Groups V2.
1. Updated example code for resource groups and ensured it passed.
2. Manually ran the command line. See pictures below
3. ran all the commands listed to do before publishing a PR
List Resource Groups
Create an AWS RGv2
Create an AWS RGv1
List showing the RGv2 that was created
Delete the RGv1 created earlier
Calling GET for both an V1 and V2 resource
https://lacework.atlassian.net/browse/CAD-360

feat(CAD-360): Support Resource Group v2 in CLI

---

lwgenerate/constants.go
lwgenerate/oci/oci.go
lwgenerate/oci/oci_test.go

This PR adds a package under `lwgenerate` to generate Terraform code for OCI integration. This is the first stop towards adding a `lacework generate cloud-account oci` command that can be used to generate Terraform code to integrate Lacework with OCI using the Lacework CLI.
There are accompanying unit tests making sure that the output is as expected. I also used the output to create an actual Lacework integration to an OCI tenant.
[SPM-902](https://lacework.atlassian.net/browse/SPM-902)
[SPM-902]: https://lacework.atlassian.net/browse/SPM-902?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add oci package to lwgenerate

---

api/resource_groups_v2.go
api/resource_groups_version_service.go

The Update API is not called from the CLI, I found an issue due to forgetting to implement an interface for `ResourceGroupWithQuery` causing the Update conversion of the object to `ResourceGroup` interface to fail. This was caught during development of the terraform provider
Made these exact same changes in the terraform provider locally and was able to run an integration test that creates, updates, deletes a resource group successfully.
https://lacework.atlassian.net/browse/CAD-125

fix(CAD-125): Fix broken update api in RGv2

---

api/v2_vulnerabilities.go
cli/cmd/vuln_container_scan.go

- For `lacework vulnerability container scan ...`, if the `fail_on_severity` or `fail_on_fixable` flag is provided, fail the CLI as expected.
- Filter out unknown severities when finding out the highest severity of a container. 
Verify container scan:
- Run `lacework vuln container scan index.docker.io techallylw/test-cli-dirty latest --poll`
- Should not fail
- Run `lacework vuln container scan index.docker.io techallylw/test-cli-dirty latest --poll --fail_on_severity low`
- Should fail
Verify container show:
- Run `lacework vuln ctr show sha256:a65572164cb78c4d04f57bd66201c775e2dab08fce394806a03a933c5daf9e48`
- Should not fail
- Run `lacework vuln ctr show sha256:a65572164cb78c4d04f57bd66201c775e2dab08fce394806a03a933c5daf9e48 --fail_on_severity low`
- Should fail

fix(cli): respect fail flags in vulnerability container scan

---

cli/vagrant/windows-10/Vagrantfile
cli/vagrant/windows-10/provision.ps1

Vagrant 2.3.7 has some issues (at a minimum on macos+intel)
1.  Pin vagrant to known working version
2. Automatically pass CI environment variables to the guest
3. Add a bit of vram so that the virtualbox window can be resized
https://github.com/lacework/go-sdk/assets/7862144/37e43ae8-7db5-4a96-a259-d89b183d8bca
https://lacework.atlassian.net/browse/GROW-2396

 chore(vagrant): enhancing windows vagrant experience 

---

integration/container_vulnerability_test.go

Add integration tests to verify container scan command fails correctly with the fail_on_severity and fail_on_fixable
run `make integration regex=TestContainerVulnerability`

test: add integration tests for container scan with fail on flags

---

integration/generate_oci_test.go

Fix for https://g.codefresh.io/build/64f84da90f189767780d7076.  Need to exclude generation tests from windows integration testing.
https://g.codefresh.io/build/64f84da90f189767780d7076

chore: OCI test build tag

---

api/_examples/alert-rules/main.go
api/alert_rules.go
api/alert_rules_test.go

The alert sources field should be `source` instead of `sources`
Run `make test`
https://lacework.atlassian.net/browse/GROW-2413

fix(api): fix alert rules source field

---

api/api.go
api/cloud_accounts.go
api/cloud_accounts_gcp_at.go
api/cloud_accounts_test.go
cli/cmd/cloud_account.go
integration/test_resources/help/cloud-account
integration/test_resources/help/cloud-account_migrate

This PR adds a new command `cloud-account migrate <INTG_GUID>` that will be used for the GPCv2 migration process when we go GA. Customers will use this command to mark the provided integration for migration. The CLI will call a [new api server endpoint](https://github.com/lacework/rainbow/pull/13814) which will handle the backend. 
- Added unit test.
- Tested end to end with the new API-server endpoint in `dev3`.
[RAIN-70441](https://lacework.atlassian.net/browse/RAIN-70441)
[RAIN-70441]: https://lacework.atlassian.net/browse/RAIN-70441?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(RAIN-70441): add CLI command to support migration

---

cli/cmd/version.go

`lacework version` is failing non deterministically, see https://github.com/lacework/code-security-action/actions/runs/5794782714/job/15707673444
This PR fails more silently,  by just logging an error instead of exiting.
Test: we are not exiting anymore, so it should just work. No need for tests as it is an easy change.
[
](https://lacework.atlassian.net/browse/COD-1559)

fix(cli): Failures in Lacework CLI update checking

---

api/_examples/alert-rules/main.go
api/alert_rules.go
api/alert_rules_test.go

The alert source AWS should be all uppercase 
run `make test`
https://github.com/lacework/terraform-provider-lacework/issues/554

fix(api): change alert_source Aws to AWS

---

api/alert_rules.go

The alert source GCP should be uppercase
run `make test`
https://github.com/lacework/terraform-provider-lacework/issues/554

fix(GROW-2435): change alert source Gcp to GCP

---

api/alerts_details_integrations_test.go
api/http.go
api/http_test.go

By using the `UseNumber()` function of the decoder https://pkg.go.dev/encoding/json#Decoder.UseNumber we are causing the Decoder to unmarshal a number into an interface{} as a Number instead of as a float64.
This fixes the problem when the CLI returns the raw response of long numbers like the `mid`.
Ran `lacework api post /api/v2/Entities/Machines/search -d '{}'` and verified that the `mid` is returning
without rounding it. 
https://lacework.atlassian.net/browse/GROW-2459

fix(api): avoid round numbers in responses

---

lwcomponent/component.go
lwcomponent/component_internal_test.go
lwcomponent/http.go
lwcomponent/http_test.go
lwcomponent/minisign_internal_test.go

For the download of components, use a default timeout of 30 seconds.  When timeout errors are returned, retry twice.
Local manual testing
https://lacework.atlassian.net/browse/GROW-2460

fix: component download timeout retry

---

lwcomponent/component.go

The SAST component is over 200mb in size and requires at least 1 minute to download.  Increasing the component download timeout to 5 minutes.
Local manual

fix: increase component download timeout to 5m

---

lwcomponent/component.go
lwcomponent/http.go
lwcomponent/http_test.go

The line `io.Copy(file, resp.Body)` streams HTTP response data to the file, at this stage we have an active HTTP connection and a timeout will interrupt us there.
This change groups the `client.Get` with the `io.Copy`.  Hardcoding component timeout values.
local unit testing

fix: component download

---

api/component_data.go
api/component_data_test.go

Add the parameter to specify the url type for sast tables
We need to prepare the API for uploading sast tables.
Unit tests
https://lacework.atlassian.net/browse/COD-1156

Support sast tables in cds

---

cli/cmd/component.go

When a component is run, check whether an available is available, and if yes report it.
Manually, e.g.
```
(⎈|lacework.teleport.sh-lacework-devtest-dev5:N/A)➜  cli git:(GROW-2470) ✗ go build . && ./cli sca 
sca v0.0.74 available: to update, run `lacework component install sca`
Lacework SCA (Software Component Analysis)
...
```

feat(cli): Components daily version check

---

cli/cmd/component.go
lwcomponent/catalog.go

Lacework minisign library signs a SHA256 hash of the data.
manual
```
> /usr/local/bin/lacework components install component-example
[✓] Component component-example found
[✓] Component component-example staged
[✓] Component signature verified
[✓] Component version 0.7.30 installed
```
https://lacework.atlassian.net/browse/GROW-2473

fix: CDK v1 signature verify

---

lwcomponent/catalog.go

1) No components returned from the API would lead to a panic.
Fix:  safe array access
2) No `~/.config/lacework/components` directory would lead to an error
Fix: create the dir if it doesn't exist
Local manual testing

fix: CDK bugs

---

cli/cmd/lql.go
integration/test_resources/help/query_run

Adds a flag when running `lacework query run` to create an empty file in `$EDITOR`, rather than using the default template.
This is a useful feature for policy engineering work, as when we have a draft query already created, that we want to quickly test, it allows to just paste into an empty file and run the query.
All changes tested locally using the testing procedure defined via the `make` rules.
Also verified that the resulting `lacework` binary behaves correctly using the new flag.
N/A

feat(lql): add option to generate empty lql file

---

scripts/chocolatey/build/lacework-cli.nuspec

When we upgraded to go version `1.21`, Chocolatey started flagging our binaries:
https://community.chocolatey.org/packages/lacework-cli#virus
This is a common false-positive so this PR is adding this "banner" to explain:
---
Since the release of the Lacework CLI version `1.30.0` we noticed that the virus scan reports positive findings. We
have analyzed the generated binaries and we have not found any virus.
This is a **common false-positive** in the Golang community for Windows binaries. For details, go to https://golang.org/doc/faq#virus
---
* https://github.com/golang/go/issues/60828
* https://github.com/golang/go/issues/61339
* https://github.com/golang/go/issues/47874
* https://github.com/golang/go/issues/47807

chore(cli): add info about false-positive virus on Windows

---

cli/cmd/component_dev.go

Apparently, Python doesn't allow `-` in library names. https://github.com/python-poetry/poetry/issues/5975
This fixes the problem by removing the hyphens, not that, we are not changing the name of the CDK component since that is packaged with `pyinstall` via the `tool.poe.tasks`
Created a component with `-`
```
➜  ~ lacework component list
STATUS                 NAME              VERSION                                   DESCRIPTION
-------------------+-------------------------+-----------+-----------------------------------------------------------------------------
Update Available   sca                       0.0.73      Software Component Analysis
Installed          remediate                 0.5.0       A tool to isolate and remediate resources
Not Installed      chronicle-alert-channel …
```

fix(scaffolding): Python components can't have '-'

---

Makefile
api/resource_groups.go
api/resource_groups_v2.go
cli/cmd/resource_groups.go
integration/context/ctx.toml
integration/resource_groups_test.go

Add support for new resource group type `OCI`
- Tested manually using dev7
- Introduced resource-group integration tests
https://lacework.atlassian.net/browse/CAD-416

feat(resource-groups): add support for OCI

---

lwcomponent/api_info.go
lwcomponent/api_info_test.go
lwcomponent/catalog.go
lwcomponent/catalog_test.go
lwcomponent/cdk_component.go
lwcomponent/cdk_component_test.go
lwcomponent/status.go

- For the install and update command, if the specified version is tainted, then the command will fail by default. Nothing is changed.
- For the list and show command, set the component status to "Tainted", displayed as "Tainted(Please update)", to prompt users to update.
lacework components list
lacework components show component-example
https://lacework.atlassian.net/browse/GROW-2367

feat: check if cdk component is tainted

---

api/_templates/resource_groups/aws.json
api/_templates/resource_groups/azure.json
api/_templates/resource_groups/container.json
api/_templates/resource_groups/gcp.json
api/_templates/resource_groups/machine.json
api/_templates/resource_groups/oci.json
api/resource_groups.go
api/resource_groups_v2.go
api/resource_groups_version_service.go
cli/cmd/resource_group_v2.go
integration/resource_groups_test.go

This pull-request adds a template for each RGv2 type (i.e. `AWS`, `GCP`, `AZURE`, `OCI`, `MACHINE`, `CONTAINER`).  This makes it easier for our customers to create resource groups via the CLI+Editor
- Manually
- Augmented delete integration test to iterate through each type
https://lacework.atlassian.net/browse/GROW-2489

feat(resource-groups): add per-group-type templates

---

cli/cmd/component_dev.go

The python pyinstaller build command was creating the component binary in subdirectory, not the component root directory. This prevented the lacework cli from executing the component. 
1. compiled the lacework cli
2.  tested the creation of a new python component with scaffolding 
3. tested that the cli could execute the component after build
https://lacework.atlassian.net/browse/GROW-2491

fix(cdk): place Python component binary in component root

---

api/cloud_accounts_aws_sidekick.go
api/cloud_accounts_aws_sidekick_org.go
api/cloud_accounts_aws_sidekick_org_test.go
api/cloud_accounts_aws_sidekick_test.go

In order to go fully-GA on the short-lived feature for AWS for Agentless Workload scanning, we need to also update the terraform to have a field for short-lived instances. I've added the field to both AWLS and AWLS Org integration types. This feature is not currently available on GCP. 
Tested via integration tests, added additional field in the integration tests.
https://lacework.atlassian.net/browse/RAIN-71760

add short lived instance field in agentless data structs

---

cli/cmd/cdk.go

Components might need to know the loaded profile to build other CLI commands,
this PR exposes the profile via environment variables.
https://lacework.atlassian.net/l/cp/GJYdDTXH
Used the `preflight` component.
N/A

feat(cdk): expose LW_PROFILE to components

---

api/_examples/alert-rules/main.go
api/alert_rules.go
api/alert_rules_test.go
cli/cmd/alert_rules.go
integration/alert_rules_test.go
integration/test_resources/help/alert-rule

- `eventCategory` is deprecated. A new field `subCategory` is added to the AlertRules API in [#14700](https://github.com/lacework/rainbow/pull/14700).
- There are 3 eventCategory values that are not in sync with subCategories: `App`, `Cloud` and `K8sActivity`. To support them for existing users, they are converted to corresponding subCategory values.
`make test`
https://lacework.atlassian.net/browse/GROW-2490

chore: use AlertRule subCategory in stead of eventCategory

---

lwgenerate/azure/azure.go
lwgenerate/azure/test-data/activity-log-with-all-subscriptions.tf
lwgenerate/azure/test-data/activity-log-with-lacework-profile.tf
lwgenerate/azure/test-data/activity-log-with-list-subscriptions.tf
lwgenerate/azure/test-data/activity-log-with-location.tf
lwgenerate/azure/test-data/activity_log_with_config.tf
lwgenerate/azure/test-data/activity_log_without_config.tf
lwgenerate/azure/test-data/customer-ad-details.tf
lwgenerate/azure/test-data/renamed_activity_log.tf
lwgenerate/azure/test-data/renamed_config_and_activity_log.tf

Enable Infrastructure Encryption by default when creating a new Azure Storage Account for activity log integration.
* updated automated tests
* executed manually
https://lacework.atlassian.net/browse/GROW-2556

fix(GROW-2556): enable azure storage account infra encryption

---

cli/cmd/generate_aws.go
cli/docs/lacework_generate_cloud-account_aws.md
integration/test_resources/help/generate_cloud-account_aws
integration/test_resources/help/generate_cloud-account_aws_controltower
lwgenerate/aws/aws.go
lwgenerate/hcl.go

Add the `--aws_assume_role` flag to `lacework generate cloud-account aws`
`make test`
Run `lacework generate cloud-account aws --noninteractive --agentless --config --cloudtrail --aws_profile org --aws_assume_role arn:aws:iam::123456789000:role/role_in_account_b --aws_region us-east-1 --aws_subaccount subaccount1:us-east-2,subaccount2:us-east-3`. Then verify the generated terraform code:
```
terraform {
required_providers {
lacework = {
source  = "lacework/lacework"
version = "~> 1.0"
}
}
}
provider "aws" {
alias   = "main"
profile = "org"
region  = "us-east-1"
assume_role {
role_arn = "arn:aws:iam::123456789000:role/role_in_account_b"
}
}
provider "aws" {
alias   = "subaccount1"
profile = "subaccount1"
region  = "us-east-2"
}
provider "aws" {
alias   = …
```

chore: Implement --aws_assume_role flag for CLI aws integration

---

.github/workflows/chocolatey-release.yml

Since the Codefresh action to release the SDK to Chocolatey is no longer available a github action needed to be created.
Used actionlint and ran the github action successfully. 
https://lacework.atlassian.net/browse/GROW-2554

build(release): fix chocolately release action

---

cli/cmd/component.go

From @cody-lw:
> Minor brevity thing I noticed this morning, `lacework component list` will return the
> version available rather than the current installed version of a component.
This code tries to clarify that, when a component IS installed and HAS an update, we still display
the installed version, rather that the latest version.
Users can use `lacework component show <component>` to see where they are and what
can they upgrade to, example:
```
$ lacework component show sca
NAME        STATUS                DESCRIPTION
-------+------------------+------------------------------
sca    Update Available   Software Component Analysis
The following versions of this component are available to install:
- 0.0.63
- 0.0.64
- 0.0.65
- 0.0.66
- 0.0.67
- 0.0.68
- 0.0.69
- 0.0.70
- 0.0.71
- 0.0.72
- …
```

fix(component): List installed version instead of latest

---

cli/cmd/generate_aws.go
cli/docs/lacework_generate_cloud-account_aws.md
integration/aws_generation_test.go
integration/test_resources/help/generate_cloud-account_aws
integration/test_resources/help/generate_cloud-account_aws_controltower
lwgenerate/_examples/aws/main.go
lwgenerate/aws/aws.go
lwgenerate/aws/aws_test.go
lwgenerate/hcl.go

- Base [PR](https://github.com/lacework/go-sdk/pull/1423)
- Support Agentless organization(multi-account) integration with auto snapshot. More details can be found [here](https://github.com/lacework/terraform-aws-agentless-scanning/blob/main/examples/multi-account-multi-region-auto-snapshot/README.md).
`make test`
Run the noninteractive mode:
`lacework generate cloud-account aws --noninteractive --aws_organization --agentless --aws_region us-east-1 --agentless_management_account_id 123456789000 --agentless_monitored_account_ids 123456789000,ou-abcd-12345678,r-abcd --aws_subaccount subaccount1:us-east-2,subaccount2:us-east-3`
https://lacework.atlassian.net/browse/GROW-2504

feat: support Agentless origanization integration with auto snapshot

---

api/cloud_accounts.go
api/cloud_accounts_azure_sidekick.go
api/cloud_accounts_azure_sidekick_test.go
api/cloud_accounts_gcp_sidekick_test.go

This is needed to support Agentless running on Azure. 
Added a test. `make test` passed. Also 
```
#go test -v -run "TestCloudAccountsAzureSidekick"
go test -v -run "TestCloudAccountsAzureSidekick"
=== RUN   TestCloudAccountsAzureSidekickCreate
--- PASS: TestCloudAccountsAzureSidekickCreate (0.00s)
=== RUN   TestCloudAccountsAzureSidekickGet
--- PASS: TestCloudAccountsAzureSidekickGet (0.00s)
=== RUN   TestCloudAccountsAzureSidekickUpdate
--- PASS: TestCloudAccountsAzureSidekickUpdate (0.00s)
PASS
ok    github.com/lacework/go-sdk/api  3.136s
```
https://lacework.atlassian.net/browse/PSP-1220

feat(PSP-1220): add new cloud account type for Azure Agentless integration

---

cli/cmd/generate_aws.go
integration/aws_generation_test.go
integration/test_resources/help/generate_cloud-account_aws
integration/test_resources/help/generate_cloud-account_aws_controltower
lwgenerate/aws/aws.go

Branched from https://github.com/lacework/go-sdk/pull/1424
Add support for organization cloudtrail setting in the lw_generate cloudtrail module
``` module "cloudtrail" {
source  = "lacework/cloudtrail/aws"
version = "2.8.0"
is_organization_trail = true
org_account_mappings = [{
default_lacework_account = "main"
mapping = [
{
lacework_account = "lw-sub-account"
aws_accounts     = "123456789011"
},
]
}]
}
```
https://lacework.atlassian.net/browse/GROW-2504

feat: add org-cloudtrail to lw_generate

---

api/cloud_accounts_azure_sidekick.go
api/cloud_accounts_azure_sidekick_test.go

There are two small changes in this PR:
1. Added integration level const strings which are used in tf provider (PR up soon)
2. Added new fields in integration object `ScanningResourceGroupName` and `StorageAccountUrl` 
3. remove unused `is_org` field
4. s/subscriptionList/subscriptionsList/g
updated test.
https://lacework.atlassian.net/browse/PSP-1220

feat(PSP-1220): misc fixes in Azure Agentless cloud provider

---

lwcomponent/component.go

Due to the use of os.Rename, component installs were failing when the temporary download folder was on a different volume than the destination folder. This impacted some AWS ec2 instance and probably containers. 
built and ran on command line
https://lacework.atlassian.net/browse/GROW-2581

fix(cdk): component install fails

---

lwgenerate/aws/aws.go

- Do not add IAM role attributes for CloudTrail when doing org integration for CloudTrail and Configuration
make test
make integration-generation
https://lacework.atlassian.net/browse/GROW-2587

chore: remove iam role attributes from CloudTrail if Config org enabled

---

cli/cmd/generate_aws.go
integration/aws_generation_test.go
lwgenerate/aws/aws.go

Only require `--agentless_monitored_accounts` when single account ids are provided.
`make test`
Only prompt user to enter profile/region for single accounts:
https://lacework.atlassian.net/browse/GROW-2586

chore: make agentless_monitored_accounts optional

---

Makefile
cli/cmd/generate_aws.go
cli/docs/lacework_generate_cloud-account_aws.md
integration/aws_generation_test.go
integration/test_resources/help/generate_cloud-account_aws
integration/test_resources/help/generate_cloud-account_aws_controltower
lwgenerate/aws/aws.go

- Add [CloudTrail Control Tower](https://github.com/lacework/terraform-aws-cloudtrail-controltower/tree/main) support to `lacework generate cloud-account aws --aws_organization --cloudtrail --controltower` to generate terraform code 
make test
make integration-generation-only
https://lacework.atlassian.net/browse/GROW-2592

chore: add CloudTrail Control Tower to generate AWS

---

Makefile
lwcomponent/api_info.go
lwcomponent/api_info_test.go
lwcomponent/catalog.go
lwcomponent/catalog_test.go
lwcomponent/cdk_component.go
lwcomponent/cdk_component_test.go
lwcomponent/dev_info.go

CDK v1 code path now using `.dev` file data.
We only need to compile for our platform when we install the CLI using make.  This is a lot faster.
1. `lacework component switch techally`
2. `lacework component dev tester`
3. `lacework component switch qan`
4.
```
> lacework component list
STATUS                 NAME              VERSION                   DESCRIPTION
-------------------+-------------------------+-----------+--------------------------------------------
Installed          tester                    0.0.0-dev   (dev-mode) testing stuff
Components version: 0.3.0
```
https://lacework.atlassian.net/browse/GROW-2590

feat(GROW-2590): CDK .dev file info

---

integration/compliance_aws_test.go

Some how this recommendation id disappeared since Friday... 🤦🏽‍♂️
Ran integration tests locally:
N/A

ci: fix integration tests

---

cli/cmd/component.go

Downloading components with `--noninteractive` leads to a segmentation fault - the CLI spinner hasn't been initialised.  
The fix is to wrap the spinner code with `!cli.nonInteractive`.
```
> bin/lacework component install sca --noninteractive
[signal SIGSEGV: segmentation violation code=0x2 addr=0x38 pc=0x101e290a4]
goroutine 13 [running]:
github.com/lacework/go-sdk/cli/cmd.downloadProgress(0x0?, {0x14000182360?, 0x0?}, 0x0)
/Users/j0n/Workspace/Lacework/go-sdk/cli/cmd/component.go:1151 +0x84
github.com/lacework/go-sdk/cli/cmd.prototypeRunComponentsInstall.func1({0x14000182360?, 0x4?}, 0x0?)
/Users/j0n/Workspace/Lacework/go-sdk/cli/cmd/component.go:925 +0x34
created by github.com/lacework/go-sdk/lwcomponent.State.Install in goroutine 1 …
```

fix: component download segv

---

api/lql_validate.go
api/lql_validate_test.go
cli/cmd/lql_validate.go

This is to support an extra field queryLanguage in the input for query validation command.  It’s optional, by default it should be LQL
* build and install the CLI from source: make prepare && make install-cli
* Create a file containing a Rego query:
```
$ cat /Users/kchen/proj/opa/rego_query.yaml
---
queryId: TestRegoQueryViaCli2
queryLanguage: Rego
queryText: |-
package lacework.policies.lacework_global_134
import future.keywords
import data.lacework
import data.lacework.assessment
source := lacework.aws.cfg.list("s3", "list-buckets")
assess := assessment.violation(input, "just because")
```
*  Query validate command can be executed successfully against the file:
```
$ /usr/local/bin/lacework query validate  -f /Users/kchen/proj/opa/rego_query.yaml
Query validated successfully. Time for …
```

feat(RAIN-91461): support Rego in query validate

---

api/policy.go
api/policy_test.go
cli/cmd/policy.go

* Create a policy using an existing Rego query: `/usr/local/bin/lacework policy create -f /Users/kchen/proj/opa/Rego_policy.yaml`
```
$ cat /Users/kchen/proj/opa/Rego_policy.yaml
---
evaluatorId: Cloudtrail
policyType: Violation
queryId: TestRegoQueryViaCli2
policyId: regopolicy-000
enabled: true
title: Test Policy for Rego Query
description: For Rego policy testing
remediation: |-
Check that the console login was expected.
AWS recommends to require MFA for all users.
severity: high
alertEnabled: true
tags:
- technique:Rego
```
* Show the policy:
```
$ /usr/local/bin/lacework policy show dev8-regopolicy-000
POLICY ID        SEVERITY             TITLE               STATE    ALERT STATE   FREQUENCY                TAGS
----------------------+----------+----------------------------+---------+- …
```

feat(cli): show query language in policies when available

---

cli/cmd/vuln_container_show_assessments.go
integration/container_vulnerability_test.go

I have a feeling that the problem of this test is that we run all the `t.Run()` statements in parallel, I think.
Run integration tests locally. CI should be green.
N/A

ci: fix TestContainerVulnerabilityCommandsEndToEnd

---

lwgenerate/aws/aws.go
lwgenerate/aws/aws_test.go

Always set the alias to "main" for the main AWS provider
- Run `lacework generate cloud-account aws --config='true' --cloudtrail='true' --aws_region='eu-central-1' --existing_bucket_arn='arn:aws:s3:::aws-cloudtrail-logs-66cc8675' --existing_sns_topic_arn='arn:aws:sns:eu-central-1:191155994050:aws-cloudtrail-logs-66cc8675' --noninteractive --lacework_aws_account_id='434813966438';`
- Run `terraform validate`
https://lacework.atlassian.net/browse/GROW-2643

fix: always set alias "main" for the main profile

---

.github/workflows/lacework-code-analysis.yml

This is a temporary fix installing Semgrep in the SAST workflow until we get Semgrep properly packaged in our the SAST component.
https://lacework.atlassian.net/browse/COD-2330

fix: temporarily install Semgrep to fix SAST

---

cli/cmd/cache.go

Currently if there are issues generating a token during the CLI startup process the response message is the raw API response. This commit parses that response a bit and pads the error with a bit more information.
Tests & manual execution
https://lacework.atlassian.net/browse/GROW-2632

fix: improve error message when token generate fails in cli

---

cli/cmd/vuln_host.go
cli/cmd/vuln_host_list_cves.go
integration/host_vulnerability_test.go
integration/test_resources/help/vulnerability_host_list-cves

The `lacework vulnerability host list-cves` command is timing out for some customers with a large amount of data. The command defaults to a 24 hour window. We can replicate this by calling the API with the same 24h window and it times out. Enable the start time, end time, and range flags to enable querying smaller amounts of data. 
Passed unit tests
Passed integration tests
Build CLI locally and manually tested the flags
https://lacework.atlassian.net/browse/LINK-2415
https://lacework.atlassian.net/browse/RAIN-91480

feat(cli): Add time filter to vulnerability host list-cve command

---

cli/cmd/generate.go
cli/cmd/generate_cloud_account.go
cli/docs/lacework_generate.md
cli/docs/lacework_generate_cloud-account.md
cli/docs/lacework_generate_k8s.md
go.mod
integration/test_resources/help/generate
integration/test_resources/help/generate_cloud-account
integration/test_resources/help/generate_k8s

- `--apply` and `--output` flag are defined in all subcommands of `lacework generate`. This PR declares them on `lacework generate` so these two flags could show up in docs for `lacework generate`.
- Subcommands will keep their own declaration and variable binding for `--apply` and `--output`.
`make build-cli-cross-platform`
https://lacework.atlassian.net/browse/GROW-2602

docs(cli): declare --apply and --output on lacework generate

---

cli/cmd/generate_execute.go

Should a failed generated cloud account Terraform execution fail, add feedback so that a customer knows how to restart the failed integration attempt (or clean it up)
Manual execution.
https://lacework.atlassian.net/browse/GROW-2640

fix: provide guidance after failed terraform execution

---

integration/policy_exceptions_test.go

go-sdk test is broken due to the change in https://github.com/lacework/services/pull/18387/files#diff-4d159a775505a4026f5a01f03d33bc1a534aecb098169c95b386156e956f3419R174
Add `arns` to policy_exceptions_test.go to fix it
make integration-only
CodeFresh pipeline failed: https://g.codefresh.io/build/659d1922df1107d2516cb8b3?step=integration&tab=output&logs=terminal

fix: update policy_exceptions_test.go

---

cli/cmd/grpc.go

When debugging a CDK component, it might expect some environment variables and a
running gRPC server, this command starts the CDK server and shows the variables that
a component might need.
_**NOTE that this command is hidden.**_
1. Ran the command.
2. (on a new terminal) Exported the env variables
3. (on the same terminal) Started a component that depends on the gRPC server and envs
Used https://github.com/lacework-dev/cdk-preflight component for testing.
```
➜  go-sdk git:(afiune/cli/grpc-cmd) lacework grpc
Development mode for CDK components
===================================
When debugging a component, it might expect some environment variables and a
running gRPC server, this command starts the CDK server and shows the variables
that your component might need:
export …
```

feat(cli): gRPC command to debug CDK components

---

cli/cmd/generate_gcp.go

Correct the state for the audit_log flag
Tests & manual execution
N/A

fix: correct gcp generate audit-log flag

---

cli/cmd/component_args.go
cli/cmd/component_args_test.go

If a component flag is followed by an argument that has a `-` prefix, we treat it as an argument, and not as a shorthand flag.
I added further tests based on we need to [support](https://github.com/spf13/pflag?tab=readme-ov-file#command-line-flag-syntax).
There is a problem.  We are unable to handle both shorthand expansion like `-xyz` -> `-x -y -z` and shorthand assignment such as `-n1234`, `-n1234` is equivalent to `-n=1234` and `-n 1234`.  We cannot lookup the component flags to know that `-n1234` should not be expanded.  Just pass through to the component and let the component parse.
Inputs based on https://github.com/spf13/pflag?tab=readme-ov-file#command-line-flag-syntax
Unit testing and manual
https://lacework.atlassian.net/browse/GROW-2677

fix: component args

---

cli/cmd/generate_aws.go
integration/aws_generation_test.go
lwgenerate/aws/aws.go
lwgenerate/aws/aws_test.go

For the aws generate command, if using existing trail:
- Make the prompt questions required for trail name, S3 bucket ARN and SNS topic ARN, 
- Add validations for the required fields to existing trial.
Manual test by running `lacework generate cloud-account aws`
https://lacework.atlassian.net/browse/GROW-2715

chore: update user flow and validation for using existing CloudTrail

---

cli/cmd/version.go

Zillow is complaining about error logs due to failure in the version check. This is probably due to GitHub rate limiting, but we should avoid logging too many errors. It is too verbose.
No test
##
https://lacework.atlassian.net/browse/COD-2516

fix: do not log errors if version check fails

---

cli/cmd/honeyvent.go
cli/cmd/root.go

Dataset is not being set for honeycomb
Run cmd and check honeycomb dataset
https://lacework.atlassian.net/browse/GROW-2728

fix: set telemetry dataset

---

cli/cmd/component.go
lwcomponent/catalog.go
lwcomponent/catalog_test.go

- Add the `includeComponentVersions` in `NewCatalog` to optionally fetch component versions
`lacework component list`
`lacework component show component-example`
https://lacework.atlassian.net/browse/GROW-2630

chore(cli): only fetch component versions when needed

---

cli/cmd/component.go
cli/cmd/component_dev.go
lwcomponent/catalog_test.go
lwcomponent/cdk_component.go

For the `lacework component dev` command:
- Call CDK v1 API to fetch components info.
- If The `.dev` specs file exists, show the version value in `.dev` instead of `.version` (same behavior as prototype code).
- Run `lacework component dev test-component` to test a new component is created correctly in dev mode 
- Run `lacework component install spm-opa` and `lacework component dev spm-opa` to test an installed component is moved into dev mode. 
https://lacework.atlassian.net/browse/GROW-2597

chore: use CDK v1 API for lacework component dev

---

.github/workflows/nightly-build.yml

Migrate Codefresh [go-sdk/nightly-build](https://g.codefresh.io/pipelines/edit/workflow?id=601418f6a064656d7c28c389&pipeline=nightly&projects=go-sdk&projectId=60118409468eb5f1e534734f&rightbar=triggers) to GitHub actions
https://github.com/lacework/go-sdk/actions/runs/7906710464
https://lacework.atlassian.net/browse/GROW-2758

ci: Create workflow nightly-build.yml

---

.github/workflows/test-build.yml

Only one run is allowed at a time to do integration tests.

chore: limit the concurrency of test-build workflow runs for a branch

---

cli/cmd/component.go
cli/cmd/component_dev.go
lwcomponent/catalog.go
lwcomponent/catalog_test.go
lwcomponent/cdk_component.go

Every `lacework component list` makes N+1 API calls: API `list all components`, and for N components API `list all versions`.
This PR proposes to fix this by only calling the `list all versions` API endpoint when a users runs `lacework component show`.  This means that `lacework component list` is a single API call, and `lacework component show` is 2 API calls.
The catch is that a user will only see the `Tainted` status after they run `lacework component show`.  Until they run that command, the version will be `Update Available`.
```
> bin/lacework component list
STATUS                 NAME             VERSION                  DESCRIPTION
-------------------+-------------------------+---------+--------------------------------------------
Update Available   component-example         0.6.0 …
```

fix: reduce component API usage

---

lwcomponent/staging.go

Windows doesn't allow the rename of opened files.  Instead copy the files.
Tested on OSX and Windows amd64.
https://lacework.atlassian.net/browse/GROW-2772

fix: component install windows

---

lwcomponent/catalog.go

GROW-2781 is a chicken-egg problem.  Solution is to update the feature flag to `v2` so that the CDK is only usable by CLI versions after the next release.
Continuation from https://lacework.atlassian.net/browse/GROW-2781

feat: CDK v2 feature flag

---

lwcomponent/catalog.go
lwcomponent/host_info.go

CDK v1 wasn't recognising prototype components.
Installing and running components, while switching between prototype and v1 code paths.

fix: cdk backwards compatibility

---

.github/workflows/chocolatey-release.yml
.github/workflows/nightly-build.yml
.github/workflows/prepare-release.yml
.github/workflows/release.yml
.github/workflows/test-build.yml
.github/workflows/update-homebrew-formula.yml
.github/workflows/verify-release.yml
.github/workflows/windows-integration.yml

- Add names to windows-integration.yml and chocolatey-release.yml
- Fix slack alert for test-build
- Move the `@oncall-growth-eng! ...` message to the front to make the message look cleaner.

chore: add workflow names and fix test-build slack alert

---

.github/workflows/prepare-release.yml

Check out the main instead of a commit SHA

chore: set checkout ref to main for prepare-release

---

.github/workflows/prepare-release.yml

set `fetch-depth: 0` to fetch all history of the repo.

chore: fetch all history for prepare-release

---

lwcomponent/catalog.go
lwcomponent/component.go

Bug in prototype b64decode of `.signature`.

fix: cdk v3 feature flag

---

.github/workflows/prepare-release.yml
.github/workflows/release.yml
.github/workflows/test-build.yml
scripts/release.sh

- Add `CI` env for `release.sh`
- Add docker credentials for release.yml
- Add `token` to the checkout action in test-build.yml 
- Can push commit to main now. A successful run: https://github.com/lacework/go-sdk/actions/runs/8024795426
- Use the `softprops/turnstyle` action to replace `concurrency` to only allow 1 running test-build.

ci: fixes on release.yml and test-build.yml

---

.github/workflows/nightly-build.yml
.github/workflows/test-build.yml
Makefile
cli/cmd/component_dev.go
integration/alert_rules_test.go
integration/lql_create_test.go
integration/lql_create_unix_test.go

- Use the [--rerun-fails](https://github.com/gotestyourself/gotestsum?tab=readme-ov-file#re-running-failed-tests) flag to rerun failed tests 2 more times.
- Run `make build` instead of `make build-cli-cross-platform` for faster build
- Use Github Action [job matrix](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs) to run integration tests with different build tags in parallel.
- Fix LQL tests issues caused by the enabling of the [lpp_rego_enabled](https://app.launchdarkly.com/default/production/features/lpp_rego_enabled/history/65dcc9ea187bb70fc59002bd/details/diff) featured flag.
https://github.com/lacework/go-sdk/actions/runs/8072320718
https://lacework.atlassian.net/browse/GROW-2770

ci: integration tests pipeline improvements

---

lwcomponent/catalog.go
lwcomponent/host_info.go
lwcomponent/staging.go

Need to use the `.exe` file extension on windows
tested on windows with SCA.  Install, update, running component
https://lacework.atlassian.net/browse/GROW-2784

fix: component windows extension

---

.github/workflows/release.yml
.github/workflows/test-build.yml
integration/lql_create_unix_test.go
integration/lql_update_unix_test.go

- There is already `docker login` in release.sh. Remove the extra step.
- Fix the LQL query create/update tests
- Don't send Slack alerts in test-build for PRs.
Run `test-build`

ci: fix tests and remove extra docker login in release.yml

---

cli/cmd/component.go
lwcomponent/catalog.go
lwcomponent/catalog_test.go
lwcomponent/staging.go
lwcomponent/staging_test.go

AWS returns an XML error message when there is an issue with the presigned URL.
New unit test and locally against the `gdevus1` cluster.
Problem:
```
> lacework component install component-example --version 0.8.2
[✓] Component component-example found
| Staging component component-example... Downloaded: 0mb
...
- Staging component component-example... Downloaded: 0mb ERROR gzip: invalid header
```
Improvement:
```
> bin/lacework component install component-example --version 0.8.2                                                                             ~/Workspace/Lacework/go-sdk
[✓] Component component-example found
...
ERROR Code: PermanentRedirect.  Message: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this …
```

fix: component download AWS XML error

---

cli/cmd/component.go
cli/cmd/component_dev.go
lwcomponent/catalog.go
lwcomponent/catalog_test.go
lwcomponent/cdk_component.go
lwcomponent/cdk_component_test.go
lwcomponent/host_info.go

Now have a CLI level `componentJSON`.  We can change the underlying CDKComponent without breaking the JSON output.
I refactored parts of the code as a cleanup.
Unit testing
Local testing:
- install, update, list, show, uninstall
- dev mode new
- dev mode enter existing
```
> bin/lacework component show component-example --json
{
"deprecated": false,
"description": "Component description",
"latest_version": "0.9.1",
"name": "component-example",
"status": "Installed",
"type": "CLI_COMMAND",
"version": "0.9.1"
}
```
https://lacework.atlassian.net/browse/GROW-2791

fix(GROW-2791): v1 component JSON

---

.github/workflows/chocolatey-release.yml
.github/workflows/update-cli-docs.yml
.github/workflows/update-homebrew-formula.yml

- Only trigger release downstream pipelines when `release` pipeline runs successfully.
- To update homebrew formula, a local homebrew tap needs to be created. Need to cd to the tap's directory and do `brew audit` with  `--fix`.
https://github.com/lacework/go-sdk/actions/runs/8135421955

ci: fix update-homebrew-formula.yml

---

cli/cmd/cache.go
cli/cmd/cli_state.go
integration/framework_test.go

When running integration tests, set the LW_API_TOKEN env to avoid abusing the /access_token endpoint which has a rate limit.
Run tests with logs. Verify that the token is reused.
https://lacework.atlassian.net/browse/GROW-2770

test: set LW_API_TOKEN for integration tests

---

.github/workflows/verify-release.yml

Got error `fatal: ambiguous argument 'origin..HEAD':`. Set `fetch-depth: 0` to fetch all history and explicitly set HEAD to main.
https://github.com/lacework/go-sdk/actions/runs/8174143700/job/22348240771?pr=1584

ci: fix verify-release.yml fetch-depth

---

cli/cmd/version.go

We should not fail (in Honeycomb) when we can't check for updates, instead we are going to
send a silent error.
Built it and ran CLI locally, saw Honeycomb dev dataset.

fix(telemetry): record silent error

---

api/_examples/cloud-accounts/azure-ad-al/main.go
api/cloud_accounts.go
api/cloud_accounts_azure_ad_al.go
api/cloud_accounts_azure_ad_al_test.go

- Add support for get and update for AzureAdAl integration
- Add unit tests
make test
make install-cli
bin/lacework cloud-account list
bin/lacework cloud-account list -t AzureAdAl
bin/lacework cloud-account show DEV38397_906EC6888EF34B3D7A6ECE49C633ADCAF83DD6F91F357E2
bin/lacework api get /schemas/CloudAccounts
https://lacework.atlassian.net/browse/RAIN-92599

feat(api): Add AzureAdAl integration support

---

cli/cmd/lql.go
lwcomponent/catalog.go

- Always enable LQL rego query and CDK components for test integrations to avoid unexpected failures.
make integration-only regex=TestQueryCreateFromEditor
make integration-only regex=TestCDKComponentList

test: fix TestQueryCreateFromEditor and TestComponent*

---

cli/cmd/component.go
integration/component_test.go

Fixing output when printing `\n` properly.
Added unit tests
https://lacework.atlassian.net/browse/GROW-2790

style(cli): fix component uninstall output

---

Makefile
cli/cmd/component.go
integration/component_test.go
lwcomponent/catalog.go
lwcomponent/cdk_component.go
lwcomponent/http.go
lwcomponent/http_test.go
lwcomponent/staging.go

While installing new component, we are seeing a panic similar to:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x40 pc=0x10534999c]
goroutine 11 [running]:
github.com/lacework/go-sdk/cli/cmd.downloadProgress(0x14000820060?, {0x14000888120?, 0x0?}, 0x0)
/codefresh/volume/go-sdk/cli/cmd/component.go:1177 +0x27c
github.com/lacework/go-sdk/cli/cmd.prototypeRunComponentsInstall.func1({0x14000888120?, 0x0?}, 0x1400005c8a0?)
/codefresh/volume/go-sdk/cli/cmd/component.go:925 +0x34
created by github.com/lacework/go-sdk/lwcomponent.State.Install in goroutine 1
/codefresh/volume/go-sdk/lwcomponent/component.go:279 +0x594
```
This is due to the fact that we were updating the progress `Suffix` unsafely. The fix is to …

fix(cli): avoid panic while updating progress

---

.github/workflows/lacework-code-analysis.yml

Installing Semgrep is no longer required to run Lacework FAST alongside SCA in GitHub Actions.
Tested by the CI here: https://github.com/lacework/go-sdk/actions/runs/8114115657
[COD-2330](https://lacework.atlassian.net/browse/COD-2330)
[COD-2330]: https://lacework.atlassian.net/browse/COD-2330?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ci(COD-2330): remove the Semgrep install step

---

cli/cmd/component.go
integration/component_test.go

We shouldn't return an error when a user runs `component install` on an already installed component.  Context https://lacework.slack.com/archives/C04974WUG0K/p1711013967046719.
The prototype `component install` will reinstall an installed component.  This PR changes the behaviour of the v1 CDK code to do nothing and just return success when a user attempts to install an already installed component.
Same goes for `component update`.
```
bin/lacework component install iac
Component iac is already installed. To upgrade run 'lacework component update iac'
> echo $?
0
```
```
> bin/lacework component update iac
[✓] Component iac found
Component iac is version 0.6.22.
> echo $?
0
```

fix: idempotent component install update

---

cli/cmd/cloud_account.go
cli/cmd/integration_azure.go

This PR adds the ability to create Azure Active Directory Activity Log integrations manually via the LW CLI.
Tested by building the CLI locally.
- make test
- make prepare
- make install-cli
- /usr/local/bin/lacework cloud-account create
- Select Azure Active Directory Activity Log and follow the prompts
- Screenshot [CLI]:
- Screenshot [Result on UI]:
[RAIN-92779](https://lacework.atlassian.net/browse/RAIN-92779)
[RAIN-92779]: https://lacework.atlassian.net/browse/RAIN-92779?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: create AzureAD intg from CLI (manual)

---

cli/cmd/policy_exceptions.go

Prior to this change the data format for resource tags was sent incorrectly, resulting in an ineffectual policy. This corrects that format issue so the policy works.
Manual execution & passing tests
https://lacework.atlassian.net/browse/GROW-2831

fix(GROW-2831): correct handling for resourceTags in policy exceptions

---

lwgenerate/aws/aws.go
lwgenerate/aws/aws_test.go
lwgenerate/hcl.go
lwgenerate/hcl_test.go

* Add generic functionality for hcl output blocks
* Add hooks to AWS to add outputs
Outputs are arbitrary, meaning the author needs to understand the resultant traversal (and that it is valid) otherwise the resultant code will be unusable.
Unit tests
https://lacework.atlassian.net/browse/GROW-2876

feat(GROW-2876): support terraform output blocks in lwgenerate

---

cli/cmd/component.go

Prior to this commit if an error occurred before the download progress function could start, the CLI would block writing to the downloadComplete channel
manual execution & unit tests 
https://lacework.atlassian.net/browse/GROW-2895

fix: use buffered channel for downloadComplete to prevent blocking

---

api/v2_vulnerabilities.go
api/v2_vulnerabilities_test.go

Enable raw access to the machine tags without marshaling to a known struct
Unit test
Fixes #1615

feat: expose raw machine tags for external automation

---

lwgenerate/aws/aws.go
lwgenerate/aws/aws_test.go

Enable lwgenerate to create AWS provider block with [default tags](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/resource-tagging#propagating-tags-to-all-resources) set.
Unit tests
https://lacework.atlassian.net/browse/GROW-2883

feat(GROW-2883): enable adding aws provider default tags

---

lwgenerate/aws/aws.go
lwgenerate/aws/aws_test.go
lwgenerate/hcl.go
lwgenerate/hcl_test.go

Enable some advanced use cases for AWS lwgenerate that require adding custom hclwrite blocks to the root terraform block, the base hcl document, as well as being able to set provider arguments.
See unit tests.
https://lacework.atlassian.net/browse/GROW-2908

feat(GROW-2908): lwgenerate enable custom root terraform blocks and provider arguments

---

lwgenerate/azure/azure.go
lwgenerate/azure/azure_test.go
lwgenerate/azure/test-data/activity_log_with_config_extra.tf
lwgenerate/azure/test-data/activity_log_with_config_provider_args.tf
lwgenerate/azure/test-data/activity_log_with_config_root_blocks.tf

Add ability to add root terraform blocks, top-level document blocks, as well as provider arguments to the lwgenerate package for Azure
See unit tests; also was executed via examples.
GROW-2919

feat(GROW-2819): enable custom blocks with azure generate

---

lwgenerate/gcp/gcp.go
lwgenerate/gcp/gcp_test.go
lwgenerate/gcp/gke.go

feat(GROW-2929): update lwgenerate to support GCP generation

---

lwgenerate/azure/azure.go
lwgenerate/azure/azure_test.go
lwgenerate/azure/test-data/activity_log_with_config_azureadprovider_args.tf

Split arguments sent to azuread and azurerm providers since they need to be different.
Unit tests
GROW-2819

fix(GROW-2819): lwgenerate split azuread and azurerm provider arguments

---

api/component_data.go
api/component_data_test.go
integration/resource_groups_test.go

ProSAST must upload with the `UrlType` of `ProSast`.
Improved resourceGroup integration test by telling user how to recover.
Unit test
https://lacework.atlassian.net/browse/COD-3355

feat: prosast component data upload

---

integration/resource_groups_test.go

Add uuid for resource group tests.

chore: Add uuid for resource group tests

---

cli/cdk/go/proto/v1/cdk.pb.go
cli/cdk/go/proto/v1/cdk_grpc.pb.go
cli/cmd/generate_gcp.go
cli/docs/lacework_generate_cloud-account_gcp.md
integration/gcp_generation_test.go
integration/test_resources/help/generate_cloud-account_gcp
lwgenerate/gcp/gcp.go
lwgenerate/gcp/gcp_test.go

Provide organization_id for project level agentless integration.
Tested using `lacework generate cloud-account gcp` command line to generate agentless terraform.

feat(GROW-2949): Provide organization_id for project level agentless integration

---

api/client.go
integration/container_vulnerability_test.go

Some integration tests take a long time to get response from API which may lead to timeout sometimes. Increase the APi timeout to 120s

fix: Increase API timeout to 120 seconds

---

.github/workflows/commit-lint.yml
lwgenerate/aws/aws.go

For single-account, multi-region AWS Agentless integration, we need to support passing `access_key`, `secret_key` and `token` for multiple regions(AWS providers).

chore(GROW-2960): support access keys for AWS Agentless multiple scanning regions 

---

api/resource_groups.go
api/resource_groups_test.go
cli/cmd/resource_groups.go

Bug in CLI causing us to output wrong casing for filter names.
Added a unit test. Also ran cli locally to visually confirm that the filter names where not getting changed when a camel case filter name is provided.

fix: Fix casing during reading of resource group

---

lwgenerate/aws/aws.go
lwgenerate/aws/aws_test.go

Disable aws_flow_log creation in go-sdk.
Tested in dev5
[GROW-3001](https://lacework.atlassian.net/browse/GROW-3001)
[GROW-3001]: https://lacework.atlassian.net/browse/GROW-3001?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Disable aws_vpc_log creation in go-sdk

---

cli/README.md

Installation instructions should include Azure Cloud Shell, as many integration processes can be done through Cloud Shell with LW CLI installed.
N/A
Mantis 1111465

docs: Add Azure Cloud Shell installation instructions

---

api/agent_access_tokens.go
cli/cmd/agent.go
cli/docs/lacework_agent_token_create.md
integration/container_vulnerability_test.go
integration/test_resources/help/agent_token_create

Need to create an "Agent Access Token" for Windows with cli command. 
CLI command: lacework agent token create <name> [description] [os] 
os can be "linux" or "windows". 
Also make changes in api/agent_access_tokens.go to support the above cli command and Terraform provider script. https://github.com/lacework/terraform-provider-lacework/pull/680
platform: devspaces, verified on QAN.
Attached screen shots:
https://lacework.atlassian.net/browse/LINK-3491

chore: add os parameter to cli command and agent-access-token create function

---

go.mod

Need to specify 1.24.0 instead of 1.24
Reference: https://github.com/golang/go/issues/62278#issuecomment-1693538776

chore: specify go 1.24.0

---

lwpreflight/aws/aws.go
lwpreflight/aws/caller.go
lwpreflight/aws/detail.go
lwpreflight/aws/permission.go
lwpreflight/aws/policy.go
lwpreflight/azure/azure.go
lwpreflight/azure/caller.go
lwpreflight/azure/detail.go
lwpreflight/azure/permission.go
lwpreflight/azure/policy.go
lwpreflight/gcp/caller.go
lwpreflight/gcp/detail.go
lwpreflight/gcp/gcp.go
lwpreflight/gcp/permission.go
lwpreflight/gcp/policy.go
lwpreflight/verbosewriter/verbosewriter.go

Add `verbosewriter` to print preflight progress messages. It can be overwritten so that the consumer of `lwpreflight` can relay the progress messages to another writer.

chore(lwpreflight): add verbose writer to show preflight progress messages

---

api/alerts_details.go
api/alerts_details_observationtimeline.go
api/alerts_details_observationtimeline_test.go
cli/cmd/alert_show.go
cli/cmd/alert_show_observationtimeline.go
cli/docs/lacework_alert_show.md
integration/alert_show_test.go
integration/test_resources/help/alert_show

Add a new scope for alerts show command in cli to match the below api. 
GET https://YourLacework.lacework.net/api/v2/Alerts/{alertId}?scope=ObservationTimeline
**Example CLI command**:
lacework alert show 126275 --scope ObservationTimeline
Tested on local cli.
Able to fetch the right data. 
Help text:
(https://lacework.atlassian.net/browse/CAD-1300?atlOrigin=eyJpIjoiOTJkMTc3Yjc3OGFiNGY0OWFlZWY4NmY3MTA0YzIxYzQiLCJwIjoiaiJ9)

feat(cli): Add new scope "ObservationTimeline" to alert show command

---

cli/cmd/outputs.go

https://lacework.atlassian.net/browse/PLTI-599
The response from http.go already has tab escaped "\\t" however after the decoder process the escaped character is converted to a literal tab for resourceTags.
"Tags" is unaffected because it's an array.

fix:(PLTI-599) Tab escape issue in resourceTags
