cli/cmd/version.go
cli/install.ps1
cli/install.sh
scripts/release.sh

chore(cli): style updates to release scripts

---

api/api.go
api/client.go
api/events.go
api/events_test.go
cli/cmd/event.go

The new `EventsService` is a service that interacts with the Events
endpoints from the Lacework Server API. We are adding the first two
functions to get the list of events by a time range.
* `ListRange(start, end)`: returns a list of Lacework events during
the specified data range
* `List()`: leverages ListRange and returns a list of events from the
last 7 days
Additionally the new `event` command has one sub-commands called
`list` exposed to the end-user. This new command will list all events
from a date range, by default last 7 days unless the user provides a
different range.
Example: Human readable format
```
$ lacework event list
EVENT ID |                TYPE                | SEVERITY |      START TIME      |       END TIME
-----------+------------------------------------+----------+- …
```

API Events Implementation + New `event` CMD

---

scripts/release.sh
scripts/release_containers.sh

ci: add docker images to release notes

---

scripts/release.sh

ci: fix typo in release.sh script

---

cli/README.md

doc: update cli documentation cli/README.md

---

api/events.go
cli/cmd/event.go

Closes https://github.com/lacework/go-sdk/issues/127

chore: fix typos in AWS events

---

.circleci/config.yml

ci: update circleci config

---

.circleci/config.yml
Makefile
scripts/release.sh

This is the first iteration of the update to the release process so that
it is now automated by CircleCI, the only requirement from us will be to
run the prepare command to add any relevant release note on every
release, as well if we need to do a major or minor version bump.

ci: update release process to be automated v.1

---

Makefile
scripts/release.sh

ci: fix typos in Makefile

---

.circleci/config.yml
scripts/release.sh

ci: fix typos in .circleci/config.yml

---

.circleci/config.yml
scripts/release.sh

ci: create release from git tag

---

.circleci/config.yml
scripts/release.sh

ci: update slack notify users and fix typos

---

api/integrations_slack_channel.go
cli/cmd/integration.go

Contributes to https://github.com/lacework/go-sdk/issues/169

fix(cli): missing fields for Slack integrations

---

cli/cmd/integration.go
cli/cmd/integration_test.go

Closes https://github.com/lacework/go-sdk/issues/169

fix(cli): missing integration details

---

cli/cmd/compliance_aws.go
cli/cmd/compliance_azure.go
cli/cmd/compliance_gcp.go

Quick fix of spelling of the word 'visualize'. 
Signed-off-by: Scott Ford <scott.ford@lacework.net>

chore(typo) fix spelling of visualize for compliance help command

---

.circleci/config.yml
scripts/release.sh
scripts/release_containers.sh

feat(ctr): use new lacework/lacework-cli repository

---

.circleci/config.yml

We want to have notifications when our nightly builds fail!

ci(slack): notify pipeline failures

---

.circleci/config.yml

fix(ci): remove slack notification for windows

---

api/vulnerabilities_host.go
cli/cmd/vuln_host.go

```
$ lacework vulnerability host scan-pkg-manifest --packages '{
"os_pkg_info_list": [
{
"os":"Ubuntu",
"os_ver":"18.04",
"pkg": "openssl",
"pkg_ver": "1.1.1-1ubuntu2.1~18.04.5"
}
]
}'
CVE COUNT | SEVERITY | PACKAGE |         VERSION          | FIXES AVAILABLE
------------+----------+---------+--------------------------+------------------
3 | High     | openssl | 1.1.1-1ubuntu2.1~18.04.5 |               3
26 | Medium   | openssl | 1.1.1-1ubuntu2.1~18.04.5 |              26
35 | Low      | openssl | 1.1.1-1ubuntu2.1~18.04.5 |              31
```
```
$ lacework vulnerability host scan-pkg-manifest '{
"os_pkg_info_list": [
{
"os":"Ubuntu",
"os_ver":"18.04",
"pkg": "openssl",
"pkg_ver": "1.1.1-1ubuntu2.1~18.04.5"
}
]
}'
CVE      | SEVERITY |  SCORE   | PACKAGE |         VERSION          | …
```

feat: human-readable output for scan-pkg-manifest

---

cli/cmd/lql.go

feat(lql): improve running queries

---

.circleci/config.yml
cli/cmd/package_manifest.go

We will update the documentation https://support.lacework.com/hc/en-us/articles/360049666194-Host-Vulnerability-Assessment-Overview

refactor: remove 'apk' as supported pkg manager 

---

integration/host_vulnerability_test.go

Updating persistent Circle CI test node for host vulnerability testing. 
Signed-off-by: Scott Ford <scott.ford@lacework.net>

fix(ci) Update CI test node

---

Makefile
cli/install.sh
scripts/release.sh

Closes https://github.com/lacework/go-sdk/issues/234

feat(cli): add ARM support

---

.circleci/config.yml

Since it is not supported by CircleCI :facepalm:

ci: remove slack alert for win systems

---

integration/host_vulnerability_test.go

Closes https://github.com/lacework/go-sdk/issues/261

ci: update hostname from our test machine

---

api/lql.go

fix(api): new request body for LQL service

---

cli/cmd/agent_install.go
cli/cmd/agent_install_test.go
lwrunner/runner.go
lwrunner/runner_test.go

Increasing the test coverage of our `lwrunner` package.

test(cli): increase agent install test coverage

---

.circleci/config.yml
scripts/release_containers.sh

This pull request is updating the slack mentions to point to our team alias @allies 🙌🏽
Additionally, we are going to stop publishing containers to the old docker hub repository:
* https://hub.docker.com/r/techallylw/lacework-cli
**JIRA: ALLY-267**

ci: updates previous to release

---

api/_examples/splunk-alert-channel/main.go
api/integration_alert_channels_splunk.go
api/integration_alert_channels_splunk_test.go
api/integrations.go
cli/cmd/integration.go
cli/cmd/integration_splunk.go

feat(cli): Add Splunk alert channel

---

api/_examples/gcp_pub_sub-alert-channel/main.go
api/integration_alert_channels_gcp_pub_sub.go
api/integration_alert_channels_gcp_pub_sub_test.go
api/integrations.go
cli/cmd/integration.go
cli/cmd/integration_gcp_pub_sub_channel.go

feat(cli): New Gcp PubSub alert channel

---

.circleci/config.yml

Update the release workflow to trigger homebrew formula job

ci: trigger homebrew update script

---

api/integration_alert_channels_gcp_pub_sub.go
api/integration_alert_channels_gcp_pub_sub_test.go
cli/cmd/integration.go
cli/cmd/integration_gcp_pub_sub_channel.go

Add the previously omitted issue_grouping field to gcp pub sub

fix: Add issue_grouping field to gcp pub sub

---

api/_examples/service-now-alert-channel/main.go
api/integration_alert_channels_service_now.go
api/integration_alert_channels_service_now_test.go
api/integrations.go
cli/cmd/integration.go
cli/cmd/integration_service_now_channel.go

feat(cli): New Service Now alert channel

---

cli/cmd/integration_gcp_pub_sub_channel.go
cli/cmd/integration_service_now_channel.go

fix: Use select for issue grouping

---

cli/cmd/integration_gcp.go
cli/cmd/integration_gcp_pub_sub_channel.go

Change private key input method to survey.Editor

refactor: Change input method for private_key field

---

cli/cmd/package_manifest_test.go
lwrunner/runner_test.go

ci: disable home directory cache mechanism

---

api/_examples/datadog-alert-channel/main.go
api/integration_alert_channels_datadog.go
api/integration_alert_channels_datadog_test.go
api/integrations.go
cli/cmd/integration.go
cli/cmd/integration_datadog.go

feat(cli): New Datadog alert channel 

---

api/_examples/cisco-webex-alert-channel/main.go
api/integration_alert_channels_cisco_webex.go
api/integration_alert_channels_cisco_webex_test.go
api/integrations.go
cli/cmd/integration.go
cli/cmd/integration_cisco_webex.go

feat(cli): New CiscoWebex alert channel

---

api/_examples/victorops-alert-channel/main.go
api/integration_alert_channels_victorops.go
api/integration_alert_channels_victorops_test.go
api/integrations.go
cli/cmd/integration.go
cli/cmd/integration_victorops.go

feat(cli): New VictorOps alert channel

---

api/_examples/new-relic-alert-channel/main.go
api/integration_alert_channels_new_relic.go
api/integration_alert_channels_new_relic_test.go
api/integrations.go
cli/cmd/integration.go
cli/cmd/integration_new_relic_channel.go

New Relic Insights alert channel
Signed-off-by: Darren Murray darren.murray@lacework.net

feat(cli): New Relic Insights alert channel

---

api/_examples/qradar-alert-channel/main.go
api/integration_alert_channels_qradar.go
api/integration_alert_channels_qradar_test.go
api/integrations.go
cli/cmd/integration.go
cli/cmd/integration_qradar_channel.go

New IBM QRadar alert channel
Signed-off-by: Darren Murray darren.murray@lacework.net

feat(cli): New IBM QRadar alert channel

---

README.md
cli/README.md

Add Homebrew command to list of installation methods of Lacework Cli

docs: Add Homebrew installation to README

---

.circleci/config.yml
README.md
cli/README.md
cli/cmd/cli_unix.go
cli/cmd/cli_unix_test.go
cli/cmd/cli_windows.go
cli/images/amazonlinux-2/Dockerfile
cli/images/centos-8/Dockerfile
cli/images/debian-10/Dockerfile
cli/images/ubi-8/Dockerfile
cli/images/ubuntu-1804/Dockerfile
cli/images/windows-nanoserver/Dockerfile
integration/framework_test.go
scripts/release.sh

ci: delete 'master' branch

---

.circleci/config.yml

ci: run integration tests on ARM-linux

---

.circleci/config.yml

fix prepare-test-resources job

ci: fix prepare-test-resources job

---

go.sum
scripts/release.sh

ci: automatic minor version bump

---

.circleci/config.yml
integration/compliance_azure_test.go
scripts/prepare_test_resources.sh

Add setup_remote_docker to prepare-test-resources job

ci: Add setup_remote_docker to prepare-test-resources job

---

.circleci/config.yml
.github/dependabot.yml

ci: switch over our CI to CodeFresh

---

cli/cmd/integration_service_now_channel.go

fix(cli): mask ServiceNow integration password

---

scripts/githooks/commit-msg
scripts/release.sh

ci: fix githooks and release scripts

---

integration/host_vulnerability_test.go

Closes https://github.com/lacework/go-sdk/issues/261

test(integration): fix failing test from API changes

---

cli/cmd/agent_install.go
cli/cmd/agent_install_test.go

refactor(cli): use official url for agent installs

---

integration/event_test.go

fix(fmt): undetected format problem

---

integration/test_resources/policy/my-policy-1.json

Adding policy resource for -u URL testing
ALLY-451

test(policy): adding policy test resource

---

api/vulnerabilities_host.go
api/vulnerabilities_host_test.go
cli/cmd/vuln_host.go
integration/host_vulnerability_test.go

Remove severity Negligible and replace with Info

refactor: Remove severity Negligible and replace with Info

---

api/api.go
api/client.go
api/policy.go
api/policy_test.go
cli/cmd/lql.go
cli/cmd/policy.go
integration/policy_test.go

Introducing policy create command
ALLY-445

feat(cli): lacework policy create

---

integration/container_vulnerability_test.go

😭 - https://github.com/lacework/go-sdk/issues/399

ci: disable on-deman ctr vulnerability tests

---

api/policy.go
api/policy_test.go
cli/cmd/policy.go
integration/policy_test.go

Initial commit of policy list/show
ALLY-447
ALLY-448

feat(cli): lacework policy list/show

---

README.md

ci: Add Codefresh badge

---

scripts/release.sh

ci: fix release script for automatic releases

---

integration/container_vulnerability_test.go

GH: https://github.com/lacework/go-sdk/issues/399

test(cli): add container vuln scan NO polling

---

integration/container_vulnerability_test.go

ci(cli): fix integration test

---

integration/container_vulnerability_test.go

ci: Disable failing test

---

integration/help_test.go

test(integration): fix missed help message update

---

api/policy.go
api/policy_test.go
cli/cmd/policy.go
integration/policy_test.go

Introducing policy update functionality
ALLY-446

feat(cli): lacework policy update

---

api/integrations.go
api/integrations_aws_test.go
cli/cmd/integration.go
cli/cmd/integration_aws_govcloud.go

AWS Gov Cloud CloudTrail integration

feat: AWS Gov Cloud CloudTrail integration

---

Makefile
go.mod
go.sum
integration/configure_unix_test.go
integration/integration_test.go
vendor/modules.txt

ci: fix a bunch of things with our CI pipeline

---

integration/test_resources/lql/MyLQL.lql

Adding resource for lqlv2 testing
ALLY-521

test(cli): adding lqlv2 test resource

---

integration/test_resources/lql/LW_CLI_AWS_CTA_IntegrationTest.lql
integration/test_resources/policy/lacework-clitest-1.json

test(cli): updated naming for test resources

---

integration/test_resources/lql/LW_CLI_AWS_CTA_IntegrationTest.yaml

Adding `lacework query` integration test resource for apiv2
ALLY-537

test(cli): add apiv2 query resource

---

integration/framework_test.go
integration/host_vulnerability_test.go

Check machineID exists in host_vulnerability_test . If not attempt to find a suitable machineID to run host vuln tests against

test: check machineID exists in host_vulnerability_test.go

---

integration/account_test.go
integration/configure_unix_test.go
integration/framework_test.go
integration/host_vulnerability_test.go
integration/test_resources/lacework_env/integrations/integrations.tf
integration/test_resources/lacework_env/integrations/variables.tf

Add tf variable for lacework_aws_account_id

ci: decouple integrations tests

---

integration/test_resources/policy/lacework-clitest-1.json

test(cli): apiv2 support for policy integration

---

api/api.go
api/lql_validate.go
api/lql_validate_test.go
cli/cmd/lql.go
cli/cmd/lql_create.go
cli/cmd/lql_delete.go
cli/cmd/lql_update.go
cli/cmd/lql_validate.go
integration/lql_create_test.go
integration/lql_test.go
integration/lql_update_test.go
integration/lql_validate_test.go

feat(cli): apiv2 support for query validate

---

cli/cmd/compliance_gcp.go

fix: Output gcp comp list with --json flag

---

api/policy.go

fix(cli): evalFrequency optional for policyCreate

---

integration/container_vulnerability_test.go

Closes https://github.com/lacework/go-sdk/issues/399

test(cli): re-enable on-demand ctr scans

---

scripts/release.sh

ci: sign lacework-releng commits

---

integration/test_resources/policy/lacework-clitest-1.json

Policy guardrails dictate we specify partial policy id
ALLY-584

test(cli): updating policy integration resource

---

api/alert_channels.go
api/alert_channels_test.go
api/api.go

https://lacework.atlassian.net/browse/ALLY-331
Add V2 Alert Channel Test function to api.go

feat: Add apiV2AlertChannelTest

---

api/policy.go
cli/cmd/integration.go
cli/cmd/lql.go
cli/cmd/lql_create.go
cli/cmd/lql_delete.go
cli/cmd/lql_list.go
cli/cmd/lql_show.go
cli/cmd/lql_update.go
cli/cmd/lql_validate.go
cli/cmd/policy.go
cli/cmd/policy_create.go
cli/cmd/policy_update.go

JIRA: https://lacework.atlassian.net/browse/ALLY-600

docs(cli): add inline help docs for query/policy cmds

---

api/alert_channels.go
api/alert_channels_aws_s3.go
api/alert_channels_aws_s3_test.go
api/alert_channels_email_user_test.go
api/alert_channels_slack_channel.go
api/alert_channels_slack_channel_test.go
api/alert_channels_test.go
cli/cmd/integration_email.go

**Contributes** to https://github.com/lacework/terraform-provider-lacework/issues/147
**JIRA** https://lacework.atlassian.net/browse/ALLY-614

Migrate a few alert channels to v2

---

cli/cmd/lql.go

Relocating cli start/stop progress for lacework query run
ALLY-615

fix(cli): query run via editor

---

cli/cmd/vuln_container.go
cli/cmd/vulnerability.go

Add new scan status case, "Partial"

fix(cli): handle scan status 'Partial'

---

api/policy.go
api/policy_test.go
cli/cmd/policy.go
cli/cmd/policy_create.go
cli/cmd/policy_create_internal_test.go
cli/cmd/policy_update_internal_test.go
integration/lql_create_test.go
integration/lql_update_test.go
integration/policy_test.go
integration/test_resources/policy/lacework-clitest-1.json

Removing policyUi from all structures and tests
ALLY-612

fix(cli): removing policyUi from policy schema

---

cli/cmd/compliance.go
cli/cmd/compliance_aws.go
cli/cmd/compliance_azure.go
cli/cmd/compliance_gcp.go

Updating the CLI CSV output of the compliance reports to closely resemble the CSV exports from UI
JIRA: https://lacework.atlassian.net/browse/ALLY-534

feat(cli): More detailed CSV compliance reports

---

Makefile

test(cli): re-enable query/policy integration

---

integration/container_vulnerability_test.go

test(cli): disable vuln ctr scan tests

---

cli/cmd/cli_state.go
cli/cmd/migration.go
cli/cmd/root.go

feat(cli): switch over to API v2 by default

---

integration/container_vulnerability_test.go

Reverts https://github.com/lacework/go-sdk/pull/530
We are back on <5m 🙌🏽

test(cli): enable vuln ctr scan tests

---

cli/install.ps1

Closes https://github.com/lacework/go-sdk/issues/531

fix(install.ps1): Force Set-Variable as Constant

---

api/resource_groups.go
api/resource_groups_aws.go
api/resource_groups_aws_test.go
api/resource_groups_azure.go
api/resource_groups_azure_test.go
api/resource_groups_container.go
api/resource_groups_container_test.go
api/resource_groups_gcp.go
api/resource_groups_gcp_test.go
api/resource_groups_lw_account.go
api/resource_groups_lw_account_test.go
api/resource_groups_machine.go
api/resource_groups_machine_test.go

Add specific Create functions for each resource group, to return specific type and props.

feat: Add resource group specific create functions

---

cli/cmd/resource_group_aws.go
cli/cmd/resource_group_azure.go
cli/cmd/resource_group_container.go
cli/cmd/resource_group_gcp.go
cli/cmd/resource_group_lw_account.go
cli/cmd/resource_group_machine.go
cli/cmd/resource_groups.go

Fix resource groups cli json output

fix: Output correct resource group json

---

api/container_registries_gcp_gar.go
api/container_registries_ghcr.go
api/integrations_ctr_reg_ecr_access_key.go
cli/cmd/integration_docker_hub.go
cli/cmd/integration_docker_v2.go
cli/cmd/integration_ecr.go
cli/cmd/integration_gar.go
cli/cmd/integration_gcr.go
cli/cmd/integration_ghcr.go

***Issue***: https://lacework.atlassian.net/browse/ALLY-666
Add NonOSPackageSupport option to ctr registries:

feat: Add NonOSPackageSupport container registries

---

api/alert_channels.go
api/alert_channels_test.go
api/alert_channels_webhook.go
api/alert_channels_webhook_test.go
cli/cmd/integration_webhook.go

***Issue***: https://lacework.atlassian.net/browse/ALLY-651
Migrate the Webhook alert channel to use the V2 API.

feat(api): Webhook alert channel(v2)

---

api/_examples/aws-cloudwatch-alert-channel/main.go
api/_examples/aws-s3-alert-channel/main.go
api/_examples/slack-alert-channel/main.go
api/_examples/webhook-alert-channel/main.go
cli/cmd/integration_aws_cloudwatch.go
cli/cmd/integration_aws_s3_channel.go
cli/cmd/integration_slack_channel.go

Update the cli commands for a few alert channels and the examples. 
Existing test should pass and I manually created a few alert channels via the cli
https://lacework.atlassian.net/browse/ALLY-695?atlOrigin=eyJpIjoiMjAyOTBlYmZhOGIxNDJjNTljY2Q3NzIyMDdmMmM1NDMiLCJwIjoiaiJ9

chore(cli): Update s3, slack, and cloudwatch alert channels cli commands to point to API v2

---

api/_examples/report-rules/main.go
api/api.go
api/report_rule_notification_types.go
api/report_rule_notification_types_test.go
api/report_rules.go
api/report_rules_test.go
api/schemas.go
api/v2.go

New Report Rules service added to go-sdk .
New unit tests
`/api/report_rules_test.go`
Run example in 
`api/_examples/report-rules/main.go`
https://lacework.atlassian.net/browse/ALLY-739

feat(api): Report Rules v2 Service

---

integration/test_resources/lacework_env/integrations/integrations.tf

ci: add Azure integration as a test resource

---

go.mod

Update the minimum go version in go.mod

chore: Update minimum go version -> 1.17

---

cli/docs/lacework_account.md
cli/docs/lacework_account_list.md
cli/docs/lacework_alert-rule.md
cli/docs/lacework_alert-rule_create.md
cli/docs/lacework_alert-rule_delete.md
cli/docs/lacework_alert-rule_list.md
cli/docs/lacework_alert-rule_show.md
cli/docs/lacework_compliance_google_list.md
cli/docs/lacework_policy.md
cli/docs/lacework_policy_create.md
cli/docs/lacework_policy_delete.md
cli/docs/lacework_policy_list.md
cli/docs/lacework_policy_show.md
cli/docs/lacework_policy_update.md
cli/docs/lacework_query.md
cli/docs/lacework_query_create.md
cli/docs/lacework_query_delete.md
cli/docs/lacework_query_list-sources.md
cli/docs/lacework_query_list.md
cli/docs/lacework_query_run.md
cli/docs/lacework_query_show-source.md
cli/docs/lacework_query_show.md
cli/docs/lacework_query_update.md
cli/docs/lacework_query_validate.md
cli/docs/lacework_resource-group.md
cli/docs/lacework_resource-group_create.md
cli/docs/lacework_resource-group_delete.md
cli/docs/lacework_resource-group_list.md
cli/docs/lacework_resource-group_show.md
cli/docs/lacework_vulnerability_container_list-assessments.md

docs: Vuln ctr list-assessments registry flag

---

cli/cmd/vuln_host.go
cli/cmd/vuln_host_test.go
cli/cmd/vulnerability_test.go

The UI today doesn't display any vulnerability that has been fixed but
the APIs return them, this is causing confusion, to fix this issue we
are filtering all of those "Fixed" vulnerabilities.
I checked a number of Host Vuln Assessments, though, I am hoping to add a few unit tests.
* https://lacework.atlassian.net/browse/ALLY-767
* https://lacework.zendesk.com/agent/tickets/4834

fix(cli): avoid using "Fixed" host vulnerabilities

---

cli/cmd/cache.go
cli/cmd/cache_test.go
cli/cmd/vuln_host.go

Introducing a simple private struct that acks as an envelope for storing
assets that has an expiration time into the local cache named `cliAsset`.
The `Data` field is an interface on purpose to allow developers to store
any kind of asset, from primitives such as strings, ints, bools, to JSON
objects.
The new function called `WriteAssetToCache` stores an asset with an
expiration time.
**Simple Example:** Having a struct named `vulnReport`
```go
cli.WriteAssetToCache("my-report", time.Now().Add(time.Hour * 1), vulnReport{Foo: "bar"})
```
The funciton `ReadCachedAsset` tries to reads an asset with an expiration
time, if the asset has expired, it returns `true`, otherwise it returns
`false`.
**Simple Example:** Having a struct named `vulnReport`
```go
var report vulnReport
if expired := …
```

feat(cli): logic to store assets with expiration time

---

api/_examples/report-rules/main.go
api/report_rule_notification_types.go
api/report_rule_notification_types_test.go

fix: report rule notifications

---

cli/cmd/alert_rules.go
cli/cmd/report_rules.go
cli/cmd/report_rules_test.go
integration/container_vulnerability_test.go
integration/global_flags_test.go
integration/help_test.go
integration/integration_test.go
integration/policy_test.go

Manage Report Rules in the Lacework cli
Manually run `lacework report-rule create | list | show | delete`
https://lacework.atlassian.net/browse/ALLY-765

feat(cli): Manage Report Rules

---

api/_examples/team-members-org/main.go
api/_examples/team-members/main.go
api/api.go
api/client.go
api/client_test.go
api/team_members.go
api/team_members_test.go
api/v2_search_filters.go

Implement CRUD operations on org level team members. 
There are tests in addition to an example file that calls most of the methods. 
https://lacework.atlassian.net/browse/ALLY-766?atlOrigin=eyJpIjoiNmFjYWE2NjkzZDdmNDQ1MWExNWFjMTdhOTc3NmFlMGMiLCJwIjoiaiJ9

feature(api): implement crud operations for org team member

---

integration/aws_generation_test.go
integration/test_resources/lacework_env/integrations/agent.tf
integration/test_resources/lacework_env/integrations/variables.tf

We have reached the limit of VPCs in our AWS account and instead of creating new ones, this code is trying to reuse an existing VPC for multiple environments.
About to run the prepare-integrations pipeline in Codefresh...
N/A

refactor(test_resources): remove Terraform code dep

---

cli/cmd/generate.go

Improve docs for `ca iac aws`
N/A

docs(cli): Improve iac-generate/aws help text

---

integration/aws_generation_test.go
integration/configure_unix_test.go
integration/configure_windows_test.go
integration/lql_create_test.go
integration/lql_test.go
integration/lql_update_test.go
integration/lql_validate_test.go
integration/policy_test.go
scripts/codefresh.ps1

As a Lacework Engineer,
I want to test the Lacework CLI in Windows systems,
So I can verify compatibility of every change I deliver
Create a pipeline that uses the new Windows system in Codefresh to run the Lacework CLI integration tests.
Created a new pipeline and run it:
https://lacework.atlassian.net/browse/ALLY-803

ci: test on windows systems 

---

api/container_registries_ghcr.go
api/container_registries_ghcr_test.go
api/integrations_ctr_reg.go
api/integrations_ctr_reg_ecr_access_key.go
api/integrations_ctr_reg_ecr_access_key_test.go
api/integrations_ctr_reg_test.go

Remove omitempty from no_os_package_support field

fix: non_os_package_support omitted from json request when false

---

lwgenerate/_examples/gcp/main.go
lwgenerate/aws/aws.go
lwgenerate/constants.go
lwgenerate/gcp/gcp.go
lwgenerate/gcp/gcp_test.go
lwgenerate/hcl.go

Add initial support for Terraform code generation for GCP
Added unit tests. Coverage is now at 92%
https://lacework.atlassian.net/browse/ALLY-393

feat(lwgenerate): Add initial hcl generation support GCP - ALLY-393

---

integration/host_vulnerability_test.go

test: fix host vuln test

---

cli/cmd/lacework_content_library.go
cli/cmd/lql.go
cli/cmd/lql_list.go

Add library flag for query list
```
lacework query list --library
```
Unit tests added
Manual tests performed
https://lacework.atlassian.net/browse/ALLY-812

feat(cli): add library flag for query list

---

api/lql.go
api/lql_test.go
cli/cmd/lacework_content_library.go
cli/cmd/lacework_content_library_internal_test.go
cli/cmd/lacework_content_library_test.go
cli/cmd/lql.go
cli/cmd/lql_create.go
cli/cmd/lql_internal_test.go
cli/cmd/lql_list.go
cli/cmd/lql_show.go
cli/cmd/lql_update.go
cli/cmd/lql_validate.go

Add library flag for query show
```
lacework query show LW_Custom_Host_Activity_CodecovCurl --library  
```
Unit tests added
Manual tests performed
https://lacework.atlassian.net/browse/ALLY-832

feat(cli): add library flag for query show

---

cli/cmd/lacework_content_library.go
cli/cmd/lacework_content_library_test.go
cli/cmd/policy.go

feat(cli): add support for policy list from library
```
lacework policy list --library
```
Automated testing added
Manual testing performed
https://lacework.atlassian.net/browse/ALLY-842

feat(cli): add support for policy list from library

---

cli/cmd/component.go
lwcomponent/component.go
lwcomponent/component_internal_test.go
lwcomponent/component_test.go
lwcomponent/state

Permit lwcomponent package consumers to easily determine if state contains a particular component, and what the status of that component is...
Automated testing added
https://lacework.atlassian.net/browse/ALLY-811

feat(lwcomponent): GetComponent method

---

cli/cmd/lacework_content_library_test.go
lwcomponent/component.go
lwcomponent/component_internal_test.go
lwcomponent/component_test.go
lwcomponent/state

Use .version file on disk for establishing CurrentVersion()
Add version to Artifacts
Rename Component version to LatestVersion
Automated testing added
https://lacework.atlassian.net/browse/ALLY-831

feat(lwcomponent): handling of component versions

---

cli/cmd/policy_create.go
cli/cmd/policy_update.go

When creating a policy attempt to create the query
```
lacework policy create --library lwcustom-18
The query LW_Custom_AWS_CTA_CloudTrailCSVMaliciousFormula was created.
The policy dev7-lwcustom-18 was created.
```
When updating a policy attempt to update the query
```
lacework policy update --library lwcustom-18
The query LW_Custom_AWS_CTA_CloudTrailCSVMaliciousFormula was updated.
The policy dev7-lwcustom-18 was updated.
```
Manually
https://lacework.atlassian.net/browse/ALLY-853

feat(cli): cascading policy create/update

---

cli/cmd/alert_rules.go
cli/cmd/lql_delete.go
cli/cmd/policy_delete.go
cli/cmd/report_rules.go
cli/cmd/resource_groups.go
cli/cmd/vuln_host.go
cli/cmd/vulnerability_exception_container.go
cli/cmd/vulnerability_exception_host.go
cli/cmd/vulnerability_exceptions_test.go
cli/cmd/vulnerabilty_exceptions.go
integration/help_test.go

Manage Vulnerability Exceptions in the CLI
```
lacework vulnerability-exceptions create
lacework vulnerability-exceptions list
lacework vulnerability-exceptions show <id>
lacework vulnerability-exceptions delete <id>
```
run `lacework vulnerability-exceptions create | list | show | delete`
add unit test `cli/cmd/vulnerability_exceptions_test.go`
https://lacework.atlassian.net/browse/ALLY-752

feat(cli): Manage Vulnerability Exceptions

---

cli/cmd/lql_sources.go

Add breadcrumb to list-sources command. When the list-sources command is run we add an output to give users info on what can be done next with the information fetched from the previous command.
```
❯ lacework query list-sources
DATASOURCE                                    DESCRIPTION                 
---------------------------------------------------+-------------------------------------------
Use 'lacework query show-source <datasource_id>' to show details about the data source.
```
Run `lacework query list-sources`
https://lacework.atlassian.net/browse/ALLY-805

feat(cli): add breadcrumb to query list-sources cmd

---

Makefile
cli/cmd/team_members.go
cli/cmd/team_members_test.go
integration/help_test.go
integration/team_members_test.go

Manage Team Members in the CLI
```
lacework team-members create
lacework team-members list
lacework team-members show <id>
lacework team-members delete <id>
```
run lacework tm create | list | show | delete
add unit test -> go-sdk/cli/cmd/team_members_test.go
test for org level
run lacework tm create | list | show | delete --organization
https://lacework.atlassian.net/browse/ALLY-815

feat(cli): Manage Team Members

---

cli/cmd/vulnerability_exceptions_test.go
cli/cmd/vulnerabilty_exceptions.go

Change vulnerability_expections `packages` field  from outputting as json to human readable table.
*Old Output
`    PACKAGES        [{"myPackage":["1.2.3"]}]     `
*New Output
```
PACKAGES               
-------------------------------------
NAME          VERSIONS      
-----------------+---------------  
myPackage        1.0.0, 2.0.0    
myOtherPackage   1.0.0     
```
Run `lacework ve show <id>`
Update `go-sdk/cli/cmd/vulnerability_exceptions_test.go`
/Users/darrenmurray/go/src/github.com/lacework/go-sdk/cli/cmd/vulnerability_exceptions_test.go

refactor(cli): vulnerability_expections packages human readable output

---

Makefile

Disable policy integration tests
Automated integration tests
https://lacework.atlassian.net/browse/RAIN-28560

test(lql): disable policies tests

---

Makefile
integration/compliance_azure_test.go
integration/host_vulnerability_test.go

Fix the host select to use the online machine only
Correct the LW_INT_TEST_AWS_ACC 
https://g.codefresh.io/build/62245a6bbfbdf112135853e7?step=IntegrationTests&tab=output&logs=terminal

fix: use online machine for testing

---

go.mod

ci: fix release pipeline

---

api/vulnerabilities_host.go
integration/host_vulnerability_test.go
integration/lql_list_test.go

A quick PR to fix a few QA tests.

ci: fix qa tests

---

cli/cmd/lacework_content_library.go

Use pointer receivers for LCL methods
Existing automated integration testing
https://lacework.atlassian.net/browse/ALLY-847

fix(lcl): use pointer receivers for LCL methods

---

CONTRIBUTING.md

chore: deprecate CLI Wiki

---

api/vulnerabilities_container.go
cli/cmd/errors.go
cli/cmd/errors_test.go

When no vulns are found VulnContainerImage is nil.
Add new unit test `cli/cmd/errors_test.go:85`
https://lacework.atlassian.net/browse/ALLY-948

fix: fix fail_on_severity when no vulns are found

---

Makefile

ci: add make cmd for output go tests in junit format

---

cli/cmd/alert_rules.go
cli/cmd/report_rules.go
cli/cmd/resource_groups.go
cli/cmd/team_members.go
cli/cmd/vulnerabilty_exceptions.go
integration/test_resources/help/alert-rule_delete
integration/test_resources/help/alert-rule_show
integration/test_resources/help/report-rule_delete
integration/test_resources/help/report-rule_show
integration/test_resources/help/resource-group_delete
integration/test_resources/help/resource-group_show
integration/test_resources/help/team-member_delete
integration/test_resources/help/team-member_show
integration/test_resources/help/vulnerability-exception_delete
integration/test_resources/help/vulnerability-exception_show

We missed documenting properly all of these commands. 
Updated help messages in our integration tests.
https://lacework.atlassian.net/browse/ALLY-975

fix(cli): command arguments

---

integration/lql_constants.go
integration/policy_test.go
integration/test_resources/lql/CLI_Host_Files_IntegrationTest.yaml

The LQL "Host" tests are mixing up case `Host` vs. `HOST`
Automated Integration
N/A

test(lql): fix case issue with host tests

---

api/_examples/alert-profiles/main.go
api/alert_profiles.go
api/alert_profiles_test.go
api/alert_templates.go
api/api.go
api/schemas.go
api/v2.go

New Alert Profiles service added to go-sdk .
Run `_examples/alert_profiles/main.go`
Unit Test `api/alert_profiles_test.go`
https://lacework.atlassian.net/browse/ALLY-979

feat(api): AlertProfiles v2 service

---

cli/cmd/generate_aws.go
cli/cmd/generate_aws_test.go
integration/aws_generation_test.go
integration/test_resources/help/cloud-account_iac-generate_aws
lwgenerate/aws/aws.go

Bug: lacework cloud-account iac-generate awson a new AWS account via Cloud Shell, after accepting to do config and cloudtrail:
```
ERROR failed to run terraform apply: exit status 1
Error: error configuring Terraform AWS Provider: failed to get shared config profile, default
with provider["[registry.terraform.io/hashicorp/aws|http://registry.terraform.io/hashicorp/aws]"],
on [main.tf|http://main.tf] line 10, in provider "aws":
10: provider "aws" {
```
Updated unit & integration tests to reflect the change ✅ 
Tested CLI locally ✅
https://lacework.atlassian.net/browse/ALLY-980

fix(cli): Remove aws profile "default"

---

cli/cmd/compliance_aws.go

As a user I would like to fully understand the implications of compliance report disable and be able to abandon ship if necessary.
Manually
https://lacework.atlassian.net/browse/ALLY-989

feat(cli): add compliance report disable warning

---

cli/cmd/alert_profiles.go
cli/cmd/alert_profiles_test.go
integration/test_resources/help/alert-profile
integration/test_resources/help/alert-profile_create
integration/test_resources/help/alert-profile_delete
integration/test_resources/help/alert-profile_list
integration/test_resources/help/alert-profile_show
integration/test_resources/help/no-command-provided

Add alert profile commands to cli.
`lacework alert-profile list`
`lacework alert-profile show <id>`
`lacework alert-profile delete <id>`
`lacework alert-profile create`
Manually run commands
Add unit test `cmd/alert_profile_test.go`
https://lacework.atlassian.net/browse/ALLY-962

feat(cli): alert profiles command

---

api/vulnerability_exceptions.go
api/vulnerability_exceptions_test.go

fix time format for expiry time
relates to https://github.com/lacework/terraform-provider-lacework/pull/316

fix: expiration time format

---

cli/cmd/agent_list.go

Simple style change that fixes a missing carrier return.
Tested locally.
N/A

style(cli): add missing carrier return

---

api/_examples/policy-exceptions/main.go
api/api.go
api/policy.go
api/policy_exceptions.go
api/policy_exceptions_test.go
api/v2.go

Add new policy exceptions service to interact with `v2/Exceptions` schema
Manually run `examples/policy_exceptions/main.go`
Add unit tests
https://lacework.atlassian.net/browse/ALLY-1046

feat(api): add policy exceptions service

---

api/vulnerabilities_container.go
api/vulnerabilities_container_test.go
cli/cmd/vulnerability_test.go

Quick fix of a misspelled field.
Updated test.
JIRA: https://lacework.atlassian.net/browse/ALLY-1057

fix: misspelled namespace field

---

api/cloud_accounts_gcp_gke_audit.go

Noticed this casing issue when debugging an issue in the Lacework Terraform Provider PR: https://github.com/lacework/terraform-provider-lacework/pull/327
When this reaches the LW API it ends up as `PRIVATE_KEY_I_D` which is not a supported field. It should be `PRIVATE_KEY_ID`. This is likely down to the casing issue here.

fix(GcpGkeAudit): Casing issue with PrivateKeyId & PrivateKeyId

---

scripts/chocolatey/build/lacework-cli.nuspec

fix(cli): Fix icon, desc and summary of .nuspec file

---

api/policy.go
cli/cmd/policy.go
cli/cmd/policy_delete.go
cli/cmd/policy_library.go
cli/cmd/policy_update.go
integration/policy_test.go
integration/test_resources/help/policy
integration/test_resources/help/policy_disable
integration/test_resources/help/policy_enable
integration/test_resources/help/policy_list
integration/test_resources/help/policy_show

populate the text editor with existing policy when performing an update via cli and text editor
run lacework policy update <policy_id>
https://lacework.atlassian.net/browse/ALLY-1034

feat(cli): fetch existing policy for cli update

---

api/_examples/cloud-accounts/aws-agentless-scanning/main.go
api/cloud_accounts.go
api/cloud_accounts_aws_agentless_scanning.go
api/cloud_accounts_aws_sidekick.go

Add new cloud account for aws agentless scanning
Run `api/_examples/cloud-accounts/aws-agentless-scanning/main.go`
https://lacework.atlassian.net/browse/ALLY-1100

feat: add cloud account integration aws agentless scanning

---

cli/cmd/alert_profiles.go
cli/cmd/alert_profiles_test.go
cli/cmd/lql.go
cli/cmd/lql_create.go
cli/cmd/lql_preview.go
cli/cmd/lql_sources.go
cli/cmd/lql_update.go
cli/cmd/policy.go
cli/cmd/policy_create.go
cli/cmd/policy_exceptions.go
cli/cmd/policy_library.go
cli/cmd/policy_update.go
integration/lql_create_unix_test.go
integration/lql_preview_test.go
integration/test_resources/help/alert-profile
integration/test_resources/help/policy
integration/test_resources/help/policy-exception_create
integration/test_resources/help/policy-exception_delete
integration/test_resources/help/policy_create
integration/test_resources/help/policy_disable
integration/test_resources/help/policy_enable
integration/test_resources/help/policy_update
integration/test_resources/help/query
integration/test_resources/help/query_create
integration/test_resources/help/query_list-sources
integration/test_resources/help/query_preview-source
integration/test_resources/help/query_run
integration/test_resources/help/query_show-source
integration/test_resources/help/query_update

Update help messages and user-facing output from all LPP commands.
Updated pipeline tests.
N/A

docs(cli): update help message from LPP commands

---

api/cloud_accounts_aws_sidekick.go

Add credential fields for aws sidekick data

feat: add credentials to sidekick data

---

api/_examples/data-export-rules/main.go
api/api.go
api/data_export_rules.go
api/v2.go

Add new v2 service DataExportRule
Run new examples `api/_examples/data-export-rules/main.go`
https://lacework.atlassian.net/browse/ALLY-1150

feat: DataExportRule service

---

.gitignore
cli/cmd/generate.go
cli/cmd/generate_aws.go
integration/aws_generation_test.go
integration/test_resources/help/cloud-account_iac-generate_aws
lwgenerate/aws/aws.go
lwgenerate/aws/aws_test.go

This change was made to increase the ability to configure AWS Config and CloudTrail options in the CLI to generate the necessary Terraform. This was led by the scenarios laid out here https://docs.lacework.com/onboarding/aws-cloudtrail-integration-with-terraform. The reasoning being that rather than give Terraform examples to cut'n'paste and then update for each scenario, that this Terraform could be generated by the CLI tool making it easier for the user and less error prone
Updates to the Unit tests and Integration tests for the AWS generation were made to cover the new functionality. Also manual testing of the CLI was made to ensure the command line options using the `noninteractive` mode to ensure that the correct Terraform was generated. …

feat(cli): Addition of extra AWS terraform options

---

api/data_export_rules.go

Add description field to data export rules

fix: add description field to dataexportrules

---

api/data_export_rules.go

omit profile versions field when empty

fix: omitempty profileVersions field

---

api/api.go
api/compliance_evaluations.go
api/compliance_evaluations_aws.go
api/inventory.go
api/inventory_aws.go
api/inventory_aws_test.go
api/inventory_test.go
api/v2.go
cli/cmd/compliance_aws.go
cli/cmd/compliance_azure.go
cli/cmd/compliance_gcp.go
integration/compliance_aws_test.go
integration/test_resources/help/compliance_aws_get-report
integration/test_resources/help/compliance_aws_search
integration/test_resources/help/compliance_azure_get-report
integration/test_resources/help/compliance_google_get-report

Add new ` compliance aws search <resource_arn>` command
```
❯ lacework comp aws search arn:aws:s3:::my-bucket
RECOMMENDATION ID    ACCOUNT ID                REASON               SEVERITY      STATUS     
--------------------+--------------+--------------------------------+----------+---------------
LW_S3_12            123456789   S3 bucket does not have MFA      Medium     NonCompliant  
delete enabled                 
```                                                             
Returns all violations for a given resource.
Run `lacework comp aws search <arn>`
https://lacework.atlassian.net/browse/ALLY-1108

feat(cli): aws compliance search command

---

Makefile
integration/container_vulnerability_test.go

Disabling test until https://lacework.atlassian.net/browse/RAIN-37563 is resolved

test: disable list-registries integration test

---

api/container_registries_dockerhub_v2.go

Correct DockerhubV2Data fields
https://lacework.atlassian.net/browse/ALLY-1137

fix: DockerhubV2Data fix fields

---

api/container_registries_gcp_gcr.go
cli/cmd/integration_gcr.go

fix: gcr limitByRep json field name

---

lwcomponent/component.go

This feature is adding the ability to enter development mode of one CDK component at a time. To do so, developers need to export the environment variable `LW_CDK_DEV_COMPONENT`
Example:
```
$ export LW_CDK_DEV_COMPONENT=new-component
$ lacework component list
```
That should show you the following output:
```
STATUS           NAME        VERSION                                       DESCRIPTION
----------------+---------------+---------+---------------------------------------------------------------------------------------
Not Installed   new-component   0.0.0     create dev specs file '/Users/afiune/.config/lacework/components/new-component/.dev'
Components version: 0.2.0
```
Then you just need to create the dev specs file that contains all the specifications of your dev component. …

feat(cdk): component dev mode

---

cli/cmd/generate_aws.go
cli/cmd/generate_azure.go

CLI command, generate Azure TF, wasn't making use of the values loaded from cache.
- unit testing
- integration testing
- manual testing
[ALLY-1217](https://lacework.atlassian.net/browse/ALLY-1217)

fix: azure interactive caching

---

cli/cmd/agent_install_ec2ic.go
cli/cmd/agent_install_ec2ssh.go
cli/cmd/aws.go
integration/test_resources/help/agent_aws-install
integration/test_resources/help/agent_aws-install_ec2ic
integration/test_resources/help/agent_aws-install_ec2ssh

Also renames `ec2-ssh` to `ec2ssh`.
Fixes RAIN-38676
Thanks Selva for pointing out these little tweaks in the help text!
Updated integration tests with new text
https://lacework.atlassian.net/browse/RAIN-38676

fix(cli): update `aws-install` command in help msg

---

cli/cmd/agent_install_ec2ic.go
cli/cmd/agent_install_ec2ssh.go
integration/test_resources/help/agent_aws-install_ec2ic
integration/test_resources/help/agent_aws-install_ec2ssh
lwrunner/awsrunner.go

This commit:
* Removes the `--token` flags and makes it a mandatory argument
* Adds a `Region` field to the `DescribeImages`
config to prevent crashes.
This reverts commit 6b983fe69537c7f8601c20bd038c0d90c25ca925.
CTF integration tests pass with the region fix, they were failing before. Help text integration tests are passing.
https://lacework.atlassian.net/browse/RAIN-38750

Change token from flag into arg for `aws-install`, region fix

---

api/_examples/reports/aws/main.go
api/_examples/reports/azure/main.go
api/_examples/reports/gcp/main.go
api/api.go
api/reports.go
api/reports_aws.go
api/reports_azure.go
api/reports_gcp.go
api/reports_test.go
api/v2.go

Add new reports service to read reports from `v2/Reports` api
Add unit tests `reports_test.go`
https://lacework.atlassian.net/browse/ALLY-1215

feat: new v2 reports service

---

.github/pull_request_template.md

Minor typo in pull request template
N/A
https://lacework.atlassian.net/browse/ALLY-1240

build: fix minor typo in pull request template

---

Makefile
cli/cmd/root.go
lwgenerate/gcp/gcp.go

chore: bump golangci-lint to 1.50.0

---

api/reports_azure.go
api/reports_gcp.go

fix gcp/azure --type flag inputs

fix: fix gcp/azure type flag

---

api/alerts.go
api/alerts_details_integrations.go
api/alerts_details_integrations_test.go
api/alerts_details_related.go
api/alerts_details_timeline.go
cli/cmd/alert.go
cli/cmd/alert_list.go
cli/cmd/alert_show.go
cli/cmd/alert_show_details.go
cli/cmd/alert_show_events.go
cli/cmd/alert_show_integrations.go
cli/cmd/alert_show_investigation.go
cli/cmd/alert_show_related.go
cli/cmd/alert_show_timeline.go
integration/alert_close_test.go
integration/alert_comment_test.go
integration/alert_list_test.go
integration/alert_show_test.go
integration/test_resources/help/alert
integration/test_resources/help/alert_show

Adding `alert show <alert_id> --scope <scope>`
Integration testing
https://lacework.atlassian.net/browse/ALLY-1235

feat(cli): adding alert show command

---

Makefile

Reverts https://github.com/lacework/go-sdk/pull/964
Merge once the pipeline is greeeeeen. 😂 

test(cli): enable compliance tests

---

api/alerts.go
api/alerts_test.go
cli/cmd/alert_list.go

Add paging for listing alerts
Unit testing
https://lacework.atlassian.net/browse/ALLY-1239

feat(cli): add paging for alerts listing

---

api/api.go
api/v2_vulnerabilities.go
api/v2_vulnerabilities_software_packages.go
cli/cmd/package_manifest.go
cli/cmd/package_manifest_test.go
cli/cmd/vuln_host.go
cli/cmd/vuln_host_test.go
integration/test_resources/help/vulnerability_host_list-hosts
integration/test_resources/help/vulnerability_host_scan-pkg-manifest
internal/array/sort.go

Migrate commands to v2: 
`lacework vuln host list-cves`
`lacework vuln host list-hosts `
`lacework vuln host scan-pkg-manifest`
`lacework vuln host show-assessment`
Update existing tests
https://lacework.atlassian.net/browse/ALLY-1147

refactor(cli): migrate vuln host cmds to use v2

---

cli/cmd/generate_aws_eks_audit.go
integration/aws_eks_audit_generation_test.go
integration/framework_test.go
integration/test_resources/help/generate_k8s_eks
lwgenerate/aws_eks_audit/aws_eks_audit.go

Feat: AWS EKS Audit log integration tests

---

cli/cmd/component.go

Fixes CI linting issue.
CI should be green now.
N/A

fix(lint): redundant break statement

---

integration/component_test.go

We just released our first component and these tests now see our new IaC component.
CI should be happy/green!
N/A

test(cdk): fix tests due to IaC component release

---

cli/cmd/compliance.go
cli/cmd/errors.go
cli/cmd/event.go
cli/cmd/policy.go
cli/cmd/vuln_container.go
lwseverity/severity.go
lwseverity/severity_test.go

As a Lacework developer I would like a package to make working with Lacework severities easy as pie (or tacos).
- Normalizing
- Sorting
- Filtering
Unit testing
https://lacework.atlassian.net/browse/ALLY-1263

feat: lwseverity package

---

api/_examples/report-definitions/main.go
api/api.go
api/reports_aws.go
api/reports_azure.go
api/reports_definitions.go
api/reports_gcp.go
api/v2.go
cli/cmd/compliance.go
cli/cmd/compliance_aws.go
cli/cmd/compliance_azure.go
cli/cmd/compliance_gcp.go
cli/cmd/report_definitions.go
cli/cmd/report_definitions_test.go
cli/cmd/root.go
cli/main.go
integration/compliance_aws_test.go
integration/host_vulnerability_test.go
integration/report_definitions_test.go
integration/test_resources/help/compliance_aws_get-report
integration/test_resources/help/compliance_azure_get-report
integration/test_resources/help/compliance_google_get-report
integration/test_resources/help/no-command-provided
integration/test_resources/help/report-definition
integration/test_resources/help/report-definition_delete
integration/test_resources/help/report-definition_list
integration/test_resources/help/report-definition_show
lwcomponent/error.go
lwcomponent/executable.go

New v2 ReportDefinitions Service to interact with ReportDefintions api
https://lacework.atlassian.net/browse/ALLY-1244

feat(api): new v2 ReportDefinitions service

---

cli/cmd/cache.go

Logic was recently added to refresh eminent/expired tokens.  This logic does not take into consideration whether or not we actually have a cached token…
Manually
https://lacework.atlassian.net/browse/ALLY-1278

fix(cli): minor fix related to refreshing tokens 

---

api/api.go
api/v2.go
api/v2_configs.go
api/v2_configs_azure.go
api/v2_configs_gcp.go
cli/cmd/compliance_aws.go
cli/cmd/compliance_aws_test.go
cli/cmd/compliance_azure.go
cli/cmd/compliance_azure_test.go
cli/cmd/compliance_gcp.go
cli/cmd/compliance_gcp_test.go
integration/compliance_gcp_test.go
integration/test_resources/help/compliance_azure
integration/test_resources/help/compliance_azure_list-subscriptions

Update the following commands to use the v2 api
`lacework compliance aws list`
`lacework compliance gcp list`
`lacework compliance gcp list-projects <orgID>`
`lacework compliance azure list`
`lacework compliance azure list-subscriptions <tenantID>`
Add new v2 service `v2configService` to interact with `v2/api/Configs/AzureSubscriptions` `v2/api/Configs/GcpProjects`
Manaully run commands
Check existing test pass
https://lacework.atlassian.net/browse/ALLY-1213

refactor(cli): migrate compliance list-accounts to use v2 api 

---

cli/cmd/compliance_aws.go
cli/cmd/compliance_azure.go
cli/cmd/compliance_gcp.go
integration/test_resources/help/compliance_aws
integration/test_resources/help/compliance_google

Remove the experimental bulk enable/disable of reports
They rely on v1 api. 
https://lacework.atlassian.net/browse/ALLY-1289

refactor(cli): Remove experimental disable/enable reports commands

---

scripts/release.sh

ci: add logging line to output latest version found

---

cli/cmd/agent_aws-install_ec2ic.go
cli/cmd/agent_aws-install_ec2ssh.go
lwrunner/awsrunner.go
lwrunner/awsrunner_test.go

This commit fixes an error in the CLI where the SSH user was set
incorrectly for Amazon Linux 2. This commit also adds a new unit test to
verify this case. This commit also adds debug logs for the AMI for each
instance captured to give more visibility for these types of problems in
the future.
Fixes RAIN-43934
Adding an integration test in the agent repo to test this capability, will link it to this PR once it's written.
https://lacework.atlassian.net/browse/RAIN-43934

fix(cli): set correct SSH user for Amazon Linux 2

---

go.mod

Commits the result of running `make go-vendor` to get our release working again.

chore(deps): Run `make go-vendor`

---

scripts/chocolatey/build/tools/chocolateyinstall.ps1
scripts/chocolatey/package.ps1

Update chocolatey CI scripts
Run the chocolatey pipeline with the updated scripts 
https://g.codefresh.io/build/63b434ab2ad6eee05da3c2a0
https://community.chocolatey.org/packages/lacework-cli/1.4.0
https://lacework.atlassian.net/browse/GROW-1178

ci: update chocolatey scripts

---

cli/cmd/generate_aws.go
cli/cmd/generate_aws_eks_audit.go
cli/cmd/generate_gcp.go
integration/test_resources/help/generate_cloud-account_aws
integration/test_resources/help/generate_k8s_eks
lwgenerate/aws/aws.go
lwgenerate/aws/aws_test.go
lwgenerate/aws_eks_audit/aws_eks_audit.go
lwgenerate/aws_eks_audit/aws_eks_audit_test.go

Include flag `lacework_aws_account_id` in generated TF Aws config and Aws Cloudtrail modules
Add new unit test:
`aws_test.TestGenerationWithLaceworkAccountID`
`eks_audit_test.TestGenerationEksSingleWithLaceworkAccountID`
https://lacework.atlassian.net/browse/GROW-1360

feat: add new flag to generate cmds set lacework aws root account

---

cli/cmd/awsiam.go
cli/cmd/awsiam_test.go

- Mocks to use struct instead of func types
- Reorganize mock structure
Expanding on the unit test mocks for `awsiam.go`.
Unit tests pass
https://lacework.atlassian.net/browse/RAIN-47429

test(cli): mock `awsiam.go` clients

---

api/reports_aws.go

`lacework compliance aws get-report`  with the  `--pdf` was not setting the report type in the request
Run `lacework compliance aws get-report <account-id> --type AWS_CIS_14 --pdf`
https://lacework.atlassian.net/browse/GROW-1392

fix(cli): set report type in compliance reports --pdf cmd

---

api/reports_gcp.go

`lacework compliance gcp get-report`  with the  `--pdf` was not setting the report type in the request
Run `lacework compliance gcp get-report <org-id> <project-id> --type GCP_CIS13 --pdf`
https://lacework.atlassian.net/browse/GROW-1394

fix(cli): set report type in gcp compliance reports --pdf cmd

---

cli/cmd/compliance.go
cli/cmd/compliance_aws.go
cli/cmd/compliance_azure.go
cli/cmd/compliance_gcp.go
integration/test_resources/help/compliance_aws_get-report
integration/test_resources/help/compliance_azure_get-report
integration/test_resources/help/compliance_google_get-report

As a user I would like to see valid inputs to the `--type` flag in the help text for `lacework compliance <cloud> get-report` cmd
- Manually run `lacework compliance <cloud> get-report --help`
- Update help text tests
https://lacework.atlassian.net/browse/GROW-1395

docs(cli): add valid report types to compliance get-report help text

---

.github/CODEOWNERS

Add growth-team to codeowners file

chore: add growth-team to CODEOWNERS file

---

api/v2_vulnerabilities.go
api/v2_vulnerabilities_test.go
cli/cmd/vuln_host_list_hosts.go
cli/cmd/vuln_host_show_assessment.go

- Change type of field  `MachineTags` in `VulnerabilityHost` to any to allow dynamic fields in json output
- Add new `func (v *VulnerabilityHost) GetMachineTags() (machineTags VulnerabilityHostMachineTags, err error)` for when access to named machineTags is required.
Manually run:
`lacework vuln host list-hosts <cve-id>`
`lacework vuln host list-hosts <cve-id> --json`
(observe results for both aws and gce hosts)
Unit tests:
- TestV2Vulnerabilities_HostGetAwsMachineTags
- TestV2Vulnerabilities_HostGetGcpMachineTags
- TestV2Vulnerabilities_HostGetEmptyMachineTags
https://lacework.atlassian.net/browse/GROW-1003

fix: update VulnerabilityHost MachineTags to support GCE host types

---

cli/cmd/policy_exceptions.go
cli/cmd/policy_exceptions_test.go
integration/policy_exceptions_test.go

During `lacework policy-exception create` prompt fetch the correct constraint keys for the policy
https://lacework.atlassian.net/browse/GROW-1397

feat(cli): show valid constraint keys for policy exception create prompt

---

lwcomponent/component_test.go

Adds a test for #1190 because ~~I want to make @afiune happy~~ it probably should have had one in the first place.

chore: add a test for #1190

---

cli/cmd/compliance_aws.go
cli/cmd/compliance_azure.go
cli/cmd/compliance_gcp.go

fix: report definition types

---

Makefile
cli/cmd/cloud_account.go
cli/cmd/generate_gcp.go
cli/cmd/integration_gcp_pub_sub_audit.go
integration/gcp_generation_test.go
integration/test_resources/help/generate_cloud-account_gcp
lwgenerate/constants.go
lwgenerate/gcp/gcp.go
lwgenerate/gcp/gcp_test.go

Addition of new Pub Sub Adit log integration for GCP - This generates the Terraform for the new integration which is supported by the latest lacework provider V1.5.0
Added to the Integration tests and unit test cases.
https://lacework.atlassian.net/browse/GROW-1400

feat(cli): Addition of generation of gcp pub sub audit log

---

integration/report_definitions_create_test.go

ci: disable report_definitions windows ci

---

cli/cmd/outputs.go
cli/cmd/version.go
integration/version_test.go

Change output of out of date version prompt from stdout to stderr. 
Update test `TestDailyVersionCheckEndToEnd`
https://lacework.atlassian.net/browse/GROW-1484

refactor: move version check output to stderr

---

go.mod

Ran `make go-vendor`
How to make sure that CI catches bugs like this?
https://lacework.slack.com/archives/C04CYEQ3W3G/p1680794620164499

chore(cli): run `make go-vendor` to fix release

---

cli/cmd/agent.go
cli/cmd/agent_install.go
integration/test_resources/help/agent_install

Follow-on to 070ce61fb929ef406b551905ef19f97a7c731c38.
Fixes RAIN-54457
Add the `server_url` flag to `lacework agent install`
This is the same change as for the other install commands, so I'm assuming it also works. That said, I don't know if there are integration tests for the normal `agent install` command. If there are, please let me know!
https://lacework.atlassian.net/browse/RAIN-54457

feat(cli): add `server_url` to `agent install` cmd

---

cli/cmd/agent.go
cli/cmd/agent_aws-install_ec2ic.go
cli/cmd/agent_aws-install_ec2ssh.go
cli/cmd/agent_aws-install_ec2ssm.go
cli/cmd/agent_gcp-install-osl.go
integration/test_resources/help/agent_aws-install_ec2ic
integration/test_resources/help/agent_aws-install_ec2ssh
integration/test_resources/help/agent_aws-install_ec2ssm
integration/test_resources/help/agent_gcp-install_osl
integration/test_resources/help/agent_install

Fixes RAIN-54457
Use a sample domain instead of `api.fra.lacework.net`, this is less confusing and more flexible around TopLS
CI should pass
https://lacework.atlassian.net/browse/RAIN-54528

chore(cli): use an example URL for CTF docs

---

api/cloud_accounts_aws_eks_audit.go

Used integration tests for the terraform that uses this api call
https://lacework.atlassian.net/browse/GROW-1532

fix(api): Omit s3 bucket arn from Aws EKS Audit if not set

---

integration/framework_test.go

Pipeline should not show `i/o: timeout` error no more.
N/A

ci: fix intermittency issues with virtual terminals

---

api/api.go
api/inventory.go
api/inventory_aws_test.go
api/inventory_test.go
cli/cmd/compliance_aws.go
cli/cmd/compliance_azure.go
cli/cmd/compliance_gcp.go
integration/compliance_aws_test.go
integration/compliance_azure_test.go
integration/compliance_gcp_test.go
integration/test_resources/help/compliance_aws_scan
integration/test_resources/help/compliance_azure
integration/test_resources/help/compliance_azure_scan
integration/test_resources/help/compliance_google
integration/test_resources/help/compliance_google_scan

Add support for `v2/inventory/scan`
New command `lacework compliance aws|gcp|azure scan`
Usage:
```
❯ lacework compliance aws scan
STATUS    scanning                 
DETAILS   Scan has been requested  
```
Tests
https://lacework.atlassian.net/browse/GROW-1205

feat(cli): New 'compliance scan' command

---

api/client.go
api/client_test.go
cli/cmd/cli_state.go
internal/lacework/server.go

Increase TLS timeout. This change fixes for https://lacework.atlassian.net/browse/LINK-1101
https://lacework.atlassian.net/browse/LINK-1101

fix: increase default TLS Handshake Timeout to 63s

---

cli/cmd/generate_gcp.go
integration/gcp_generation_test.go
integration/test_resources/help/generate_cloud-account_gcp
lwgenerate/gcp/gcp.go
lwgenerate/gcp/gcp_test.go
lwgenerate/hcl.go

https://developer.hashicorp.com/terraform/language/v1.1.x/meta-arguments/for_each
unit and integration test
`lacework generate cloud-account gcp --projects project1 --projects project2 --projects project3`
https://lacework.atlassian.net/browse/GROW-1502

feat: GCP multi project Terraform

---

cli/cmd/docs.go
scripts/docs/doc_gen.go

Readd the removed doc gen file.
https://lacework.atlassian.net/browse/GROW-1522

fix: readd doc gen file

---

go.mod
go.sum
integration/alert_close_test.go
integration/alert_list_test.go
vendor/github.com/hashicorp/consul/sdk/LICENSE
vendor/github.com/hashicorp/consul/sdk/testutil/retry/retry.go
vendor/modules.txt

Making TestAlertClose* tests more resilient
The change is to a test and is vetted by test automation
https://lacework.atlassian.net/browse/GROW-1544

test(cli): add --nocache to popalert 

---

cli/cmd/generate_azure.go
cli/docs/lacework_generate_cloud-account_azure.md
integration/test_resources/help/generate_cloud-account_azure

When generating terraform for an azure integration the command line option used is `terraform-apply` this is not consistent with gcp and aws which use simply `apply`, therefore this consistent these other cloud account integration options and simply use `apply`
Built the CLI and ran azure commands with combinations of `apply` and` terraform-apply `to ensure that both flags can be set, also made sure that `terraform-apply` is not shown when help flag showing list of command options is used 
https://lacework.atlassian.net/browse/GROW-1542

fix: consolidate terraform apply command across cloud-account cmds

---

api/client.go

Change http transport to copy of http.DefaultTransport with the updated TLS timeout setting

fix: http transport override ignoring default proxy settings

---

integration/gcp_generation_test.go
lwgenerate/gcp/gcp.go
lwgenerate/gcp/gcp_test.go

Update terraform generation for Pub Sub Audit log integrations
Terraform generated for Pub Sub Audit log was incorrect when Organization integration was chosen
Added unit, integration tests, also manually ran the CLI in interactive and non-interactive modes
https://lacework.atlassian.net/browse/RAIN-56497

fix: add correct terraform attribute for Pub Sub Audit log generation

---

cli/cmd/cloud_account.go

Make naming of the GCP Pub Sub Audit Log consistent throughout Lacework 
Manual test for `lacework cloud-account create`
https://lacework.atlassian.net/browse/GROW-1601

refactor: update name for GCP Audit Log cloud account

---

Makefile
integration/alert_close_test.go
integration/alert_rules_test.go
integration/azure_generation_test.go
integration/cloud_account_test.go
integration/configure_unix_test.go
integration/container_vulnerability_test.go
integration/context/ctx.go
integration/context/ctx.toml
integration/gke_generation_test.go
integration/report_definitions_create_test.go
integration/report_definitions_test.go
integration/team_members_test.go
scripts/integration_test_ctx.sh

A PR will no longer run every integration test. Only tests with relevant build tags will execute. In order for this to work a mapping of build tags and code files must be maintained. 
Add new make command `integration-context-tests`
Add new script `scripts/integration_test_ctx.sh`
Add new go file `ctx.go` to parse the mapping file and determine correct build tags to run
Add new `ctx.toml` file to map build tags to go files
Add comment trigger to replace `make integration-only` with `make integration-context-tests`
https://lacework.atlassian.net/browse/GROW-1396

test: run integration tests from changes

---

api/_examples/report-distributions/main.go
api/api.go
api/report_distributions_test.go
api/reports_distributions.go
api/v2.go
cli/cmd/report_distributions.go
cli/cmd/report_distributions_create.go
cli/cmd/report_distributions_update.go
integration/test_resources/help/report-distribution
integration/test_resources/help/report-distribution_create
integration/test_resources/help/report-distribution_list
integration/test_resources/help/report-distribution_show
integration/test_resources/help/report-distribution_update
lwseverity/severity.go

Add new commands for Report Distributions.
`lacework report-distributions list`
`lacework report-distributions show <id>`
`lacework report-distributions create`
`lacework report-distributions update <id>`
`lacework report-distributions delete <id>`
usage:
```
❯ lacework report-distributions list
GUID                                          NAME                FREQUENCY                       DEFINITION GUID                       
-----------------------------------------------------------+--------------------------------+-----------+-----------------------------------------------------------
MOCK_WK001HZV1S7WEPL9TV39SQQGIY2THVBWWSI8Z24ZTWBPG55           example distribution          daily       MOCK_WK001HZV1S7WEPL9TV39SQQGIY2THVBWWSI8Z24ZTWBPG12  
```
```
❯ lacework report-distributions …
```

feat(cli): New Report Distributions command

---

cli/cmd/api.go
integration/test_resources/help/api

Update docs for `lacework api` command.

docs(cli): remove API v1 refs and add examples

---

.github/workflows/commit-lint.yml
.gitlint
Makefile
scripts/githooks/commit-msg

New github action to validate commit messages
`commit-lint.yml`
`.gitlint`
https://jorisroovers.com/gitlint/latest/
Test locally with `gitlint --commit  <hash>`
Trigger Github Action on this PR https://github.com/lacework/go-sdk/actions/runs/5003665407/jobs/8965181458
https://lacework.atlassian.net/browse/GROW-1169

ci: create commit-lint.yml

---

api/client.go
api/client_test.go
api/http.go

Some users of the Go SDK may want failed API requests to be retried. This PR adds a new configuration option to the API client to allow this to be configured. The default is still to not do retries, to preserve the current behaviour.
A new automated test has been added with setups up a mock server that fails a request a couple of times before succeeding it. We then try it with no retrying and confirm this fails, and with some retrying to confirm it succeeds.

feat(api): Allow API client to be configured with a retrying policy

---

.gitlint
api/v2_vulnerabilities.go
api/v2_vulnerabilities_test.go
cli/cmd/vuln_container_show_assessments.go
cli/cmd/vuln_container_test.go
cli/cmd/vuln_host_show_assessment.go
cli/cmd/vuln_host_test.go
cli/cmd/vulnerability.go
cli/cmd/vulnerability_test.go
integration/container_vulnerability_test.go
integration/test_resources/help/vulnerability_container_show-assessment

Add new optional parameter to  'lacework vuln ctr show cmd' 
Usage:
```
❯ lacework vuln ctr show lacework vuln ctr show <sha> CVE-1234-56789             
CVE DETAILS                  
----------------------------------------------
CVE ID            CVE-2021-24215          
SEVERITY          Medium                  
PACKAGE           example                 
NAMESPACE         alpine:test             
FEED              lacework                
SRC                                       
START TIME        2022-11-14T00:20:57Z    
VERSION FORMAT    apk                     
CURRENT VERSION   1.00.0-r1               
FIX VERSION       1.20.00-r0              
STATUS            VULNERABLE              
INTRODUCED IN LAYERS …
```

feat(cli): New CVE-ID parameter to 'lacework vuln ctr show cmd'

---

api/_examples/cloud-accounts/oci-cfg/main.go
api/cloud_accounts.go
api/cloud_accounts_oci_cfg.go
api/cloud_accounts_oci_cfg_test.go

This PR adds support for OCI cloud account integration using the `api` object in go-sdk. The corresponding changes have already been made in the Lacework API. Adding OCI support to the CLI will be a separate PR.
I wrote unit tests to go along with this and ran them, along with existing unit tests in the `api` folder by typing `go test -v ./api/...`.
https://lacework.atlassian.net/browse/SPM-763

feat(api): Support OCI cloud accounts

---

integration/context/ctx.toml
lwgenerate/azure/test-data/activity-log-with-all-subscriptions.tf
lwgenerate/azure/test-data/activity-log-with-existing-storage.tf
lwgenerate/azure/test-data/activity-log-with-lacework-profile.tf
lwgenerate/azure/test-data/activity-log-with-list-subscriptions.tf
lwgenerate/azure/test-data/activity-log-with-location.tf
lwgenerate/azure/test-data/activity_log_with_config.tf
lwgenerate/azure/test-data/activity_log_without_config.tf
lwgenerate/azure/test-data/config-log-with-list-subscriptions.tf
lwgenerate/azure/test-data/config-with-all-subscriptions.tf
lwgenerate/azure/test-data/config-with-azurerm-subscription.tf
lwgenerate/azure/test-data/config-with-management-group.tf
lwgenerate/azure/test-data/config-with-storage-account.tf
lwgenerate/azure/test-data/config_without_activity_log.tf
lwgenerate/azure/test-data/customer-ad-details.tf
lwgenerate/azure/test-data/renamed_activity_log.tf
lwgenerate/azure/test-data/renamed_config.tf
lwgenerate/azure/test-data/renamed_config_and_activity_log.tf
lwgenerate/constants.go

Correct Azure module versions
https://registry.terraform.io/modules/lacework/activity-log/azure/latest
https://registry.terraform.io/modules/lacework/config/azure/latest

fix: azure module versions

---

cli/cmd/integration_oci.go

Adding OCI cloud integrations through `lacework cloud-account create` always fails because the private key gets incorrectly formatted. The Lacework API will only accept the private key in a PEM format, which looks like this:
```
-----BEGIN PRIVATE KEY-----
MIIBgjAcBgoqhkiG9w0BDAEDMA4ECKZesfWLQOiDAgID6ASCAWBu7izm8N4V
2puRO/Mdt+Y8ceywxiC0cE57nrbmvaTSvBwTg9b/xyd8YC6QK7lrhC9Njgp/
...
-----END PRIVATE KEY-----
```
The problem is the newlines. If you hit 'enter', the CLI will assume this is the end of the private key and you won't be able to input the rest of it. If you type '\n', the backslash gets automatically escaped, so this ends up being encoded as the characters '\\' and 'n' rather than the escape character '\n'. The solution is to ask for a path to the private key file, which makes much …

fix(cli): supply OCI integration private key as file to avoid mangling

---

integration/test_resources/help/generate_cloud-account_aws
integration/test_resources/help/generate_cloud-account_gcp
integration/test_resources/help/generate_k8s_eks
scripts/integration_test_ctx.sh

test: fix failing help tests

---

api/entities.go
api/entities_machines.go
api/v2_vulnerabilities.go
cli/cmd/vuln_host.go
cli/cmd/vuln_host_show_assessment.go
cli/cmd/vuln_host_test.go
cli/cmd/vulnerability.go
integration/context/ctx_cfg.go
integration/test_resources/help/vulnerability_host_show-assessment
integration/vulnerability_test.go
internal/array/contains.go
scripts/integration_test_ctx.sh

- Add new `collector_type` flag to `lacework vuln host show-assessement` cmd. To allow filtering by Agent/Agentless results
- Default `collector_type` is `Agentless`
- If no flag is set by the user and agentless results are not found, we automatically try agent
- If agentless flag is explicitly set by the user, and no agentless integration is found return error and link to docs.
Display collector_type in host details output
Manully run:
https://lacework.atlassian.net/browse/GROW-2294

feat: vuln host show-assessment filter by collector type

---

api/entities_machines.go
cli/cmd/vuln_host_show_assessment.go

Fix missing line length.
CI should pass. 
https://github.com/lacework/go-sdk/issues/941

style(lint): fix line length

---

Makefile
README.md
api/README.md
api/_examples/active-containers/main.go
api/_examples/alert-channels-v2/main.go
cli/cmd/docs.go
cli/main.go
lwcomponent/component.go
lwconfig/README.md
lwconfig/_examples/main.go
lwconfig/config.go
lwdomain/domain.go
lwgenerate/aws/aws.go
lwgenerate/azure/azure.go
lwgenerate/gcp/gcp.go
lwgenerate/hcl.go
lwlogger/README.md
lwlogger/logger.go
lwseverity/severity.go
lwtime/README.md
lwtime/_examples/natural-time/main.go
lwtime/_examples/relative-time/main.go
lwtime/epoch.go
lwtime/epochstring.go
lwtime/nanotime.go
lwtime/nattime.go
lwtime/reltime.go
lwupdater/README.md
lwupdater/updater.go

Making Go Docs prettier https://pkg.go.dev/github.com/lacework/go-sdk
I installed `godoc` and run it locally:
```
$ go install golang.org/x/tools/cmd/godoc@latest
godoc -http=localhost:6060
using module mode; GOMOD=/Users/afiune/github/go-sdk/go.mod
```
https://lacework.atlassian.net/browse/GROW-1535
Closes https://github.com/lacework/go-sdk/issues/1236

docs: https://pkg.go.dev/github.com/lacework/go-sdk

---

api/alert_rules.go

Remove invalid AlertRule eventCategory fields

fix: remove HostVulnerability & ContainerVulnerability values

---

cli/cmd/vuln_container_show_assessments.go
cli/cmd/vulnerability_test.go

`TestOutputContainerVulnerabilityAssessmentWithSingleCveMultipleResults` is intermittently failing
Ensure  `TestOutputContainerVulnerabilityAssessmentWithSingleCveMultipleResults` passes
https://lacework.atlassian.net/browse/GROW-2348

test: fix failing vuln test

---

Makefile
api/alert_channels.go
api/alert_profiles.go
api/alert_rules.go
api/compliance_evaluations.go
api/container_registries.go
api/inventory.go
api/policy.go
api/report_rules.go
api/resource_groups.go
api/team_members.go
api/vulnerability_exceptions.go
cli/cmd/flags.go
cli/cmd/policy_delete.go
integration/compliance_azure_test.go
integration/component_test.go
internal/format/strings.go
lwcomponent/error.go

Ran `make fmt` to fix these issues.
Ran `make fmt-check` and `make imports-check` and they passed.
Also, fixed the Codefresh pipeline to exit when issues arise.
N/A

style(fmt): fixed imports-check directive

---

lwupdater/updater.go

We've started seeing some intermitted failures with a 403 status code in this code. This PR adds some retrying so that if this is due to rate limiting as we suspect we will succeed after retrying.
Manual testing to confirm things are still working normally. Hard to confirm if this will fix things as the issue above is intermittent.
https://lacework.atlassian.net/browse/COD-1559

fix(COD-1559): Add some retrying in `updater.go`

---

lwupdater/updater.go

Requires env var set `DEBUG`
Add logging for headers when github api response does not succeed

chore: add debug logging for updater

---

cli/cmd/resource_groups.go

I forgot to delete the additions I made to the list here. RGv2 entries already get populated a few lines below with the toggling of the feature flag.

fix: Remove duplicated entries for v2 RGs in create command

---

Makefile
integration/cloud_account_test.go

`cloud_account` integration tests have not been running on nightly build and are failing.
https://lacework.atlassian.net/browse/GROW-2414

test: enable 'cloud_account' test for 'make integration-only'

---

api/alerts_close.go
cli/docs/lacework_alert_close.md
integration/test_resources/help/alert_close

Add support for alert close reason 'Expected Behavior'.
Manual
https://lacework.atlassian.net/browse/GROW-2295

feat(cli): add 'Expected Behavior' alert close reason 

---

cli/cmd/component.go
lwcomponent/component.go

A customer found that component installation would take ~30 minutes to complete.  This change provides more CLI information and honeycomb telemetry
Local testing:
- install iac
- update iac
- uninstall iac
https://lacework.atlassian.net/browse/GROW-2446

feat: CDK component install telemetry

---

api/_examples/components/main.go
api/api.go
api/components.go
api/components_test.go
api/v2.go

Adding the Lacework `Components` API to the go-sdk
unit testing
https://lacework.atlassian.net/browse/GROW-2329

feat(GROW-2329): CDK api

---

api/alert_rules.go

Add `OCI` to the AlertSources
run `make test`

feat(SPM-1183): support OCI source for alert_rules

---

.github/workflows/chocolatey-release.yml
.github/workflows/windows-integration.yml

ci: fix windows GH actions

---

.github/workflows/windows-integration.yml
integration/help_test.go

Fixes our Windows integrations tests since they were not working before.
Ran the Windows Integration Tests  ✅  Successfully!
https://github.com/lacework/go-sdk/actions/runs/6699700105/job/18204345299
N/A

fix(ci): windows integration tests

---

Makefile

feat(Makefile): build CLI simpler & faster

---

Makefile
cli/cmd/cli_unix.go
cli/cmd/cli_windows.go
cli/cmd/generate.go
cli/cmd/generate_aws.go
cli/cmd/generate_aws_test.go
cli/docs/lacework_generate_cloud-account_aws.md
integration/aws_generation_test.go
integration/test_resources/help/generate_cloud-account_aws
integration/test_resources/help/generate_cloud-account_aws_controltower
lwgenerate/aws/aws.go
lwgenerate/aws/aws_test.go
lwgenerate/constants.go

- Refactor the UX of `lacework generate cloud-account aws` according to the [proposal](https://docs.google.com/document/d/1-sStyx3FoNkGw79ywUTEIGgzM7orX2wLrBn7ELywT1w/edit#heading=h.w5ighgm8d8px).
`make test`
`make integration-generation`
https://github.com/lacework/go-sdk/assets/7945666/5932d026-7781-43d7-a0a5-da128991bcd4
https://lacework.atlassian.net/browse/GROW-2563

feat: refactor UX for lacework generate cloud-account aws

---

cli/cmd/component.go
lwcomponent/catalog.go
lwcomponent/cdk_component.go

CDK lifecycle events.
```
> lacework component install component-example --version 0.7.34
[✓] Component component-example found
[✓] Component component-example staged
[✓] Component signature verified
[✓] Component version 0.7.34 installed
[✓] Component configured
Installation completed.
CDK example component
```
```
> lacework component update component-example
[✓] Component component-example found
[✓] Component component-example staged
[✓] Component signature verified
[✓] Component component-example updated to 0.7.35
[✓] Component reconfigured
This message will be shown in the CLI when the component is updated, i.e. a new version is installed. \n This is an optional field. \n If not provided the CLI will present the user with instructions on how to run the component. \n This message has …
```

feat: CDK v1 component lifecycle events

---

.github/workflows/code-analysis-sca.yml
.github/workflows/lacework-code-analysis.yml

https://lacework.atlassian.net/browse/GROW-2599
Follow the instructions in https://github.com/lacework/code-security-action to integrate SCA with GitHub Actions
https://github.com/lacework-dev/growth-team-github-actions-playground/pull/1

ci: add GitHub workflow for SCA

---

lwgenerate/aws_eks_audit/aws_eks_audit.go
lwgenerate/aws_eks_audit/aws_eks_audit_test.go

* Allow disabling the writing of the required_providers block; useful when generating code alongside the EKS code
* Ensure AWS profile name is included in provider block when provided
* Allow adding a prefix to provider aliases to prevent conflicts; useful when generating code alongside the EKS code
Tests and manual execution
https://lacework.atlassian.net/browse/GROW-2607

chore(lwgenerate): enable eks provider configuration

---

api/api.go
api/metrics.go
api/v2.go
cli/cmd/cli_state.go
cli/cmd/honeyvent.go
cli/cmd/honeyvent_test.go
integration/policy_exceptions_test.go

Refactor Honeycomb events
Add support for Lacework Api `metrics/honeycomb`
Send only dev events(for now) to new endpoint
Move Honeyvent struct to api pkg
https://lacework.atlassian.net/browse/GROW-2649

refactor: dev honeycomb events to use lacework api

---

api/metrics.go

Set additional properties for honeycomb metrics

chore: set account details for honeycomb metrics

---

lwgenerate/gcp/gcp.go
lwgenerate/gcp/gke.go
lwgenerate/gcp/gke_test.go

- Add terraform google provider alias for GKE
- Make required providers optional for GKE
make test
https://lacework.atlassian.net/browse/GROW-2659

chore: GKE alias and make required providers optional

---

api/metrics.go
api/metrics_test.go

MetricsService Send() will not post data to lacework when `LW_TELEMETRY_DISABLE` is set.
This will allow Terraform provider and modules to disable telemetry in the same way as the CLI
https://lacework.atlassian.net/browse/GROW-2627

chore: add 'LW_TELEMETRY_DISABLE' env var for metrics service

---

.github/workflows/test-build.yml

Migrate Codefresh [go-sdk/test-build](https://g.codefresh.io/pipelines/edit/workflow?id=601309a0b0dae020a9cf1275&pipeline=test-build&projects=go-sdk&projectId=60118409468eb5f1e534734f&rightbar=triggers&advanced=0) to GitHub actions
https://github.com/lacework/go-sdk/actions/runs/7908492159/job/21587784031?pr=1534
https://lacework.atlassian.net/browse/GROW-2758

ci: Create workflow test-build.yml

---

.github/workflows/update-cli-docs.yml

Migrate Codefresh pipeline [go-sdk/update-cli-docs](https://g.codefresh.io/pipelines/edit/workflow?id=6195c76a9ff69e309286d4ec&pipeline=update-cli-docs&projects=go-sdk&projectId=60118409468eb5f1e534734f&rightbar=variables) to Github Actions
https://github.com/lacework/go-sdk/actions/runs/7877121554
https://lacework.atlassian.net/browse/GROW-2758

ci: Create workflow update-cli-docs.yml

---

.github/workflows/update-homebrew-formula.yml

Migrate Codefresh pipeline [homebrew-tap/update-formula](https://g.codefresh.io/pipelines/edit/workflow?id=60929af67c5a183ff0ef1d14&pipeline=update-formula&projects=homebrew-tap&projectId=6092887672d3d79b5ad01747&rightbar=triggers) to Github Actions
https://github.com/lacework/go-sdk/actions/runs/7874850564?pr=1532
https://lacework.atlassian.net/browse/GROW-2757

ci: Create workflow update-homebrew-formula.yml

---

.github/workflows/verify-release.yml

Migrate Codefresh pipeline [go-sdk/verify-release](https://g.codefresh.io/pipelines/edit/workflow?id=6099c247b272737887ecc27b&pipeline=verify-release&projects=go-sdk&projectId=60118409468eb5f1e534734f&rightbar=triggers) to Github Actions
https://github.com/lacework/go-sdk/actions/runs/7893799966/job/21543156486?pr=1537
https://lacework.atlassian.net/browse/GROW-2757

ci: Create workflow verify-release.yml

---

.github/workflows/prepare-release.yml

Migrate Codefresh pipeline [go-sdk/prepare-release](https://g.codefresh.io/pipelines/edit/workflow?id=6056d5fc38440b2594554e86&pipeline=prepare-release&projects=go-sdk&projectId=60118409468eb5f1e534734f&rightbar=triggers&advanced=0) to Github Actions
https://github.com/lacework/go-sdk/actions/runs/7893672345/job/21542750417?pr=1536
https://lacework.atlassian.net/browse/GROW-2757

ci: Create workflow prepare-release.yml

---

.github/workflows/prepare-release.yml

GITHUB_TOKEN env is needed in prepare-release.yml

chore: add GITHUB_TOKEN env to prepare-release.yml

---

cli/cmd/component.go
integration/component_test.go
lwcomponent/catalog.go
lwcomponent/catalog_test.go
lwcomponent/staging_test.go

Improving component testing.  Added the `PUBLIC.cdk.v4` feature flag.
Unit, integration, local manual.

feat: CDK v4 feature flag

---

integration/alert_list_test.go

Fix broken alert integration tests
check for the existence of required test data, only execute if present
example skip: https://github.com/lacework/go-sdk/actions/runs/8523947621/job/23347405619?pr=1608
N/A

fix: failing tests due to transient data states

---

integration/framework_test.go
integration/gcp_generation_test.go
integration/gke_generation_test.go

Fix Terraform & GCP generation tests.
Integration tests
N/A

fix: correct integration tests for gcp

---

cli/cmd/cloud_account.go
cli/docs/lacework_cloud-account.md
integration/test_resources/help/cloud-account
integration/test_resources/help/cloud-account_migrate

This PR adds a change to make the documentation surrounding the `cloud-account migrate` cmd more descriptive to avoid any confusion.
Tested by running locally.
[RAIN-92200](https://lacework.atlassian.net/browse/RAIN-92200)
[RAIN-92200]: https://lacework.atlassian.net/browse/RAIN-92200?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(cli): update cloud-account migrate cmd desc

---

lwgenerate/gcp/gcp.go
lwgenerate/gcp/gcp_test.go
lwgenerate/gcp/gke.go

Add support for GCP default labels
Added unit tests.

feat(GROW-2931): Add support for GCP default labels

---

lwgenerate/gcp/gcp.go
lwgenerate/gcp/gcp_test.go

fix(GROW-2931): GCP default label should be attributes.

---

integration/vulnerability_test.go

Fix broken integration test (fix host-id).
See executed unit tests on this PR.
N/A

fix: vuln integration test host id

---

integration/aws_generation_test.go
lwgenerate/aws/aws.go

Support bucket encryption for existing cloudtrail

feat: Support bucket encryption for existing cloudtrail

---

lwgenerate/aws/aws.go

feat: Add support for use random cloudtrail name

---

lwgenerate/constants.go

AWS config organization terraform module 0.X no longer working due to introduce secret ARN after https://lacework.atlassian.net/browse/GROW-2579. Need to upgrade to 1.X.

feat: Upgrade aws config org version to 1.0

---

integration/resource_groups_test.go

fix: Fix failed resource group tests

---

lwgenerate/aws/aws.go

fix: Add credentials to control tower accounts

---

lwcomponent/catalog_test.go
lwcomponent/cdk_component.go
lwcomponent/cdk_component_test.go

fix(COD-4672): Default to Installed if apiInfo is nil and hostInfo is not nil

---

cli/cmd/vuln_host_show_assessment.go
cli/cmd/vuln_host_test.go

fix: Add missing csv header for host vuln

---

cli/cmd/generate_azure.go
cli/cmd/generate_azure_test.go
integration/azure_generation_test.go
integration/compliance_aws_test.go
test.txt

Summary
Refactor the UX of lacework generate cloud-account azure
Related JIRA:
https://lacework.atlassian.net/browse/CAD-838
Screen shots:
Tests performed:
1. Activity log integration successful.
2. Azure configuration integration successful.

feat: refactor UX for lacework generate cloud-account azure

---

cli/cmd/vuln_host_scan_package_manifest.go
cli/docs/lacework_vulnerability_host_scan-pkg-manifest.md
integration/alert_list_test.go
integration/test_resources/help/vulnerability_host_scan-pkg-manifest

Made a small edit to remove a now-obsolete limitation .
Mantis: 1187602

docs: Correcting limitation for  lacework vulnerability host scan-pkg-manifest command.
